### ISSUE TITLE
WX350

### ISSUE THREAD

**Issue by drdog29** [ma1co/Sony-PMCA-RE#101]
I want to solve " running on NTSC ".
Another camera that I own, WX20, ran the program without difficulty.
However, this program is not installed on the WX350 camera.
I downloaded and ran the file " pmca-gui-v0.17-win ".
There is no problem until " get camera info ", but in the " install app " window, select and run the tweak and the following error message appears.

Loading app list
Found 10 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-WX350 is a camera in MTP mode

Model:              DSC-WX350
Product code:       xxxxxxxxxxx
Serial number:      xxxxxxxxxx
Firmware version:   2.00

Loading app list
Found 10 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-WX350 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

There was no problem with my other camera, but I do not know why there is a problem with only the WX350.
Let me know if you have a solution.
Have a nice day.

I used in window 10 explorer

**Comment by ma1co** [comment]
The WX350 doesn't support android apps. Please use the _Tweak_ tab in pmca-gui instead.

**Comment by drdog29** [comment]
Thank you for your kindness.
I'll try again.
May I ask you again if it doesn't work?
Thank you.
 




 
-----Original Message-----

**Comment by ma1co** [comment]
Of course, feel free to re-open the issue.
