### ISSUE TITLE
Stuck in updater mode after I ran pmca-console updatershell in windows PowerShell ISE

### ISSUE THREAD

**Issue by thegallivanter** [ma1co/Sony-PMCA-RE#104]
Hi ma1co en nuggerwell, great work on fwtool, pmca-re and open memories! Years ago I looked at nex-hack for the first time and really hoped something like this would be done. Nice work!

I wanted to remove the 30 minute record limit on my old nex-3. I downloaded the pmca-console (windows) and went to it in PowerShell ISE. Then in PowerShell I ran 'pmca-console updatershell', which started out fine. 

Then the updatershell told me how to issue commands, but I could not type anything. Probably because PowerShell ISE is weird? I had to close PowerShell, but now my nex-3 is stuck in updater mode.

If I try to access the camera I get the message below. Do you guys know how to get my camera out of updater mode? Even disconnecting and reconecting and flipping the power switch dont change anything. 

Im hesitant to remove the battery, the camera seems to still be running even though the screen is black. But these sony batteries run out quick so will be drained before I know what to do probably.

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in updater mode

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 64, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 244, in infoCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 251, in getCameraInfo
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
[6168] Failed to execute script pmca-console

**Comment by thegallivanter** [comment]
Ok after the battery ran out, when I put a new battery in it, the camera was out of updater mode. Just booted normally and can access the camera through usb normally.
