### ISSUE TITLE
Clicking get camera information comes up with the following errors/messages

### ISSUE THREAD

**Issue by NareRusco** [ma1co/Sony-PMCA-RE#105]
OS: Windows 10 x64

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 230, in infoCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 159, in importDriver
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 25, in <module>
  File "C:\Python36\lib\site-packages\comtypes\client\_generate.py", line 97, in GetModule
  File "C:\Python36\lib\site-packages\comtypes\typeinfo.py", line 485, in LoadTypeLibEx
  File "_ctypes/callproc.c", line 918, in GetResult
OSError: [WinError -2147312566] Error loading type library/DLL

**Comment by ymkim92** [comment]
Now I can run pmca-gui.py, but only in Ubuntu, not Windows.
I just follow the instruction at here: 
https://github.com/ma1co/Sony-PMCA-RE/pull/91/commits/8b745f5e8808475c272852cec190291378441518 

I don't know how to fix this problem in Windows

**Comment by ma1co** [comment]
Are you using the Windows N version? Apparently you need the Media Feature Pack to communicate with MTP devices. See #92.
