### ISSUE TITLE
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4.." when installing apps

### ISSUE THREAD

**Issue by simoautio** [ma1co/Sony-PMCA-RE#117]
I keep getting this error:

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 291, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 61, in installApp
  File "C:\projects\sony-pmca-re\pmca\marketserver\server.py", line 61, in __init__
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 7: invalid continuation byte

when trying to install apps. Tweaking firmware worked fine, and app installation is enabled. I'm on firmaware 2.01 and windows 10, any ideas how i could get past this?

**Comment by simoautio** [comment]
Maybe relevant to the case as well:

Model:              ILCE-6300
Product code:       0032828110
Serial number:      03414140
Firmware version:   2.01
Lens:               Model 0x10a08011 (Firmware 2.04)

**Comment by ma1co** [comment]
You probably have some weird characters in your computer name (hostname).

**Comment by ma1co** [comment]
This should be fixed with 01a6df32086c4e486a9562fd42762f87c6ef0f3e.
