### ISSUE TITLE
Can't switching to app install mode on my AX55(AX53)

### ISSUE THREAD

**Issue by apychan** [ma1co/Sony-PMCA-RE#12]
It's seems to be no app install mode on Sony Handycam.
Any way to intall app on Handycam by using PMCA-RE?

```
pmca install
Using Windows drivers
Looking for Sony devices

Querying MTP device
Sony Corporation FDR-AX55 is a camera in MTP mode
Switching to app install mode. Please run this command again when the camera has switched modes.
Traceback (most recent call last):
  File "<string>", line 172, in <module>
  File "<string>", line 166, in main
  File "<string>", line 102, in installCommand
  File "<string>", line 28, in switchToAppInstaller
  File "pmca\usb\sony.py", line 153, in switchToAppInstaller
  File "pmca\usb\sony.py", line 122, in _sendCommand
  File "pmca\usb\sony.py", line 75, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006
pmca returned -1
```

**Comment by ma1co** [comment]
It seems that app install mode is indeed disabled on camcorders. *libInfraScalarExtCmdPlugIn.so* checks the boolean property *0x01640001* in the backup file before enabling the app install usb command with EXTCMD_ATTACH_CMD. This flag is not set on any camcorder, except the AS100V.

So I have to disappoint. For now, there is no way to install apps on camcorders.

**Comment by ma1co** [comment]
You should be able to enable app installation using `pmca-console updatershell` or the _Tweak_ tab in pmca-gui. You can then install the [launcher app](https://github.com/ma1co/OpenMemories-Launcher).
