### ISSUE TITLE
Errors Using with FDR-AXP35

### ISSUE THREAD

**Issue by Serpentor** [ma1co/Sony-PMCA-RE#156]
I am trying to unlock English on this camera since it is Japanese only.  When I attempt to unlock protected settings (a requirement to unlock the other languages), I get this error.

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 168, in do
  File "C:\projects\sony-pmca-re\pmca\usb\usbshell\__init__.py", line 117, in setTweakEnabled
  File "C:\projects\sony-pmca-re\pmca\usb\usbshell\__init__.py", line 71, in _req
pmca.usb.usbshell.UsbShellException: Unknown error

I have also tried to install the Tweaks app on the install tab hoping to make changes that way, but I get these errors.

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

I am at a loss.  Nothing works.  Has anyone with this camera been successful?

**Comment by Serpentor** [comment]
Not sure if anyone reads this help forum or is available to assist anymore, but I wanted to update this by saying I just tried Windows 7.1 and got the exact same results.  I really, REALLY like this camera but can't use it in Japanese.  If anyone has any idea how to get this working, please help.  It will be greatly appreciated!

**Comment by Serpentor** [comment]
Does anyone support this tweak or is it dead?  Any help is appreciated.

**Comment by Serpentor** [comment]
@ma1co I have uploaded the nflasha and boot1 through boot5 files to your dropbox.  I hope it is possible to add the FDR-AXP35 to the tweak.  It is listed as supported, but I have never been able to make it work.

**Comment by Serpentor** [comment]
@ma1co I have uploaded the nflasha and boot1 through boot5 files to your dropbox. I hope it is possible to add the FDR-AXP35 to the tweak. It is listed as supported, but I have never been able to make it work.
