### ISSUE TITLE
Trying to force firmware update on ILCE-6000 (a6000)

### ISSUE THREAD

**Issue by thepixelshawn** [ma1co/Sony-PMCA-RE#160]
Tried updating the firmware on my a6000 from v3.20 to v3.21 using the official Sony updater, but after quite a few attempts (on two PCs, taken the battery out to de-charge and re-charge, etc, etc) I'm still left with a black screen and solid red battery indicator light on the device.

Using this tool, whenever I test the USB connection/'Get camera info' I get this:

```
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in updater mode

Getting device info
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 116, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 349, in updaterShellCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 251, in getCameraInfo
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
```

Then I tried using the console to force the firmware update using `pmca-console firmware -f FirmwareData_ILCE6000V321.dat`, but after Writing firmware to 60%, I get this:

```
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 80, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 334, in firmwareUpdateCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 411, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 542, in writeFirmware
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 492, in _sendWriteCommands
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 479, in _sendCommand
Exception: Response error: 0x1043
[11244] Failed to execute script pmca-console
```

I'm thinking I need to swap the connection mode back to MTP to successfully update the firmware. But is this even possible with a device black screen? In other words, is there a way to switch USB connection modes remotely from a PC?

Either way, I'm at a lost and wondering if I bricked my device completely. And if that's the case, is it worth it to contact Sony for repairs?

**Comment by ma1co** [comment]
You can try the following:
`pmca-console updatershell -m ILCE-6000`

This should bring you to the updater shell. Please send me the output of running `shell ls -lR /setting` in there.

**Comment by whattheshawn** [comment]
Hi @ma1co. Sorry for the terribly long delay! Here's the output when running `shell ls -lR /setting`:

```
/setting:
-rwxrwxrwx    1 0        0          852647 Jan  1 00:05 Backup.bak
-rw-r--r--    1 0        0          852647 Jan  1  1980 Backup.bin
-rw-r--r--    1 0        0           94916 Jan  1 00:00 DmmConfig.bin
drwxr-xr-x    2 0        0           16384 Jan  1 00:00 appfw_infra
-rw-r--r--    1 0        0           51200 Jan  1 00:00 facedmy.bin
drwxrwxrwx    2 0        0           16384 Jan  1  1980 gps
-rw-r--r--    1 0        0         1346048 Jan  1 00:00 init_bk.bak
-rw-r--r--    1 0        0            2516 Jan  1 00:00 kemco.txt
drwxrwxrwx    2 0        0           16384 Jan  1  1980 mode
-rw-r--r--    1 0        0         4182016 Jan  1  1980 psd.bin
-rw-r--r--    1 0        0            3236 Jan  1 00:00 ulogio.bin
drwxr-xr-x    2 0        0           16384 Jan  1 00:00 updater

/setting/appfw_infra:

/setting/gps:

/setting/mode:

/setting/updater:
-rw-rw-rw-    1 0        0               2 Jan  1 00:01 dat4
-rwxrw-rw-    1 0        0               0 Jan  1 00:04 mode
```
Thanks for taking the time to look at this if you ever get around to it again!

**Comment by ma1co** [comment]
In the same shell, you can try running the following command: `shell rm /setting/updater/mode`
Then `exit` to restart.
There is a small chance that this bricks your camera completely (depending on how wrong the firwmare update went), but I'm fairly confident that it might restore your camera.
