### ISSUE TITLE
MTP Error 0x2006 - RX100M6

### ISSUE THREAD

**Issue by BattleNonSense** [ma1co/Sony-PMCA-RE#166]
Tested on 2 different PC`s. Can`t install the tweak app

`Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M6 is a camera in MTP mode

Model:              DSC-RX100M6
Product code:       0080817650
Serial number:      02913024
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M6 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006`

**Comment by Peter807** [comment]
I have the same issue with my Sony RX10M4. MTP error 0x2006.
Someone any solutions?
![Sony RX10M4 tweak](https://user-images.githubusercontent.com/59140092/71322470-67caf680-24fa-11ea-9fa3-0ae9cacbb667.jpg)

**Comment by kokohkekar** [comment]
I have the same problem with my Sony A7R3. 

It worked alright on my Sony A6500 (installing the OpenMemories: Tweak apps)

**Comment by khunpoum** [comment]
i have the same problem with my RX100M5A (RX100VA) 
MTP error 0x2006

**Comment by taufiq1926** [comment]
i have some problem, is there solving from it?

**Comment by taufiq1926** [comment]
> I have the same problem with my Sony A7R3.
> 
> It worked alright on my Sony A6500 (installing the OpenMemories: Tweak apps)

how the solving?

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for these camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

If you manage to run it on the RX100M6, I would be interested in a firmware dump. You can dump the firmware using `pull /dev/nflashaB0` and `pull /dev/nflasha` in serviceshell. Please upload the files to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx). Thanks!

**Comment by vitorross** [comment]
Hi @ma1co I don't know how to use GitHub properly, and I don't understand anything about programming, I'm here looking and trying to change the language of my Sony HDR-CX470, but it's not one of the devices that has coverage, do you know any other way to change the language?

Thank You!
