### ISSUE TITLE
Mass storage error. AS100V

### ISSUE THREAD

**Issue by Rexarn** [ma1co/Sony-PMCA-RE#167]
I've tried everything, running as admin, replugging cables, wiping my arse, selling my soul to satan and trying different different options for about 5 hours straight (it's 9:05 AM right now). These errors came after 
Open Memories: Appstore (and the other Open Memories thing)
And the one i want the most, a live feed (like the gopro 10.0.0.5/live.mp3u)

"Start tweaking mode" makes my camera freeze saying "Wait"

These are my errors.

Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Model:              HDR-AS100V
Product code:       0002426614
Serial number:      03662823
Firmware version:   2.00
GPS Data:           2019-12-27 00:00:00 - 2020-01-26 00:00:00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

PLEASE, help me guys. I'm using the latest release of the program and i have installed newest python and python 2.7.. PLEEEEEEASE.....

**Comment by ma1co** [comment]
Click the "Start tweaking" button and when the log tells you to follow the instructions on the camera, then press the record button.

**Comment by David-tech-2021** [comment]
> Click the "Start tweaking" button and when the log tells you to follow the instructions on the camera, then press the record button.

Hello Rexarn and ma1co, I have roughly the same problem if I may.
Once I hit the install OpenMeomories: Tweak, I the following massage:

Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Using firmware for model ILCE-7M3

Unknown device: ILCE-7M3

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

appart from that I'm blocked and will be happy to get any assistance.

**Comment by ma1co** [comment]
The ILCE-7M3 is currently not supported.

**Comment by David-tech-2021** [comment]
Thanks! So was my feeling. I'll buy an external recorder to solve the
problem

David Koren
Kameramann, Cutter, Regisseur
0178-1645089
***@***.***

*LivenberliN *Produktion/Studio
*www.livenberlin.site <http://www.livenberlin.site>*


Am Do., 12. Aug. 2021 um 11:23 Uhr schrieb ma1co ***@***.***>:
