### ISSUE TITLE
Sony A7RM3 - Error App Install Mode

### ISSUE THREAD

**Issue by kokohkekar** [ma1co/Sony-PMCA-RE#168]
I need help with the problem, I am having as follow,

**Get Camera Info successfully executed with the following result:**
Querying MTP device
Sony Corporation ILCE-7RM3 is a camera in MTP mode

Model:              ILCE-7RM3
Product code:       0032829340
Serial number:      04472751
Firmware version:   3.01
Lens:               Model 0x13a0802d (Firmware 3.00)

**Installing OpenMemories: Tweak failed with the following error messages:**
Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

**Comment by protectedMan** [comment]
3代机器本身就不支持安装app吧

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
