### ISSUE TITLE
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by DaKiGbg** [ma1co/Sony-PMCA-RE#17]
Hi! I tried to install the STG Uploader using pmca-gui v0.7 and got the following error message, I've tried in both MTP and mass storage mode and get the "same" error message.

Using Windows drivers
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX60V is a camera in app install mode

Using remote server sony-pmca.appspot.com
Uploading apk
Traceback (most recent call last):
  File "<string>", line 74, in do
  File "pmca\commands\usb.py", line 186, in installCommand
  File "pmca\commands\usb.py", line 53, in installApp
  File "pmca\marketserver\server.py", line 126, in setApk
  File "pmca\util\http.py", line 31, in get
  File "pmca\util\http.py", line 44, in request
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 449, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1240, in https_open
  File "urllib2.py", line 1197, in do_open
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

BR
Daniel

**Comment by ma1co** [comment]
@DaKiGbg Which operating system?

**Comment by ma1co** [comment]
It's still weird... Does the gui load the app list into the combo box? Or does that give an error, too?

**Comment by DaKiGbg** [comment]
No, no app list using the gui, that did however also work using the web
interface.

Den 24 juli 2016 8:07 em skrev "ma1co" <notifications@github.com>:
>
> It's still weird... Does the gui load the app list into the combo box? Or
does that give an error, too?

**Comment by ma1co** [comment]
Do you have some antivirus software running which intercepts all https traffic?

**Comment by sonic74** [comment]
My Norton 360 intercepted the traffic, but this resulted in another error message about missing socket permissions. After unblocking, I get the same error message CERTIFICATE_VERIFY_FAILED.

**Comment by Bostwickenator** [comment]
I'm thinking this has to be something to do with the AWS issued SSL
certificates.
