### ISSUE TITLE
Issue with Sony SLT-A65

### ISSUE THREAD

**Issue by xavdr** [ma1co/Sony-PMCA-RE#171]
Hi, I get this message while run `pmca-console.py`:

```
M:\MACH-L\Sony-PMCA-RE-0.17>python pmca-console.py info
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation SLT-A65 is a camera in MTP mode

Traceback (most recent call last):
  File "pmca-console.py", line 96, in <module>
    main()
  File "pmca-console.py", line 64, in main
    infoCommand(args.driver)
  File "M:\MACH-L\python-LIB\pmca\commands\usb.py", line 255, in infoCommand
    lensInfo = dev.getLensInfo()
  File "M:\MACH-L\python-LIB\pmca\usb\sony.py", line 319, in getLensInfo
    info = self.MountedLensInfo.unpack(self._sendCommand(self.SONY_CMD_LensCommunicator_GetMountedLensInfo))
  File "M:\MACH-L\python-LIB\pmca\usb\sony.py", line 244, in _sendCommand
    ) + data).ljust(writeBufferSize, b'\0'), readBufferSize)
  File "M:\MACH-L\python-LIB\pmca\usb\sony.py", line 97, in sendSonyExtCommand
    response = self.driver.sendWriteCommand(self.PTP_OC_SonyDiExtCmd_write, [cmd], data)
  File "M:\MACH-L\python-LIB\pmca\usb\driver\windows\wpd.py", line 177, in sendWriteCommand
    return self._readResponse(context)
  File "M:\MACH-L\python-LIB\pmca\usb\driver\windows\wpd.py", line 149, in _readResponse
    result = self._send(params)
  File "M:\MACH-L\python-LIB\pmca\usb\driver\windows\wpd.py", line 144, in _send

    raise Exception('MTP SendCommand failed: 0x%x' % code)
Exception: MTP SendCommand failed: 0x-7ff8fb71
```
After getting this error camera seems to be restarting - screen turns to black, some mechanical click, and then again establishing MTP USB-connection.

I have ran both `pmca-console-v0.17-win.exe` and `pmca-gui-v0.17-win.exe` and python library itself on my portable python 3.7 installation.

**Comment by viplike** [comment]
the same issue on a77

**Comment by xavdr** [comment]
> @xavdr I have the same issue on a77, any success with your camera?
forgot details, use Mass Storage mode (switch in menu)
