### ISSUE TITLE
camera RX100M5A (RX100VA) is not supported

### ISSUE THREAD

**Issue by khunpoum** [ma1co/Sony-PMCA-RE#179]
camera RX100M5A (RX100VA) is not supported

pmca-console install -o outfile.txt
`
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M5A is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 72, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006
[29732] Failed to execute script pmca-console
`

pmca-console install -i
`Loading app list
Found 11 apps
 [ 1] com.github.ma1co.openmemories.tweak
 [ 2] com.jonasjuffinger.timelapse
 [ 3] com.github.ma1co.openmemories.appstore
 [ 4] com.obsidium.focusbracket
 [ 5] com.obsidium.bettermanual
 [ 6] org.bostwickenator.dofmath
 [ 7] org.bostwickenator.googlephotos
 [ 8] com.github.ma1co.pmcademo.app
 [ 9] org.bostwickenator.ftpuploader
 [10] com.github.LubikR.synologyuploader
 [11] info.schnatterer.pmcaFilesystemServer
Enter number of app to install (0 to abort): 2

Installing com.jonasjuffinger.timelapse
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M5A is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 72, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006
[19540] Failed to execute script pmca-console`

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).

If you manage to run it, I would be interested in a firmware dump. You can dump the firmware using `pull /dev/nflashaB0` and `pull /dev/nflasha` in serviceshell. Please upload the files to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx). Thanks!

**Comment by khunpoum** [comment]
Already upload dump of my rx100m5a before changes.

All tweaks apply, but one is not apply
```
Enter number of tweak to toggle (0 to finish): 1
Success

1: [X] Disable video recording limit
       13h 01m 00s

2: [ ] Unlock all languages
       13 / 35 languages activated

3: [X] Enable PAL / NTSC selector & warning
       Enabled

4: [X] Enable USB app installer
       Enabled

5: [ ] Unlock protected settings
       Protection enabled

Enter number of tweak to toggle (0 to finish): 2
Error: Senser adjust control error 129
```

App TimeLapse can't install
![image](https://user-images.githubusercontent.com/29778875/166127424-571db4dd-5924-4247-9789-385918c5533f.png)

**Comment by ma1co** [comment]
Thank you for the dump!

This is weird... Do you also get the error when protection (tweak 5) is enabled?

And apps are not supported on this camera, this won't change through the tweaks. There is simply no Android subsystem.

**Comment by gerescm** [comment]
> @ma1co Thanks
> 
> Already upload dump of my rx100m5a before changes.
> 
> All tweaks apply, but one is not apply
> 
> ```
> Enter number of tweak to toggle (0 to finish): 1
> Success
> 
> 1: [X] Disable video recording limit
>        13h 01m 00s
> 
> 2: [ ] Unlock all languages
>        13 / 35 languages activated
> 
> 3: [X] Enable PAL / NTSC selector & warning
>        Enabled
> 
> 4: [X] Enable USB app installer
>        Enabled
> 
> 5: [X ] Unlock protected settings
>        Protection enabled
> 
> Enter number of tweak to toggle (0 to finish): 2
> Error: Senser adjust control error 129
> ```
> 
> App TimeLapse can't install (other apps i'am dont try) ![image](https://user-images.githubusercontent.com/29778875/166127424-571db4dd-5924-4247-9789-385918c5533f.png)

were you able to fix this? i m in the same place
