### ISSUE TITLE
Entity not found error on OS X

### ISSUE THREAD

**Issue by grundew** [ma1co/Sony-PMCA-RE#18]
I get the following error when running pmca-console.py info

➜  Sony-PMCA-RE git:(master) ✗ python pmca-console.py info
Using libusb
Looking for Sony devices

Querying mass storage device
Traceback (most recent call last):
  File "pmca-console.py", line 60, in <module>
    main()
  File "pmca-console.py", line 42, in main
    infoCommand(config.appengineServer, args.driver)
  File "/Users/grundew/src/Sony-PMCA-RE/pmca/commands/usb.py", line 142, in infoCommand
    device = getDevice(driver)
  File "/Users/grundew/src/Sony-PMCA-RE/pmca/commands/usb.py", line 130, in getDevice
    devices = list(listDevices(driver))
  File "/Users/grundew/src/Sony-PMCA-RE/pmca/commands/usb.py", line 107, in listDevices
    info = MscDevice(drv).getDeviceInfo()
  File "/Users/grundew/src/Sony-PMCA-RE/pmca/usb/**init**.py", line 17, in **init**
    self.reset()
  File "/Users/grundew/src/Sony-PMCA-RE/pmca/usb/**init**.py", line 24, in reset
    self.driver.reset()
  File "/Users/grundew/src/Sony-PMCA-RE/pmca/usb/driver/libusb.py", line 76, in reset
    self.dev.reset()
  File "/usr/local/lib/python2.7/site-packages/usb/core.py", line 915, in reset
    self._ctx.backend.reset_device(self._ctx.handle)
  File "/usr/local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 893, in reset_device
    _check(self.lib.libusb_reset_device(dev_handle.handle))
  File "/usr/local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found
➜  Sony-PMCA-RE git:(master) ✗

**Comment by voz** [comment]
@grundew changing the following settings of the camera has fixed the errors for me:

Menu > Setup > USB Connection > MTP
Menu > Setup > USB LUN Setting > Single

**Comment by ma1co** [comment]
Should be fixed with the new native OS X driver.
