### ISSUE TITLE
i have this error plz help 

### ISSUE THREAD

**Issue by catacle** [ma1co/Sony-PMCA-RE#183]
Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Model:              ILCE-6300
Product code:       0032828230
Serial number:      03881878
Firmware version:   2.01
Lens:               Model 0x18a08019 (Firmware 1.81)

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 291, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 61, in installApp
  File "C:\projects\sony-pmca-re\pmca\marketserver\server.py", line 61, in __init__
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 6: unexpected end of data

**Comment by ma1co** [comment]
This should be fixed with 01a6df32086c4e486a9562fd42762f87c6ef0f3e.
