### ISSUE TITLE
Sony DSC-WX500 support

### ISSUE THREAD

**Issue by davidomisi** [ma1co/Sony-PMCA-RE#196]
Hi,

is it possible to add the Sony DSC-WX500 to the list of supported devices? If there is anything I can do to help, let me know.

Kr David

**Comment by ma1co** [comment]
As a first step, we have to dump the firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x51020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/5000420/0x51020000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x51020000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by davidomisi** [comment]
Thanks,

I get the following .dat file as matching result; gen3_0x51020030_0.dat

I'll await the following steps ^^

**Comment by ma1co** [comment]
Thank you, the WX500 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Update to the newest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts) of pmca-console.
* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by davidomisi** [comment]
Hey there,

think there is a type somewhere in the script; below the output. (tried
both console and gui (just in case)).

installing app;

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 275, in
installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 222, in
getDevice
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 206, in
listDevices
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 75, in __init__
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 120, in
openSession
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 164,
in sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144,
in _send
Exception: MTP SendCommand failed: 0x-7ff8febf

get device info;

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 234, in
infoCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 222, in
getDevice
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 206, in
listDevices
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 75, in __init__
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 120, in
openSession
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 164,
in sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144,
in _send
Exception: MTP SendCommand failed: 0x-7ff8febf

updatershell;

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 97, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 83, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 342, in
updaterShellCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 222, in
getDevice
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 206, in
listDevices
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 75, in __init__
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 120, in
openSession
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 164,
in sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144,
in _send
Exception: MTP SendCommand failed: 0x-7ff8febf
[6496] Failed to execute script pmca-console


Let me know if I can do anything else!

Kr David

**Comment by ma1co** [comment]
Can you try switching the camera to mass storage mode?

**Comment by davidomisi** [comment]
Tried it (also tried with libusb driver) and it didn't work sadly :/

Anything else I can try?

**Comment by ma1co** [comment]
Weird.... If it worked before, it should also work now.
Can you try closing all other software that might be accessing the camera?
What kind of error do you get in mass storage mode?

**Comment by ruzzty06** [comment]
> Weird.... If it worked before, it should also work now. Can you try closing all other software that might be accessing the camera? What kind of error do you get in mass storage mode?

Hi, is this thread still alive? I followed your instruction and was able to have the files. I uploaded them to your provided dropbox link. Hope you can come up with support for WX500.

**Comment by ma1co** [comment]
@ruzzty06 Thank you very much for the dump. The WX500 should already be supported in the OpenMemories: Tweak app and in the "Tweaks" tab the development builds of pmca-console / pmca-gui. Please let us know if you encounter any problems.

**Comment by ruzzty06** [comment]
@ma1co  Thank you so much!!! Now I have english language. such a big help.
