### ISSUE TITLE
Device timeouts

### ISSUE THREAD

**Issue by yohcop** [ma1co/Sony-PMCA-RE#20]
On the alpha 6300.
The download often starts fine, but ultimately times out

```
Using libusb
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Looking for Sony devices
Looking for Sony devices
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in app install mode

Using remote server sony-pmca.appspot.com
Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 4%
Downloading 8%
Downloading 13%
Downloading 17%
Downloading 22%
Downloading 26%
Downloading 30%
Downloading 35%
Downloading 39%
Traceback (most recent call last):
  File "pmca-console.py", line 60, in <module>
    main()
  File "pmca-console.py", line 50, in main
    installCommand(args.server, args.driver, args.apkFile, pkg, args.outFile)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/commands/usb.py", line 186, in installCommand
    installApp(device, host, apkFile, appPackage, outFile)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/commands/usb.py", line 64, in installApp
    result = installer.install(dev, server.host, server.port, xpdData, printStatus)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/installer/__init__.py", line 69, in install
    dev.sendSslData(connectionId, resp)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/sony.py", line 276, in sendSslData
    self._sendCommand('\x00\x01\x00\x01', '\x05\x03', dump16be(req) + dump32be(len(data)) + data)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/sony.py", line 255, in _sendCommand
    self._write(type1 + '\x00\x00' + type2 + dump32be(len(data) + 18) + 8*'\x00' + data)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/sony.py", line 210, in _write
    response = self.driver.sendWriteCommand(self.PTP_OC_SendProxyMessage, [], data)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/driver/libusb.py", line 172, in sendWriteCommand
    return self._readResponse()
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/driver/libusb.py", line 151, in _readResponse
    type, code, transaction, data = self._readPtp()
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/driver/libusb.py", line 138, in _readPtp
    data = self.read(self.MAX_PKG_LEN)
  File "/tmp/Sony-PMCA-RE-0.7/pmca/usb/driver/libusb.py", line 79, in read
    return self.dev.read(self.epIn, length, 2000).tostring()
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 918, in read
    self.__get_timeout(timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 769, in bulk_read
    timeout)
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 872, in __read
    _check(retval)
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

I tried adding, and increasing, the timeout to self.dev.read (actually, in the logs you can see my "2000" there, line 79 in libusb.py). But that doesn't help. It looks like the device just stops answering. Any ideas?

**Comment by gaganpreet** [comment]
I had a similar issue with my Sony 6000, the process got stuck at "Downloading 8%" every time and wouldn't move further than that, I added a short `time.sleep(0.2)` in `pmca/installer/__init__.py` right at the start of the `while True:` loop and it finished successfully.
