### ISSUE TITLE
RE: Please Help: Sony Hx300 #198 

### ISSUE THREAD

**Issue by amitpandey2194** [ma1co/Sony-PMCA-RE#204]
@ma1co I am opening this new issue as the previous one is closed and didn't know if you will monitor my comment there.

#198 after you mentioned here that it supports HX300.

I tried installing the OpenTweak Memories Tweak,
It is still giving me the same error as above. Do I need a specific version of the pmca where you updated the support. Do I need to install the firmware? I am not so clear about the next steps. I just went ahead and downloaded the build from here and tried installing but it still gives the error.

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-HX300 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
File "pmca-gui.py", line 76, in do
File "pmca\commands\usb.py", line 277, in installCommand
File "pmca\commands\usb.py", line 37, in switchToAppInstaller
File "pmca\usb\sony.py", line 306, in switchToAppInstaller
File "pmca\usb\sony.py", line 244, in sendCommand
File "pmca\usb\sony.py", line 98, in sendSonyExtCommand
File "pmca\usb_init.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

**Comment by ma1co** [comment]
Duplicate
