### ISSUE TITLE
How to install OpenMemories on HDR-CX450?

### ISSUE THREAD

**Issue by wesley9946** [ma1co/Sony-PMCA-RE#207]
Hi there,

Is there a way to run OpenMemories on the HDR-CX450?
Everytime I try to do something, it shows the following:

```
> pmca-console-v0.17-win.exe install
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 72, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
[11668] Failed to execute script pmca-console
```

I also did a guess_firmware if that helps you out:

```
> pmca-console-v0.17-win.exe guess_firmware -f 0x61010000.zip
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Getting device info
Model name: HDR-CX450

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen3_0x61010033_0.dat
```

Thanks in advance!

**Comment by ma1co** [comment]
The CX450 should already be supported in pmca-gui using the "Tweaks" tab.
