### ISSUE TITLE
Downloading to camera from Linux

### ISSUE THREAD

**Issue by phedders** [ma1co/Sony-PMCA-RE#21]
Very excited to see this project!
It's Python, it's portable, it runs on MacOS... should run on Linux too :) (and no macox or windux here)

info works:

```
prh@brix:~/sony-camera/Sony-PMCA-RE$ ./pmca-console.py info
Using libusb
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6000 is a camera in MTP mode

Model:              ILCE-6000
Product code:       0032826830
Serial number:      somethingorother
Firmware version:   3.20

```

but Downloading gives error:

```
Installing org.bostwickenator.googlephotos
Using libusb
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6000 is a camera in app install mode

Using remote server sony-pmca.appspot.com
Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 4%
Traceback (most recent call last):
  File "./pmca-console.py", line 60, in <module>
    main()
  File "./pmca-console.py", line 50, in main
    installCommand(args.server, args.driver, args.apkFile, pkg, args.outFile)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/commands/usb.py", line 186, in installCommand
    installApp(device, host, apkFile, appPackage, outFile)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/commands/usb.py", line 64, in installApp
    result = installer.install(dev, server.host, server.port, xpdData, printStatus)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/installer/__init__.py", line 69, in install
    dev.sendSslData(connectionId, resp)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/usb/sony.py", line 284, in sendSslData
    self._sendCommand('\x00\x01\x00\x01', '\x05\x03', dump16be(req) + dump32be(len(data)) + data)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/usb/sony.py", line 263, in _sendCommand
    self._write(type1 + '\x00\x00' + type2 + dump32be(len(data) + 18) + 8*'\x00' + data)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/usb/sony.py", line 217, in _write
    self._checkResponse(response)
  File "/home/prh/sony-camera/Sony-PMCA-RE/pmca/usb/__init__.py", line 58, in _checkResponse
    raise Exception('Response code not OK: 0x%x' % code)
Exception: Response code not OK: 0xa489

```

Info then says:

```
prh@brix:~/sony-camera/Sony-PMCA-RE$ ./pmca-console.py info
Using libusb
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6000 is a camera in app install mode

Using remote server sony-pmca.appspot.com
Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading result
Task completed successfully

Model:              ILCE-6000
Product code:       0032826830
Serial number:      somethingorother
Firmware version:   3.20
```

Any ideas?

**Comment by phedders** [comment]
I added a "print code" into that checkResponse routine and the codes I immediately prior to the trace are:
```
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
8193
8193
8193
42120
42121

```

I've no idea what is going on in this bit of magic though:
```
214  def _write(self, data):                                                                                                                                                                                                        
215   info = 4*'\x00' + '\x81\xb4\x00\x00' + dump32le(len(data)) + 40*'\x00' + '\x02\x41\x00\x00' + 4*'\x00'                                                                                                                        
216   response = self.driver.sendWriteCommand(self.PTP_OC_SendProxyMessageInfo, [], info)                                                                                                                                           
217   self._checkResponse(response)                                                                                                                                                                                                 
218   response = self.driver.sendWriteCommand(self.PTP_OC_SendProxyMessage, [], data)                                                                                                                                               
219   self._checkResponse(response)  
```

**Comment by ma1co** [comment]
We've encountered this already: #9. I figured out that response code 0xa489 means "device busy". It should be fixed now. Please let me know if it works.
