### ISSUE TITLE
Please support a7c

### ISSUE THREAD

**Issue by johnbhshin** [ma1co/Sony-PMCA-RE#215]
Hello,

Please support a7c. I live in Japan but I don't understand Japanese. I've just purchased a7c as I expect this app may save me.
Please help me!

Querying MTP device
Sony Corporation ILCE-7C is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006

**Comment by irn27** [comment]
me to...

**Comment by matejdrdla** [comment]
Hello,

please add me to the list of the people having the mentioned problem. I also bought Sony A7C in Japan and found that there is no English menu :(

A donation will be granted!

Any kind of support will be highly appreciated,

BR,
Matej

**Comment by anthonywang1996** [comment]
I have the same issue too please support a7c

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
