### ISSUE TITLE
Sony DSC-HX9V still not working: wrong magic

### ISSUE THREAD

**Issue by psychotik2k3** [ma1co/Sony-PMCA-RE#224]
Hi, i read the issue [152](https://github.com/ma1co/Sony-PMCA-RE/issues/152)
and here is what i get/did:

windows 10 home french
sony hx9v plugged in MTP

downloaded the following binaries (today jan 11th 2021):
pmca-console-v0.17-win.exe
pmca-gui-v0.17-win.exe

when i launch the GUI and get camera info i have this error below:
```
Querying MTP device
Sony Corporation DSC-HX9V is a camera in MTP mode

Found 11 apps
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 255, in infoCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 319, in getLensInfo
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 97, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 177, in sendWriteCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 149, in _readResponse
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144, in _send
Exception: MTP SendCommand failed: 0x-7ff8ffe1
```
it looks like the camera reset after i get the information, unplugging then replugging on the USB.
so i switched into mass storage mode and then there is no this kind of reset anymore once i get the camera info.

```
Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Model:              DSC-HX9V
Product code:       0048887150
Serial number:      01790725
Firmware version:   1.00
GPS Data:           2014-07-16 00:00:00 - 2014-08-15 00:00:00

```

on the console side:

```
pmca-console-v0.17-win.exe guess_firmware -f 0x11020000.zip
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: DSC-HX9V

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x11020062_0.dat

```
looks promising execpt the invalid version
but 
```
pmca-console-v0.17-win.exe updatershell
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Using firmware for model DSC-HX9V

Unknown device: DSC-HX9V

```

with the GUI i got the same error when trying to launch the updatershell, unkown device.

and if i try to update directly (not sure if i can without going through the updater process)

```
pmca-console-v0.17-win.exe firmware -f 0x11020000\gen2_0x11020062_0.dat
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 80, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 329, in firmwareUpdateCommand
  File "C:\projects\sony-pmca-re\pmca\firmware\__init__.py", line 21, in readDat
Exception: Wrong magic
[28608] Failed to execute script pmca-console
```

oh and by the way i retrieved the 0x11020000.zip you provided on the issue 152.

any idea what's wrong ?
do i have to have python in the path ??? if yes witch version ?

thanks

**Comment by psychotik2k3** [comment]
ok retrieveing the dev version and having pyhton  2.7 in path i was able after a kind of reboot to laucnh the twek through the UI and enabled the 13hopuirs recording.
now i have to find a dummy battery for it.
thanks
