### ISSUE TITLE
sony 6000 invalid model

### ISSUE THREAD

**Issue by gobbledyduck** [ma1co/Sony-PMCA-RE#228]
Hello after I updated the firmware to sony a6001 I forgot to update the remote control app. Then I factory reset the camera and tried to revert it back to the original name sony a6000 but I keep getting this error invalid model. Is there a way to fix this?
the error:

Querying mass storage device
Sony DSC is a camera in mass storage mode

Initializing firmware update
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 82, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 360, in updaterShellCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 373, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 527, in checkGuard
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 501, in _sendWriteCommands
Exception: Firmware update error: Invalid model
[11624] Failed to execute script pmca-console

**Comment by dennis-fan** [comment]
pmca-console updatershell -m ILCE-6000
