### ISSUE TITLE
Help - did I brick my camera?

### ISSUE THREAD

**Issue by somedudewho** [ma1co/Sony-PMCA-RE#232]
Hi,

On Windows 10, I tried to firmware update my ILCA-99M2 via this tool (1.00 > 1.01). I extracted the firmware image from the official Sony file, then used pcma-gui v0.17 with the firmware update function.

It started out fine, but then it got stuck:

`
Querying MTP device
Sony Corporation ILCA-99M2 is a camera in MTP mode

Model:              ILCA-99M2
Product code:       0032828830
Serial number:      03773043
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCA-99M2 is a camera in MTP mode

Initializing firmware update
Updating from version 1.00 to version 1.01
Switching to updater mode

Waiting for camera to switch...
Please follow the instructions on the camera screen.
Initializing firmware update
Updating from version 1.00 to version 1.01
Writing firmware
0%
5%
10%
15%
20%
25%
30%
35%
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 100, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 334, in firmwareUpdateCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 399, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 411, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 542, in writeFirmware
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 492, in _sendWriteCommands
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 471, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 66, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\msc.py", line 223, in sendWriteCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\msc.py", line 206, in _sendScsiCommand
pywintypes.error: (31, 'DeviceIoControl', 'A device attached to the system is not functioning.')

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in updater mode

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 244, in infoCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 251, in getCameraInfo
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
`

The camera would then not come back on the display (even after disconnecting the power and reconnecting), but the computer would still see it. Apparently, the camera was still in updater mode.

Then I read about the the updater shell and tried `shell rm /setting/updater/mode`:

`
C:\> .\pmca-console-v0.17-win.exe updatershell -m ILCA-99M2
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in updater mode

Initializing firmware update
Writing firmware
0%
100%
Starting updater shell...

Welcome to the USB debug shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>help
List of supported commands:
help                     Print this help message
info                     Print device info
tweak                    Tweak device settings
shell                    Start an interactive shell
shell <COMMAND>          Execute the specified command
push <LOCAL> <REMOTE>    Copy the specified file from the computer to the device
pull <REMOTE> [<LOCAL>]  Copy the specified file from the device to the computer
bootloader [<OUTDIR>]    Dump the boot loader
bk r <ID>                Read backup property
bk w <ID> <DATA>         Write backup property
bk s                     Sync backup data to disk
exit                     Exit
>shell ls -lR /setting
/setting:
-rwxrwxrwx    1 0        0         1038962 Jan  1 00:00 Backup.bak
-rw-r--r--    1 0        0         1038962 Jan  1  1980 Backup.bin
-rw-r--r--    1 0        0           83331 Jan  1 00:00 DmmConfig.bin
drwxr-xr-x    2 0        0           16384 Jan  1 00:00 appfw_infra
-rw-r--r--    1 0        0           51200 Jan  1 00:00 facedmy.bin
-rw-r--r--    1 0        0           57888 Jan  1  1980 facerec0.bin
drwxr-xr-x    2 0        0           16384 Jan  1  1980 gps
-rw-r--r--    1 0        0            1757 Jan  1 00:00 kemco.txt
drwxrwxrwx    2 0        0           16384 Jan  1  1980 mode
-rw-r--r--    1 0        0         2650112 Jan  1  1980 psd.bin
-rw-r--r--    1 0        0            3420 Jan  1 00:00 ulogio.bin
drwxr-xr-x    2 0        0           16384 Jan  1 00:00 updater

/setting/appfw_infra:

/setting/gps:

/setting/mode:

/setting/updater:
---x-wx-wx    1 0        0               2 Jan  1 00:01 dat4
-r--r--r--    1 0        0               0 Jan  1 00:00 mode
>shell rm /setting/updater/mode
>exit
Done
`

Since then, the camera won't come back at all :( It makes a tiny little noise if I connect power and would the focus an attached lens to infinity, but not more. It then just seems to be stuck in some kind of power cycling loop or so, making a soft mechanical noise every minute or so... 

In any case, the screen doesn't come on and must crucially, it does not get recognised by the PC anymore. Any pointers? Clinging to straws here, thanks!

**Comment by CyberUSB2** [comment]
You said you disconnected the power, but did you try taking the **battery** out? 

Sometimes pmca-console.exe updatershell will crash and my camera will become stuck and unresponsive. So I unplug from USB then take the battery out and when I put it back in, the camera reboots itself and starts functioning again.

**Comment by fknorn** [comment]
> You said you disconnected the power, but did you try taking the **battery** out?
> 
> Sometimes pmca-console.exe updatershell will crash and my camera will become stuck and unresponsive. So I unplug from USB then take the battery out and when I put it back in, the camera reboots itself and starts functioning again.

Hi - thanks for getting back on this. Of course it tried all that, all sorts of
timings with battery in/out, even DC, etc…

**Comment by somedudewho** [comment]
Hi, thanks for getting back on this. Of course I tried that, all sorts of combos and timing of battery in/out, even played around with DC ... no avail ... :(

**Comment by tomriley** [comment]
I also seem to have bricked my a7rii the same kind of way - playing around with deleting/recreating the /setting/updater/mode files to try to fix a restart loop after managing to enable languages. Did you ever fix your camera?

**Comment by somedudewho** [comment]
Nope :/
