### ISSUE TITLE
Cannot change settings - getting error 

### ISSUE THREAD

**Issue by dmitriyteteruk** [ma1co/Sony-PMCA-RE#234]
Hi! I use FDR-AX33. I successfully changed settings from PAL to NTSC and added All Languages.
All languages added 2 menu items with no letters in it. I have tried to revers Language settings to lower number of languages but with no success. Each time I am getting error.
Re-pro steps:

1. Run PMCA-GUI v0.17 (Windows 10)
2. Get camera info - OK - log below.

> Using drivers Windows-MSC, Windows-MTP
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode
> 
> Model:              FDR-AX33
> Product code:       0002441156
> Serial number:      0355XXXX
> Firmware version:   1.10

3. Start tweaking (updater mode)
> Waiting for camera to switch...
> Please follow the instructions on the camera screen.

4.  Updated mode tweaks
> Using drivers Windows-MSC, Windows-MTP
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode

> Getting device info
> Using firmware for model FDR-AX33

> Initializing firmware update
> Switching to updater mode

> Waiting for camera to switch...
> Please follow the instructions on the camera screen.
> Initializing firmware update
> Writing firmware
> 0%
> 100%
- current settings tweak window
![image](https://user-images.githubusercontent.com/34028526/115873977-40689e80-a44c-11eb-84fd-9ee76a0ca063.png)
- updated settings - trying to uncheck Language menu
![image](https://user-images.githubusercontent.com/34028526/115874234-8887c100-a44c-11eb-8234-b26afac2a819.png)
- getting error
> Traceback (most recent call last):
>   File "C:\projects\sony-pmca-re\pmca-gui.py", line 168, in do
>   File "C:\projects\sony-pmca-re\pmca\usb\usbshell\__init__.py", line 117, in setTweakEnabled
>   File "C:\projects\sony-pmca-re\pmca\usb\usbshell\__init__.py", line 71, in _req
> pmca.usb.usbshell.UsbShellException: Unknown error

At same time I can uncheck and check back box with **Unlock Protect Settings** option, but it does not help.
![image](https://user-images.githubusercontent.com/34028526/115874943-62165580-a44d-11eb-8ff2-5d3a58fd735d.png)

Can somebody clarify how to overcome this error. I have tried on different PCs and with different USB cables. .

**Comment by Serpentor** [comment]
I have this exact same set of errors with an FDR-AXP35.
