### ISSUE TITLE
DSC-WX50

### ISSUE THREAD

**Issue by mjroy2021** [ma1co/Sony-PMCA-RE#240]
Is the OpenMemories: Tweak supposed to work with the DSC-WX50.
I used: pmca-gui-v0.17-win

I get the following when I try to install OpenMemories: Tweak:

Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Model:              DSC-WX50
Product code:       0080803201
Serial number:      06133123
Firmware version:   1.01

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

Is the issue at my PC (Windows 10) or the fact that OpenMemories does not support my camera.

Thanks,

**Comment by ma1co** [comment]
The WX50 can probably be added. As a first step, we have to dump its firmware. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
* Download [0x21020000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/3199140/0x21020000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x21020000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by Dandumontp** [comment]
Hi. I have WX50 too, and it's a japanese version. I will try to change the interface to english.

I have made the command and the firmware is "Success: Found matching file: gen2_0x21020021_0.dat"

What can i do after that ?

**Comment by TGE3416** [comment]
Hey ma1co, i followed your instructions and this is what i got: 

C:\Users\PC\OneDrive\Escritorio\New folder (2)>pmca-console-v0.18-win guess_firmware -f 0x21020000.zip
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Model name: DSC-WX50

Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen2_0x21020021_0.dat

However, im stuck when it comes to the updatershell command to dump the firmware. I read in one your other discussions that it should provide a guide to switching into updater mode and then run `pull /dev/nflasha` but it does not seem to work. This is what i get: 

C:\Users\PC\OneDrive\Escritorio\New folder (2)> pmca-console-v0.18-win updatershell
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Getting device info
Using firmware for model DSC-WX50

Unknown device: DSC-WX50

Do you think you could help me out?

**Comment by TGE3416** [comment]
@ma1co

**Comment by jbac208** [comment]
Dear @ma1co ,

Checking  https://github.com/ma1co/OpenMemories-Tweak/issues/309, I'm assuming the wx50 needs to be supported in updatershell before moving on to next steps? Please advise.

Thank you

**Comment by PKM77777** [comment]
Wondering if there was an update to this issue and if WX50 is added to the updatershell? Getting the same problems as TGE3416. Thanks in advance for the help
