### ISSUE TITLE
SLT A65-V 'MTP Command Failed' when atttempting to install OpenMemories Tweak

### ISSUE THREAD

**Issue by JonaSketch** [ma1co/Sony-PMCA-RE#246]
Hello,

When I attempt to install OpenMemories Tweak with pcma-gui, I receive this message, and the camera reboots:

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation SLT-A65V is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 97, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 177, in sendWriteCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 149, in _readResponse
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144, in _send
Exception: MTP SendCommand failed: 0x-7ff8ffe1

What could be a potential fix? Could I try intalling a different installation, or do I need to install different drivers? Thanks in advance.

**Comment by ma1co** [comment]
The SLT-A65 does not support apps, but should be supported through the updater mode (use the "Tweaks" tab in pmca-gui).

**Comment by JonaSketch** [comment]
> The SLT-A65 does not support apps, but should be supported through the updater mode (use the "Tweaks" tab in pmca-gui).

OK, thank you very much! I gave an attempt at the Tweaks, and I was able to unlock all of the languages, but I was unfortunately unable to remove the 30 minute recording time limit. While I was in the app, it seemed to work, I wasn't given any errors, but when I actually tested it, the 30 minute recording limit was still there.
