### ISSUE TITLE
MTP ERROR installing apps in SONY A7III

### ISSUE THREAD

**Issue by DarCoF** [ma1co/Sony-PMCA-RE#263]
Hi @ma1co ,

Every time I try to install the tweaks apps (whether from de gui or directly through console) it's throwing the following error: 

Loading app list
Cannot connect to remote server, falling back to appstore repository
Found 11 apps
 [ 1] com.github.ma1co.pmcademo.app
 [ 2] com.github.ma1co.openmemories.tweak
 [ 3] com.github.ma1co.openmemories.appstore
 [ 4] org.bostwickenator.dofmath
 [ 5] org.bostwickenator.googlephotos
 [ 6] org.bostwickenator.ftpuploader
 [ 7] com.obsidium.focusbracket
 [ 8] com.obsidium.bettermanual
 [ 9] com.jonasjuffinger.timelapse
 [10] com.github.LubikR.synologyuploader
 [11] info.schnatterer.pmcaFilesystemServer
Enter number of app to install (0 to abort): 2

Installing com.github.ma1co.openmemories.tweak
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-7M3 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 91, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 69, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 239, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 35, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 81, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006
[6740] Failed to execute script pmca-console

There seems to be some error connecting camera and PC. Any clue with this issue? 

Thanks.

**Comment by DarCoF** [comment]
Hey @ma1co! Could you help me out here please? It would be very helpful to be able to unlock languages in my camera.
