### ISSUE TITLE
Unknown device: HDR-CX675

### ISSUE THREAD

**Issue by RinzRinz** [ma1co/Sony-PMCA-RE#265]
Dear sir, 
I am trying to get the unlock language tweak to work on my Japanese HDR-CX675.
However, it does not recognize any of the firmwares in the zip file. Also, I cannot use the tweak as it gives me:

Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 274, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 37, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 67, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 36, in _checkResponse
pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0

I would like to send my firmware to you but, not sure how to use AppVeyor (I need developer version of the console) but at artifacts there is nothing for me to download. Maybe I am just stupid and dont understand how to download it. 

Could you please help me? Thank you for your assistance. 

Kind regards, Rinz

**Comment by RinzRinz** [comment]
Does anybody know how to get the developer version so I can make the firmware dump?

**Comment by ma1co** [comment]
The artifacts are back online.
