### ISSUE TITLE
FDR-AXP33 cannot tweak PAL to NTSC

### ISSUE THREAD

**Issue by KamilSucharski** [ma1co/Sony-PMCA-RE#273]
My device is recognised as shown below and I cannot tweak PAL to NTSC..

> 
> Using drivers Windows-MSC, Windows-MTP
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode
> 
> Model:              FDR-AXP33
> Product code:       0002441214
> Serial number:      03578926
> Firmware version:   1.10

When I try to uncheck "Enable PAL / NTSC selector & warning"  in the tweak menu I get the log below.

> Traceback (most recent call last):
>   File "pmca-gui.py", line 167, in do
>   File "pmca\usb\usbshell\__init__.py", line 112, in setTweakEnabled
>   File "pmca\usb\usbshell\__init__.py", line 66, in _req
> pmca.usb.usbshell.UsbShellException: Protection enabled. Please disable protection first.

When I try to check "Unlock protected settings" in the tweak menu I get the log below.

> Traceback (most recent call last):
>   File "pmca-gui.py", line 167, in do
>   File "pmca\usb\usbshell\__init__.py", line 112, in setTweakEnabled
>   File "pmca\usb\usbshell\__init__.py", line 66, in _req
> pmca.usb.usbshell.UsbShellException: Unknown error

When I try to install the https://github.com/ma1co/OpenMemories-Tweak or https://github.com/ma1co/OpenMemories-Launcher apps in the Install apps menu I get the log below, and nothing happens on the camera (no app install mode, I can't find anything online about it).

> Using drivers Windows-MSC, Windows-MTP
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode
> 
> Switching to app install mode
> Waiting for camera to switch...
> Operation timed out. Please run this command again when your camera has connected.

**Comment by KamilSucharski** [comment]
I'm just going to tag users appearing in similar issue threads, maybe one of them encountered it along the way...

@dmitriyteteruk @RealTadango @ashmkuk @AndreMPCosta @lorient7 @ma1co @ArekKontrol @maxandfriend @marines4 @opener12327 @paparuda @AndrewRacz @kfire75 @Oleespen99 @Ramyts

**Comment by Egor-l** [comment]
I've met the same trouble with AX33. 
Previously I successfully unlocked AX53.  
The crucial step was 1- Starting with the cam in 24P mode like is written here
https://github.com/ma1co/Sony-PMCA-RE/issues/90
With AX33 this 24p mode is missing in menue

**Comment by KamilSucharski** [comment]
@Egor-l It is set to 24p mode, and I restarted in many times during troubleshooting.

**Comment by KamilSucharski** [comment]
![24modeax33p](https://user-images.githubusercontent.com/15111215/152165847-df6530b1-35a3-4f3f-ae00-a706b64bbe2b.jpg)
@Egor-l as you can see it's set to 24p Mode.

**Comment by KamilSucharski** [comment]
@Egor-l What is your firmware version? I'm using 1.10

**Comment by Egor-l** [comment]
FW is the same 1.10. Have you tried with a new release 0.18?

**Comment by KamilSucharski** [comment]
@Egor-l I downloaded and checked the newest release 0.18.
Get camera info returns
```
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Model:              FDR-AXP33
Product code:       0002441214
Serial number:      03578926
Firmware version:   1.10
```

As for the tweak mode it's even worse than it was. Now the logs are
```
Getting device info
Using firmware for model FDR-AXP33

Initializing firmware update
Switching to updater mode

Waiting for camera to switch...
Please follow the instructions on the camera screen.
Operation timed out. Please run this command again when your camera has connected.
```

The tweak menu doesn't even appear. The camera first displays "Follow instructions on the computer" and then goes into a black screen. Only by taking out the battery and putting it back in can I restore it to working order.

As for the app installation the result is the same as it was before.

**Comment by adwb1949** [comment]
Hi, apart from the ntsc to pal and back what else can be installed from the tweaks or apps lists?
Thank you
