### ISSUE TITLE
Help, and question

### ISSUE THREAD

**Issue by PrincePop25** [ma1co/Sony-PMCA-RE#289]
So when try to connect my Sony Cyber-shot DSC-HX9V in the software and I follow all the instructions and make sure the USB thing is in PTM when I try running the software it gives me this error and weird thing is my camera USB thing changes to Mass Storage?

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 255, in infoCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 319, in getLensInfo
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 97, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 177, in sendWriteCommand
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 149, in _readResponse
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144, in _send
Exception: MTP SendCommand failed: 0x-7ff8ffe1

**Comment by PrincePop25** [comment]
> So when try to connect my Sony Cyber-shot DSC-HX9V in the software and I follow all the instructions and make sure the USB thing is in PTM when I try running the software it gives me this error and weird thing is my camera USB thing changes to Mass Storage?
> 
> Traceback (most recent call last): File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 255, in infoCommand File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 319, in getLensInfo File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 97, in sendSonyExtCommand File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 177, in sendWriteCommand File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 149, in _readResponse File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 144, in _send Exception: MTP SendCommand failed: 0x-7ff8ffe1
