### ISSUE TITLE
Sony a7siii unlock language by usb pmca-gui-v0.18-6-g295cbc8-win.exe latest development build

### ISSUE THREAD

**Issue by qiuxd1996** [ma1co/Sony-PMCA-RE#298]
I try to use zadig to replace driver to libusb-win32(v1.2.6.0) and it just worked. But when i open the pmca-gui-v0.18-6-g295cbc8-win.exe and try to usb the strat tweaking(service mode) buttom.
And i get this

Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-7SM3 is a camera in MTP mode

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Traceback (most recent call last):
  File "pmca\usb\driver\generic\libusb.py", line 85, in write
  File "usb\core.py", line 986, in write
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 229, in setup_request
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 178, in managed_claim_interface
  File "usb\backend\libusb0.py", line 537, in claim_interface
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, win error: \xc7\xeb\xc7\xf3\xb5\xc4\xd7\xca\xd4\xb4\xd4\xda\xca\xb9\xd3\xc3\xd6\xd0\xa1\xa3\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pmca-gui.py", line 117, in do
  File "pmca-gui.py", line 146, in start
  File "pmca\commands\usb.py", line 351, in updaterShellCommand
  File "pmca\commands\usb.py", line 221, in getDevice
  File "pmca\commands\usb.py", line 199, in listDevices
  File "pmca\usb\__init__.py", line 80, in __init__
  File "pmca\usb\__init__.py", line 122, in openSession
  File "pmca\usb\driver\generic\__init__.py", line 239, in sendCommand
  File "pmca\usb\driver\generic\__init__.py", line 235, in _writeInitialCommand
  File "pmca\usb\driver\generic\__init__.py", line 207, in _writePtp
  File "pmca\usb\driver\generic\__init__.py", line 97, in write
  File "pmca\usb\driver\generic\libusb.py", line 87, in write
pmca.usb.driver.generic.GenericUsbException
How can i solve the problem

**Comment by ma1co** [comment]
The A7SM3 is currently not officially supported, I expect the service mode connection to fail. You might have some luck switching the camera to mass storage mode and then using service mode (not updater mode).

**Comment by qiuxd1996** [comment]
Thanks for the response. I try that mass storage,unfortunately it's not lucky enough.
I hope that pcma can work on A7SM3 in the future. Thanks!

**Comment by anderson-kesen** [comment]
Confirming this works on the Sony a7S III (ILCE-7SM3) — used `pmca-console.py serviceshell` with the `tweak` command to unlock all languages. No VM/Linux needed, ran it natively on macOS with `sudo`.

One gotcha: if you hit `Error: Cannot overwrite backup`, run `bk unlock` first, apply the tweak, then `bk lock` before exiting.

Wrote up the full step-by-step here in case it helps: https://github.com/anderson-kesen/a7siii-language-unlock
