### ISSUE TITLE
Hello, I am using A7S2 and the error is as follows：

### ISSUE THREAD

**Issue by takutasa** [ma1co/Sony-PMCA-RE#303]
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-7SM2 is a camera in app install mode

Traceback (most recent call last):
  File "pmca-console.py", line 99, in <module>
  File "pmca-console.py", line 73, in main
  File "pmca\commands\usb.py", line 300, in installCommand
  File "pmca\commands\usb.py", line 48, in installApp
  File "pmca\marketserver\server.py", line 42, in __init__
  File "socketserver.py", line 456, in __init__
  File "http\server.py", line 138, in server_bind
  File "socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 9: invalid continuation byte
[6972] Failed to execute script 'pmca-console' due to unhandled exception!
Versions are 0.18
What is the problem? Or do I need to switch to OSX or linux?

**Comment by ma1co** [comment]
This should be fixed with 01a6df32086c4e486a9562fd42762f87c6ef0f3e. Please try the [develpoment builds](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).

**Comment by takutasa** [comment]
Thank
