### ISSUE TITLE
Sony A6400 Japanese Version Language unlock (PMCA Gui 18.7 Newest)

### ISSUE THREAD

**Issue by blablabla15** [ma1co/Sony-PMCA-RE#304]
Hello, I have 1 Sony A6400 Japanese and I have following ma1co guide to unlock full language. But when I'm stick to Unlock language option, PMCA GUI 18.7 have a notification is "Exception: Senser adjust control error 129". Please tell me what I'm wrong or missing!

**Comment by ma1co** [comment]
I know that the error message is confusing, I'll try to fix that. Can you try to check "unlock protected settings" first?

**Comment by blablabla15** [comment]
> I know that the error message is confusing, I'll try to fix that. Can you try to check "unlock protected settings" first?

Yes, I try everything just language, protection and PAL/NTSC warning can't check/uncheck. Btw, when I open GUI first time, 2 option video limit and USB app already checked.

**Comment by blablabla15** [comment]
> I know that the error message is confusing, I'll try to fix that. Can you try to check "unlock protected settings" first?

PAL/NTSC warning and Protection don't have any notice like Language unlock, but I can't checked too, it will return to uncheck :D

**Comment by datNDivvy** [comment]
i got the same error

**Comment by datNDivvy** [comment]
> I know that the error message is confusing, I'll try to fix that. Can you try to check "unlock protected settings" first?

Checked and then roll back to uncheck stage

**Comment by selfsome** [comment]
Is there any solution to this? 
Got same error code on my A7R4

**Comment by rjmehra** [comment]
Hi Team,

Just to add some information, not sure if it's useful or not, but I find this happens with my A7C as well.
Trying to unlock the languages (it's in Japanese only).

Using Zadig I first changed the camera driver to libusb-win32.
Then I used the PMCA GUI to put the camera into service mode (so far so good).
Zadig then refreshed and changed the name of the camera from ILCE A7C to Sony USB Device.
I changed the driver again to libusb-win32 and hit replace driver, but it times out.
So instead I just extracted the package using that option, and installed the driver with device manager which seemed to work.
Zadig then reports that the Sony USB Device (in service mode) is now using the libusb driver.
But in PMCA GUI, it still gives the "129" error.

If there's any updates or leads please let us know.

Thanks all!

R

**Comment by tokyofamille** [comment]
Hello ma1co,

Just bought an a6400 in Japan, I have exactly same concern as [blablabla15] using development v0.18-14 version.
I can tick/untick only "disable video" and "USB app".
If I tick "unlock protected settings" has no error message but nothing happen, screen come back untick.
"Unlock all languages" give error message as soon as I tick it: "Error: Senser adjust control error 129"

I hope that you will find us a solution.

Current software is already a great piece of work, thank you for your time.

**Comment by mraulia** [comment]
hello @ma1co , same here. im using the latest version. pmca-gui-v0.18-14-gd7267
![error](https://user-images.githubusercontent.com/70988800/180681391-9636e861-2cb6-469b-bd13-16b0b7bda28e.png)

when i choose,
Tweaks - Start tweaking (updater mode) = Unknown device: ILCE-6400
Tweaks - Start tweaking (service mode) = Error: Cannot use camera in this mode.

Thanks for your attention.

**Comment by Kesshinn** [comment]
Did anyone solve any of these issues?

**Comment by mraulia** [comment]
Up Up Up...

**Comment by joundy** [comment]
Finally i successfully unlocked ENGLISH lang on my sony a6400 japan version

First, you need to activate "service mode" https://github.com/ma1co/Sony-PMCA-RE#windows-drivers, I use the development build **v18.18-18**, you can download it on https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts, make sure you can enter service shell using **pmca-console**, btw i use window 11 on my laptop.
```
C:\Users\user\Downloads>pmca-console-v0.18-18-gd634e6c-win.exe serviceshell
Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices
Found a camera in service mode

Authenticating
Starting service shell...

Welcome to platform shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>exit
Done`
```
if you face an error like this, make sure you have been replaced the driver twice,  reopen zadig software, select the sony camera and then replace the driver again with libusb-win32.
```
Waiting for camera to switch...
Found a camera in service mode
Error: Only libusb drivers are supported for service mode
```
And then the last part using **pmca-gui**, select tab tweaks -> unchek all, only check "Unlock all language" -> press "done"
```
Querying mass storage device
Sony DSC is a camera in mass storage mode

Model:              ILCE-6400
Product code:       *****
Serial number:      *****
Firmware version:   2.00
Lens:               Model 0xa0c530 (Firmware 3.01)

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to service mode

Waiting for camera to switch...
Found a camera in service mode
Authenticating
Applying tweaks...
Done
```
Thank you @ma1co for a great piece of work.

**Comment by tokyofamille** [comment]
I used convenient GUI mode, works perfectly as well with v0.18 development version, can be added in stable mode.

Thank you @ma1co

**Comment by blablabla15** [comment]
Now, it's working, thankyou very much @ma1co - form Vietnam with love <3

**Comment by JoyJulianGomes** [comment]
@ma1co Thank you so much!!! Really appreciate it!!

**Comment by aadezz** [comment]
Hello @ma1co and teams, great of work! much appreciate!
Big helps big thanks..

and @joundy , thx for update info.. god bless you all

**Comment by Creativius** [comment]
Hello @ma1co and the whole team. **You all did a very big job and I am very grateful to you for it!!!** I managed to put the Ukrainian language on the Sony Alpha 6100 camera. Also @joundy thanks for the advice to use GUI mode v0.18.18.

From Ukraine with love!

**Comment by Serpentor** [comment]
How do you get the latest version on Appveyor? I do not see anything to download.

**Comment by Minitu103** [comment]
I have the same trouble, I can't get the latest version :( really need the help from everyone!

**Comment by TehTechnoGuy** [comment]
@tokyofamille  @ma1co 

Is there any chance someone with the 0.18-18 development release can upload it to a mirror? It looks like it's no longer available on the appveyor website. I'm hoping to make my japanese a7rIV / a7r4 english in menu. 


Please and thank you!

**Comment by WynnterPixel** [comment]
hi, does anyone still have their pmca-console-v0.18-18-gd634e6 copy for windows? would really appreciate it if someone could zip it here, thanks

**Comment by joundy** [comment]
@WynnterPixel https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip do it at your own risk

**Comment by WynnterPixel** [comment]
@joundy Bro, you're a life saver.  THANK YOU!

**Comment by Serpentor** [comment]
> @WynnterPixel https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip do it at your own risk

Thank you! I was finally able to open up the language options on my AXP35 after failing to figure it out for three years. This latest release is definitely a major advancement. Unfortunately, my camera only allows me to see the first screen of available languages and reboots if I try to scroll. Oh well, I understand German better than Japanese, so it's start! Now to figure out why it reboots before getting to the page with the English option.

**Comment by Serpentor** [comment]
Thank you! I was finally able to open up the language options on my AXP35 after failing to figure it out for three years. This latest release is definitely a major advancement.

**Comment by AmateurCameraGuy** [comment]
Finally, was able to change my ILCE-6400 from japanese to english. Thank you so much @joundy! Just a question though, how do I change it back to the original driver? My PC and PlayHome Memories won't recognize my camera as normal usb. Already changed to winusb through Zadig but it won't work. Thank you all for the help as always.  

Edit: Nevermind, I have just updated the driver from the device manager to USB Mass Storage.

**Comment by WynnterPixel** [comment]
What I did was.
1. Device Manager
2. Update Drivers of ZVe10 under libusb-win32 devices
3. Browse my computer drivers
4. Let me pick from a list of available drivers on my computer
5. look for USB Mass Storage Device and use that to update your driver

**Comment by AmateurCameraGuy** [comment]
Yeah, have done these a while earlier and worked.  Have updated my previous post. But thanks @WynnterPixel for the detailed instruction, this will help others who experienced the same problem. Cheers!

**Comment by Minitu103** [comment]
> Finally, was able to change my ILCE-6400 from japanese to english. Thank you so much @joundy! Just a question though, how do I change it back to the original driver? My PC and PlayHome Memories won't recognize my camera as normal usb. Already changed to winusb through Zadig but it won't work. Thank you all for the help as always.
> 
> Edit: Nevermind, I have just updated the driver from the device manager to USB Mass Storage.

I'm using sony ILCE-6400, but I can't change language from japanese to english. I have set the camera to mtp mode and nothing happen

**Comment by agmarta** [comment]
can someone please show me the steps i just want to sell my camera and i need to change it to english first

**Comment by NandaA7iii** [comment]
> @WynnterPixel https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip do it at your own risk

Hello joundy , is it work for a7iii japanese version? I new in gifthub just for unlock japanese language to english, if you dont mind can you make video turorial or pdf photos step by step how do that , thank you!

**Comment by NandaA7iii** [comment]
> Reference in n

is it work with a7iii camera? i buy japanese version and i want it to english language , can you teach me step by step how to do it because im newbie in coding or tweaking like this, if you dont mind can you make video tutorial ?

**Comment by picklejr3** [comment]
Hi! So thanks everyone (especially joundy) for helping me with my a6400 to get english on the jap only version. I have one question though i just learned ver 2.0 for the firmware includes animal af (i have version 1.0) and i was wondering if this interferes with updating the firmware because i can’t seem to update it using the windows tool on sonys website. whenever i plug my camera in with the program running it says check connection and the app won’t recognize it. If anyone could help that would be amazing!

**Comment by fimatr93** [comment]
Hello maybe someone can help me with that issue... after installing libusb win32 i run the console for serviceshell but i receive Error: Cannot use camera in this mode. i have tried to reinstall the driver takeout from MTP mod and go back reboot the PC few revisions of the console but always the same issue. maybe because i got the new software? 2.0? lens need to be removed? or some setting in the camera? 
thank you for helping

**Comment by picklejr3** [comment]
I got it to update to 2.0 after installing the mod so I don't think its that, nor having the lens attached (on my a6400, it depends which camera ur doing it on I think). Did you use the additional program joundy mentioned? After changing the driver (you have to do it twice), I used the v18.18-18 (I didn't use the terminal version) I was able to install the tweak, and then it worked as normal

**Comment by fimatr93** [comment]
> I got it to update to 2.0 after installing the mod so I don't think its that, nor having the lens attached (on my a6400, it depends which camera ur doing it on I think). Did you use the additional program joundy mentioned? After changing the driver (you have to do it twice), I used the v18.18-18 (I didn't use the terminal version) I was able to install the tweak, and then it worked as normal

Ok, so after not sleeping all night, trying and failing,trying and failing,trying and success!!!
I have managed to do it! 
so first of all thank you very much you saved me from learning kanji😂.
Secondly all my issue was the MTP mod on the camera! I don't know if its issue only with my camera or maybe i dident read correctly. But i had to put my camera to "auto" i dont know what mode it worked on, but when i installed the libusb it gave me prompt that i am about change the system driver, just pressed ok and after that like a magic all was working as described in the manual! 
so thank you again to the creator!!! You are life saver! God bless you with all you ever wanted this year!

**Comment by keithauhk** [comment]
Hi,

I just able to have English langauge on my a6100 from Japan.
I cloned the latest code and run the console and "tweak" command on Ubuntu 18.04 with Python3. It looks all fine without any issue!
Great work!

I was able to choose English language from the menu and have it working well. However, going through every line in language menu causes camera restart. It happens when it reaches Arabian or Indonesian. Due to this reason I was not able to try changing the language to Traditional Chinese. Would there be any solution?

Thanks @ma1co!

**Comment by kehuydietngo** [comment]
> Hi,
> 
> I just able to have English langauge on my a6100 from Japan. I cloned the latest code and run the console and "tweak" command on Ubuntu 18.04 with Python3. It looks all fine without any issue! Great work!
> 
> I was able to choose English language from the menu and have it working well. However, going through every line in language menu causes camera restart. It happens when it reaches Arabian or Indonesian. Due to this reason I was not able to try changing the language to Traditional Chinese. Would there be any solution?
> 
> Thanks @ma1co!

can you help me, my telegram is @fihung, I cant change english on a6400. I will send money via paypal for thank :(((

**Comment by kehuydietngo** [comment]
> @WynnterPixel https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip do it at your own risk

pls help me, my telegram is @fihung, I'll pay for you with thanks :((

**Comment by kehuydietngo** [comment]
> Now, it's working, thankyou very much @ma1co - from Vietnam with love <3

bạn ơi, giúp mình với, zalo mình là 0389276425, mình xin cám ơn và hậu tạ ạ <3

**Comment by kira7863** [comment]
> Finally i successfully unlocked ENGLISH lang on my sony a6400 japan version
> 
> First, you need to activate "service mode" https://github.com/ma1co/Sony-PMCA-RE#windows-drivers, I use the development build **v18.18-18**
, you can download it on https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts, make sure you can enter service shell using **pmca-console**, btw i use window 11 on my laptop.
> 
> ```
> C:\Users\user\Downloads>pmca-console-v0.18-18-gd634e6c-win.exe serviceshell
> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
> Looking for Sony devices
> Found a camera in service mode
> 
> Authenticating
> Starting service shell...
> 
> Welcome to platform shell.
> Type `help` for the list of supported commands.
> Type `exit` to quit.
> >exit
> Done`
> ```
> 
> if you face an error like this, make sure you have been replaced the driver twice, reopen zadig software, select the sony camera and then replace the driver again with libusb-win32.
> 
> ```
> Waiting for camera to switch...
> Found a camera in service mode
> Error: Only libusb drivers are supported for service mode
> ```
> 
> And then the last part using **pmca-gui**, select tab tweaks -> unchek all, only check "Unlock all language" -> press "done"
> 
> ```
> Querying mass storage device
> Sony DSC is a camera in mass storage mode
> 
> Model:              ILCE-6400
> Product code:       *****
> Serial number:      *****
> Firmware version:   2.00
> Lens:               Model 0xa0c530 (Firmware 3.01)
> 
> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
> Looking for Sony devices
> 
> Querying mass storage device
> Sony DSC is a camera in mass storage mode
> 
> Switching to service mode
> 
> Waiting for camera to switch...
> Found a camera in service mode
> Authenticating
> Applying tweaks...
> Done
> ```
> 
> Thank you @ma1co for a great piece of work.


Hi from where can I download
development build **v18.18-18** the site that you mentioned deleted it

**Comment by blockstate** [comment]
Will this work for Sony a7r II as well and do I just have to change drivers?
Do I then uninstall the libusb drivers when I'm done?
I would prefer to use this method then instead of installing a program on the camera.
Will it be like a stock non-Japanese version when I'm done?

**Comment by Chong138** [comment]
Just got my new a6400 to convert from japanese to english after following this guide!! Thanks you so much for saving me from making a return!! Got it for a pretty good deal

**Comment by gunky8** [comment]
> @WynnterPixel https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip do it at your own risk

I don't know why but this zip file has a virus now and I can't download it either through Windows or Mac.
Could someone PLEASE upload a new link for ver 18.8 so I can unlock an a7iii?

**Comment by ikhsan1231** [comment]
i can't open the pcma console app, when i open it, the app just flashes and exits by itself. no one experienced it too ?

i am using pcma 0.18 18 on windows 11 home

**Comment by ikhsan1231** [comment]
i cant go in service mode because i cant open the pcma console, any solution please :(

**Comment by MasadaIV** [comment]
> i cant go in service mode because i cant open the pcma console, any solution please :(

Which Camera version? Try the gui not the console.

**Comment by evianita08** [comment]
> 

Hey!. I just finished changing my region locked Sony A6400 camera. You can try to use the pcma console and gui version 18.22 from [this](https://github.com/evianita08/pmca_v18.22). And you can follow the visual step by steps guide from [this](https://youtu.be/BJhheKXs39A) video. Hope it helps

**Comment by FAR18-droid** [comment]
> Hi,
> 
> I just able to have English langauge on my a6100 from Japan. I cloned the latest code and run the console and "tweak" command on Ubuntu 18.04 with Python3. It looks all fine without any issue! Great work!
> 
> I was able to choose English language from the menu and have it working well. However, going through every line in language menu causes camera restart. It happens when it reaches Arabian or Indonesian. Due to this reason I was not able to try changing the language to Traditional Chinese. Would there be any solution?
> 
> Thanks @ma1co!

Hi,

I just bought the a6100 from Japan, but I have no idea how to open the language lock. I try use the gui latest version v0.18 but it doesn't support the a6100. 
Would anyone mind to tell me what I have to do with it?

**Comment by lucasdanielflores** [comment]
@ma1co Thanks so much for this amazing tool. I am about to buy a Sony A7R iii with Asian languages. Will this tool allow me to change/unlock the language to English? Thanks so much in advance for your help.

**Comment by theshieriff** [comment]
Hello all,
Hello @ma1co 

does anyone knows if the newest firmware also supports changing the Japanese language on Sony A6600 model?
How about Sony A7c ?

thanks for replay. 

Best,

**Comment by dreambold** [comment]
@theshieriff It should work for both models, you can try the script on a Ubuntu system.

**Comment by chenbert1211** [comment]
> > 
> 
> Hey!. I just finished changing my region locked Sony A6400 camera. You can try to use the pcma console and gui version 18.22 from [this](https://github.com/evianita08/pmca_v18.22). And you can follow the visual step by steps guide from [this](https://youtu.be/BJhheKXs39A) video. Hope it helps

THANK YOU!!! LIFE SAVER!!!

**Comment by chocomochi** [comment]
18.22 Worked on my A6400. I would've learned japanese if it werent for these open-source peeps!

**Comment by ThapaSandesh** [comment]
> > > 
> > 
> > 
> > Hey!. I just finished changing my region locked Sony A6400 camera. You can try to use the pcma console and gui version 18.22 from [this](https://github.com/evianita08/pmca_v18.22). And you can follow the visual step by steps guide from [this](https://youtu.be/BJhheKXs39A) video. Hope it helps
> 
> THANK YOU!!! LIFE SAVER!!!

hey i just wanted to know if there gonna be some problem after doing this or your camera is just working fine??

**Comment by ThapaSandesh** [comment]
> > 
> 
> Hey!. I just finished changing my region locked Sony A6400 camera. You can try to use the pcma console and gui version 18.22 from [this](https://github.com/evianita08/pmca_v18.22). And you can follow the visual step by steps guide from [this](https://youtu.be/BJhheKXs39A) video. Hope it helps

hey i just wanted to know if there gonna be some problem after doing this or your camera is just working fine??

**Comment by Logan-87** [comment]
Hi everyone!

I just got a Japanese **FX 30** and have a Macbook Pro (Apple Silicon / M1 Pro).  Can someone please point me in the right direction?

I'd appreciate your help. Thank you!

**Comment by harrypm** [comment]
So trying this working the A7RIII with 18.22 

![image](https://github.com/ma1co/Sony-PMCA-RE/assets/56382624/7f73cb7e-b913-4927-98c8-76b0562b09e9)

Nothing.

But with 18.14 I get actual options.

![image](https://github.com/ma1co/Sony-PMCA-RE/assets/56382624/5de85312-026c-4b29-8db0-8edb2fe5f9c1)

I get the tweeks, but when I go to click them it just greys out and gives me:

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "pmca-gui.py", line 117, in do
  File "pmca-gui.py", line 152, in start
  File "pmca\commands\usb.py", line 671, in senserShellCommand
  File "pmca\usb\sony.py", line 920, in authenticate
  File "pmca\usb\sony.py", line 913, in _sendAuthPacket
  File "pmca\usb\driver\generic\__init__.py", line 97, in write
  File "pmca\usb\driver\generic\libusb.py", line 87, in write
pmca.usb.driver.generic.GenericUsbException`

It would be nice if @ma1co would be kind to include a full archive binary list as the current release on the repo here is out of date and missing the service options, some docs on how to use all CLI would be nice as the help page is missing info.

**Comment by BillNyetheRUSpy** [comment]
> So trying this working the A7RIII with 18.22
> 
> ![image](https://private-user-images.githubusercontent.com/56382624/341113954-7f73cb7e-b913-4927-98c8-76b0562b09e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDgzNTgsIm5iZiI6MTcxOTU0ODA1OCwicGF0aCI6Ii81NjM4MjYyNC8zNDExMTM5NTQtN2Y3M2NiN2UtYjkxMy00OTI3LTk4YzgtNzZiMDU2MmIwOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA0MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTE5MzU5YWFlZTk0NTNjNzQ1ZjM4YWQ0M2M5ZmJjYjRkOTQwZmZjZTVkNzUzYTI1NzUzNmMyYzExMGNkMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DzhjvhExk4hGDPpwTCcnA2BimGzzx52UzDWDwVGl4OA)
> 
> Nothing.
> 
> But with 18.14 I get actual options.
> 
> ![image](https://private-user-images.githubusercontent.com/56382624/341114191-5de85312-026c-4b29-8db0-8edb2fe5f9c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDgzNTgsIm5iZiI6MTcxOTU0ODA1OCwicGF0aCI6Ii81NjM4MjYyNC8zNDExMTQxOTEtNWRlODUzMTItMDI2Yy00YjI5LThkYjAtOGVkYjJmZTVmOWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA0MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5M2MxYzZkMDRhMTVkM2Q4YWJhOWU5YjE2NDFlYzBkN2RhMzFjYWY2MDZmNDk1MzZmMzJjYTZlMjkxZmVhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yemDPFJy1htQbsftEw8TERQ2NL45eVpyh1GQXHiipng)
> 
> I get the tweeks, but when I go to click them it just greys out and gives me:
> 
> During handling of the above exception, another exception occurred:
> 
> `Traceback (most recent call last): File "pmca-gui.py", line 117, in do File "pmca-gui.py", line 152, in start File "pmca\commands\usb.py", line 671, in senserShellCommand File "pmca\usb\sony.py", line 920, in authenticate File "pmca\usb\sony.py", line 913, in _sendAuthPacket File "pmca\usb\driver\generic\__init__.py", line 97, in write File "pmca\usb\driver\generic\libusb.py", line 87, in write pmca.usb.driver.generic.GenericUsbException`
> 
> It would be nice if @ma1co would be kind to include a full archive binary list as the current release on the repo here is out of date and missing the service options, some docs on how to use all CLI would be nice as the help page is missing info.

Having this exact issue with the A9ii. Line numbers are different but the symptoms are the same. 

I would like to try this on 0.18-18. Anyone got a mirror for it? The lack of accessible previous dev versions on the official repo is very annoying.

**Comment by VinBones** [comment]
[Uploading pmca-console-v0.18-14-gd7267ea-win.zip…]()

**Comment by VinBones** [comment]
> > So trying this working the A7RIII with 18.22
> > ![image](https://private-user-images.githubusercontent.com/56382624/341113954-7f73cb7e-b913-4927-98c8-76b0562b09e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDgzNTgsIm5iZiI6MTcxOTU0ODA1OCwicGF0aCI6Ii81NjM4MjYyNC8zNDExMTM5NTQtN2Y3M2NiN2UtYjkxMy00OTI3LTk4YzgtNzZiMDU2MmIwOWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA0MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTE5MzU5YWFlZTk0NTNjNzQ1ZjM4YWQ0M2M5ZmJjYjRkOTQwZmZjZTVkNzUzYTI1NzUzNmMyYzExMGNkMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DzhjvhExk4hGDPpwTCcnA2BimGzzx52UzDWDwVGl4OA)
> > Nothing.
> > But with 18.14 I get actual options.
> > ![image](https://private-user-images.githubusercontent.com/56382624/341114191-5de85312-026c-4b29-8db0-8edb2fe5f9c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDgzNTgsIm5iZiI6MTcxOTU0ODA1OCwicGF0aCI6Ii81NjM4MjYyNC8zNDExMTQxOTEtNWRlODUzMTItMDI2Yy00YjI5LThkYjAtOGVkYjJmZTVmOWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDA0MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5M2MxYzZkMDRhMTVkM2Q4YWJhOWU5YjE2NDFlYzBkN2RhMzFjYWY2MDZmNDk1MzZmMzJjYTZlMjkxZmVhNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yemDPFJy1htQbsftEw8TERQ2NL45eVpyh1GQXHiipng)
> > I get the tweeks, but when I go to click them it just greys out and gives me:
> > During handling of the above exception, another exception occurred:
> > `Traceback (most recent call last): File "pmca-gui.py", line 117, in do File "pmca-gui.py", line 152, in start File "pmca\commands\usb.py", line 671, in senserShellCommand File "pmca\usb\sony.py", line 920, in authenticate File "pmca\usb\sony.py", line 913, in _sendAuthPacket File "pmca\usb\driver\generic\__init__.py", line 97, in write File "pmca\usb\driver\generic\libusb.py", line 87, in write pmca.usb.driver.generic.GenericUsbException`
> > It would be nice if @ma1co would be kind to include a full archive binary list as the current release on the repo here is out of date and missing the service options, some docs on how to use all CLI would be nice as the help page is missing info.
> 
> Having this exact issue with the A9ii. Line numbers are different but the symptoms are the same.
> 
> I would like to try this on 0.18-18. Anyone got a mirror for it? The lack of accessible previous dev versions on the official repo is very annoying.

[pmca-gui-v0.18-18-gd634e6c-win.zip](https://github.com/user-attachments/files/16051775/pmca-gui-v0.18-18-gd634e6c-win.zip)

**Comment by Vhappy86** [comment]
> o update to 2.0 after installing the mod so I don't think its that

Hi,
I'm wondering the same, I changed language but  camera always restart if I go to menu language and scroll to see all option.
Some user report during firmware update camera reset and it keeps on restarting.
Could you please help how you upgraded firmware.

Thanks for your help

**Comment by NarZhang** [comment]
I tried to switch to the Chinese language menu after unlocking, but whenever the option is close to Chinese, the A6400 will crash and restart. Can anyHERO save me? T-T

**Comment by dreambold** [comment]
@NarZhang Chinese language will not work, it seems there is an issue with the fonts missing for Chinese.

**Comment by NarZhang** [comment]
> @NarZhang中文无法使用，似乎是由于缺少中文字体造成的。
So pity.Some camera guys in China seem to have solved this problem, but I can't find any sharing on the Internet. I hope some gooooood bro can invite the way hhhhh

**Comment by NarZhang** [comment]
> @NarZhang中文无法使用，似乎是由于缺少中文字体造成的。

So pity.Some camera guys in China seem to have solved this problem, but I can't find any sharing on the Internet. I hope some gooooood bro can invent the way hhhhh

**Comment by rChristian0618** [comment]
![462647990_1491068564931427_7899879410402371892_n](https://github.com/user-attachments/assets/c49d4307-e281-4f63-a06d-70c64b6eb614)


I followed everything about zadig and libusb and my end point is this. It says NO TWEAKS AVAILABLE. My camera is Sony A6400 Chinese Version. Is there ant other way to unlock this?

**Comment by massay06** [comment]
hello @ma1co 
I always fail to install languages ​​on my A6400 camera
after installing libusb-win32 and it was successful when I checked in device manager it was installed
but when entering the PMCA GUI stage it always fails, it says "cannot continue because libusb-win32 is not installed"
Is there anything wrong/missing in the steps?

**Comment by massay06** [comment]
> Halo mungkin seseorang dapat membantu saya dengan masalah itu... setelah menginstal libusb win32 saya menjalankan konsol untuk serviceshell tetapi saya menerima Error: Tidak dapat menggunakan kamera dalam mode ini. Saya telah mencoba menginstal ulang driver yang diambil dari mod MTP dan kembali menyalakan ulang PC beberapa revisi konsol tetapi selalu mengalami masalah yang sama. Mungkin karena saya mendapatkan perangkat lunak baru? 2.0? Lensa perlu dilepas? Atau beberapa pengaturan di kamera? Terima kasih telah membantu

i experienced the same problem
have you found the solution?
after installing libusb-win32 after that it always failed
