### ISSUE TITLE
RX100 M3 upload

### ISSUE THREAD

**Issue by Resense** [ma1co/Sony-PMCA-RE#32]
Log
Loading plugin
Starting task
Got task key
Cancelling plugin
Plugin cancelled
Starting download to camera
Progress Uploading 0%
Device error : SSL

**Comment by Resense** [comment]
When I use pmca-gui v0.10 to install some apk 


Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M3 is a camera in app install mode

Using remote server sony-pmca.appspot.com
Uploading apk
Traceback (most recent call last):
  File "<string>", line 77, in do
  File "pmca\commands\usb.py", line 224, in installCommand
  File "pmca\commands\usb.py", line 59, in installApp
  File "pmca\marketserver\server.py", line 132, in setApk
  File "pmca\util\http.py", line 28, in postFile
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)

**Comment by Resense** [comment]
I know，the path and name of apk cant be Chinese，thanks for help

**Comment by Deph0** [comment]
Please close if you figured it out.
