### ISSUE TITLE
v0.18 GUI not working on my Mac

### ISSUE THREAD

**Issue by alpha1717** [ma1co/Sony-PMCA-RE#327]
Hi, opening the v0.18 gui for mac results in a black screen window. v0.17 starts correctly with the user interface. Please fix, thank you.

**Comment by napHuLLIa** [comment]
Yes, I have same problem

**Comment by shabzvisuals** [comment]
anybody found a solution to this yet?

**Comment by aikinai** [comment]
I think this is because of some problem with the default system version of tcl-tk on Macs, maybe on Apple Silicon only? I was able to get the GUI working by installing up-to-date versions of all dependencies and running `pmca-gui.py` directly.

I did a number of other things before this, so I can't guarantee this covers everything, but try this:

- Install [Homebrew](https://brew.sh)
- Install the latest Python
  `brew install python`
- Install the latest tcl-tk for Python (tkinter)
  `brew install python-tk`
- Clone the repo directly
  `git clone https://github.com/ma1co/Sony-PMCA-RE.git`
- Install dependencies
  `cd Sony-PMCA-RE/`  
  `pip install -r requirements.txt`
- Run the GUI directly
  `sudo ./pmca-gui.py`

<img width="562" alt="Screenshot 2023-01-10 at 15 49 34" src="https://user-images.githubusercontent.com/916221/211481058-ab169c07-70bb-4f50-a0db-709e701a2d60.png">

**Comment by zanegolas** [comment]
I have multiple environments so I had to specify pip3 and python3 for the above commands. I also needed to run `brew install libusb`

**Comment by shunsukefuruyama** [comment]
Following @aikinai and @zanegolas, I got the GUI to work on my M1. However, when running "Get camera info", I get `usb.core.NoBackendError: No backend available`

**Comment by zanegolas** [comment]
@shunsukefuruyama can you run `brew install libusb` again and copy the output here?

**Comment by PontusMadsen** [comment]
I was able to run the ./pmca-gui.py .. but when I tried to load the camera, I got the ["no backend"](https://github.com/ma1co/Sony-PMCA-RE/issues/401#issue-1691117228) error.
After following @aikinai 's walkthrough, and installing libusb, I now can't run the gui anymore, and get the following error:

`Traceback (most recent call last):
  File "/Sony-PMCA-RE-master/./pmca-gui.py", line 8, in <module>
    from pmca.commands.usb import *
  File "/Sony-PMCA-RE-master/pmca/commands/usb.py", line 11, in <module>
    from ..apk import *
  File "/Sony-PMCA-RE-master/pmca/apk/__init__.py", line 1, in <module>
    from axmlparserpy.axmlprinter import AXMLPrinter
ModuleNotFoundError: No module named 'axmlparserpy'`

**Comment by saralemus7** [comment]
> I was able to run the ./pmca-gui.py .. but when I tried to load the camera, I got the ["no backend"](https://github.com/ma1co/Sony-PMCA-RE/issues/401#issue-1691117228) error. After following @aikinai 's walkthrough, and installing libusb, I now can't run the gui anymore, and get the following error:
> 
> `Traceback (most recent call last): File "/Sony-PMCA-RE-master/./pmca-gui.py", line 8, in <module> from pmca.commands.usb import * File "/Sony-PMCA-RE-master/pmca/commands/usb.py", line 11, in <module> from ..apk import * File "/Sony-PMCA-RE-master/pmca/apk/__init__.py", line 1, in <module> from axmlparserpy.axmlprinter import AXMLPrinter ModuleNotFoundError: No module named 'axmlparserpy'`

Having the same error. Did you ever figure it out?

**Comment by Seele-Q** [comment]
> > I was able to run the ./pmca-gui.py .. but when I tried to load the camera, I got the ["no backend"](https://github.com/ma1co/Sony-PMCA-RE/issues/401#issue-1691117228) error. After following @aikinai 's walkthrough, and installing libusb, I now can't run the gui anymore, and get the following error:
> > `Traceback (most recent call last): File "/Sony-PMCA-RE-master/./pmca-gui.py", line 8, in <module> from pmca.commands.usb import * File "/Sony-PMCA-RE-master/pmca/commands/usb.py", line 11, in <module> from ..apk import * File "/Sony-PMCA-RE-master/pmca/apk/__init__.py", line 1, in <module> from axmlparserpy.axmlprinter import AXMLPrinter ModuleNotFoundError: No module named 'axmlparserpy'`
> 
> Having the same error. Did you ever figure it out?

Check /opt/homebrew/lib/, there is 3 folders python3.10,python3.11 and python3.12, the modules is install to pythhon3.11, but look like the PMCA is use python3.12, so copy all module from python3.11 to python3.12.
than run sudo ./pmca-gui.py, to check if any other error.

<img width="184" alt="image" src="https://github.com/ma1co/Sony-PMCA-RE/assets/164854418/f8372341-e416-40ff-a6a1-6bbd9dd3bec2">

**Comment by gothzeu** [comment]
Found a way out ! (on MacBook Air M1)

1. Download v0.17 GUI for MacOS
2. Launch it
3. If you get an error while installing an app, go to "Activity Monitor" and kill every tasks with "Photos","Drive"..

**Comment by Logan-87** [comment]
> Found a way out ! (on MacBook Air M1)
> 
> 1. Download v0.17 GUI for MacOS
> 2. Launch it
> 3. If you get an error while installing an app, go to "Activity Monitor" and kill every tasks with "Photos","Drive"..

---

Were you able to unlock the English Language? What Camera are you using?

**Comment by gothzeu** [comment]
I've got the O.G a7s, and I did it to tweak the 30mn video limit and successfully added the Timelapse app !

**Comment by SialoKhan** [comment]
That's awesome!!! Do you think it'd work on Mac OS 14.5 developer beta?

**Comment by Logan-87** [comment]
> I've got the O.G a7s, and I did it to tweak the 30mn video limit and successfully added the Timelapse app !

........ 


That's awesome! Thank you!

Did you download the Camera Drivers for Mac?

it says that Sony Camera drivers need to be installed but when I click on the driver link, it only shows for Mac OS 10/11 and nothing for newer (Mac OS 14).

**Comment by gothzeu** [comment]
For the 0.17: 
- https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.17

And for the Sony drivers 
- Create a Sony account and follow the steps on the "playmemories" website

https://www.playmemoriescameraapps.com/portal/fts/step1.php

- Normally, it will ask you to install a web extension that you'll need to approve in the System Preferences on your Mac (I needed to re-start my Mac and access to the Disk Utility Manager to reduce the security for other developers softwares)

And after all of this, you'll be good to go !

**Comment by gothzeu** [comment]
This is a video showing the process I was talking above, on MacOS Ventura it worked for me 😊

https://m.youtube.com/watch?v=VoDVSnpnreY&pp=ygUgVXBkYXRlIHNvbnkgY2FtZXJhIG1hY29zIHZlbnR1cmE%3D

**Comment by Logan-87** [comment]
> For the 0.17:
> 
> * https://github.com/ma1co/Sony-PMCA-RE/releases/tag/v0.17
> 
> And for the Sony drivers
> 
> * Create a Sony account and follow the steps on the "playmemories" website
> 
> https://www.playmemoriescameraapps.com/portal/fts/step1.php
> 
> * Normally, it will ask you to install a web extension that you'll need to approve in the System Preferences on your Mac (I needed to re-start my Mac and access to the Disk Utility Manager to reduce the security for other developers softwares)
> 
> And after all of this, you'll be good to go !

............ 



Man, this is incredibly helpful! Can't thank you enough! 

I'm trying to unlock the English on my FX 30 (Japan) on my MacBook Pro M1 Pro (14.5 developer beta) and I couldn't find much information about MacBook method.


I already have a Sony account and I'll check out the Play Memories website.

**Comment by gothzeu** [comment]
Hope you will make it work on your FX30 !

**Comment by Logan-87** [comment]
> This is a video showing the process I was talking above, on MacOS Ventura it worked for me 😊
> 
> https://m.youtube.com/watch?v=VoDVSnpnreY&pp=ygUgVXBkYXRlIHNvbnkgY2FtZXJhIG1hY29zIHZlbnR1cmE%3D



_____________________________________

I created an account on PlayMemories website and installed the web extension and enabled it in the settings. Now I can't move past this:
<img width="1242" alt="Screenshot 2024-03-31 at 15 03 40" src="https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/309e4ad1-cab2-466a-949a-d0d7b9fd4b6a">

**Comment by Logan-87** [comment]
Also I ran this from the comments above:


Install [Homebrew](https://brew.sh/)
Install the latest Python
brew install python
Install the latest tcl-tk for Python (tkinter)
brew install python-tk
Clone the repo directly
git clone https://github.com/ma1co/Sony-PMCA-RE.git
Install dependencies
cd Sony-PMCA-RE/
pip install -r requirements.txt
Run the GUI directly
sudo ./pmca-gui.py



Everything worked except the "dependencies." It says "command not found"

**Comment by gothzeu** [comment]
OK so now you need to make sure that you've put the right setting on the camera to connect it on your Mac
![tempImage97jpLU](https://github.com/ma1co/Sony-PMCA-RE/assets/134288652/c0da8f21-12a3-4230-88cf-b3858d303202)

**Comment by gothzeu** [comment]
And for : **Install dependencies**
- cd Sony-PMCA-RE/
- pip install -r requirements.txt

I didn't have "pip" also, so I tried with "pip3" and it worked

**Comment by Logan-87** [comment]
Yeah it's already in USB Mass Storage.


I think I didn't "Reduce the security" at the startups. Doing it now!!

**Comment by Logan-87** [comment]
What was the exact command you used for Pip3?

**Comment by gothzeu** [comment]
Yeah, don't forget to do like the video above where you need to shut down etc..

And for the command, I just moved into my "Sony-PMCA-RE" folder, then :
`pip3 install -r requirements.txt `

**Comment by Logan-87** [comment]
I'm getting an error while trying to install Pip3

:

"error: externally-managed-environment"

**Comment by Logan-87** [comment]
Okay, I tried:

"brew install Pip3  install  -r requirements.txt"


Got:

" Warning -  No available formula with the name "Pip3".  Did you mean
"pipx?"

To install pipx, run:  brew install pipx

**Comment by Logan-87** [comment]
Also it says on Play Memories website:

"Click Allow button for the system software for "Sony Imaging Products & Solutions Inc." In the " Security & Privacy " window." 


I don't see that anywhere in my " Privacy & Security" 


So now I don't have 2 things:

1. Pip install is failing 

2. "Allow Button for Sony Imaging Products & Solutions Inc."

**Comment by gothzeu** [comment]
Honestly, I don't remember if I went through all the process with the "pip3" install ..

- One thing I'm sure is that there's no "System Preferences" anymore, it's called "System Settings" and it has changed a bit of things.

So, then after downloading this :
<img width="905" alt="Capture d’écran 2024-03-31 à 23 27 52" src="https://github.com/ma1co/Sony-PMCA-RE/assets/134288652/cc47c75d-c470-496a-bdd6-1c34ad641616">

It will ask you to allow Sony and normally you'll be able to activate that option in the "Privacy & Security" section, near "Allow applications downloaded from.."

- Only if you did followed the "Reduced Security" step at 4:06 on the YouTube video :
<img width="907" alt="Capture d’écran 2024-03-31 à 23 43 36" src="https://github.com/ma1co/Sony-PMCA-RE/assets/134288652/a4482224-677a-4b37-ac99-7108013bb9b1">

**And don't hesitate to check the 2 boxes, just in case !**

**Comment by Logan-87** [comment]
Yes, I have already Reduced Security by following the exact process from the video.

I don't see a "PCMADownloader.pkg" anywhere !!!

**Comment by Vivienlandon** [comment]
**I managed to run this application successfully!**
_Macbook | Apple M1 Max | 14.2.1 Sonoma | Sony Alpha 7sii_

**Before I did these steps:**

- Check if your camera is supported - link from the github script page: https://openmemories.readthedocs.io/devices.html

-  I used this guide (https://support.d-imaging.sony.co.jp/mac/security/11/en/index.html) to change the security policy on my Mac computer with Apple silicon, so I can do all the following steps. 

- I watched (https://www.youtube.com/watch?v=p7hpi084Y_s&ab_channel=ProgrammingKnowledge2) to know how to install homebrew the correct way

- Made sure I have a correct cable for the camera (needs to be a data cable, like a tether cable) and put the USB Setting to Mass storage, I also removed my SD Card, and removed the cable from the computer (later you can plug it in) 

- Installed the latest update for the playmemories camera app from this site https://www.playmemoriescameraapps.com/portal/fts/step1.php

- Downloaded and installed the latest specific driver for my camera https://support.d-imaging.sony.co.jp/mac/driver/1015/en/index.html  (I don't know if this is needed) or this link which was posted on the github main page of this script: https://support.d-imaging.sony.co.jp/mac/driver/11/ja/


**Then I went through these steps:**
**1. Install Homebrew (if not already installed):**

**2. Install Python via Homebrew:**
   - brew install python

**3. Install python-tk (Tkinter):**
   - brew install python-tk

**4. Clone the Sony-PMCA-RE GitHub repository:**
   - git clone https://github.com/ma1co/Sony-PMCA-RE.git

**5. Navigate to the cloned directory:**
   - cd Sony-PMCA-RE/

**6. Install Python dependencies:**
   - Create a virtual environment: python3 -m venv myenv
   - Activate the virtual environment: source myenv/bin/activate
   - Install requirements: pip install -r requirements.txt

**7. Handle asyncore module not found error:**
   - This was due to Python version compatibility. Install an older version of Python that includes asyncore.
   - brew install python@3.9
   - Create a new virtual environment with Python 3.9: python3.9 -m venv myenv39
   - Activate the new environment: source myenv39/bin/activate
   - Re-install requirements: pip install -r requirements.txt

**8. Solve _tkinter module not found error:**
   - Reinstall python-tk for the specific Python version: brew reinstall python-tk@3.9

**9. Resolve USB backend not found error:**
   - Install libusb via Homebrew: brew install libusb

**10. Running the script with sufficient permissions:**
    - Faced a permissions issue (Access denied (insufficient permissions)).
    - Solved by running the script with sudo and specifying the virtual environment’s Python executable: sudo myenv39/bin/python ./pmca-gui.py

**11. Successfully interacted with the camera:**
    - After addressing the permissions issue, the script was able to switch the camera to app install mode and perform the desired operation
    
    
I used chatGPT to help me through every error I encountered, I explained GPT which guide I was using (the one posted from the user aikinai in the beginning of this thread) and explained that I would not know how to do these things, so it helped me super well to go step by step and solved errors along the way. I drunk a shot once I managed to make it work, felt so proud (I don't know anything about python or code haha) 

Once you are done dont forget to change back your security settings of your macbook.

**Comment by Logan-87** [comment]
Thank you! You're a lifesaver!!!

I'm gonna try this!


One Question:

Is it mandatory to be on the latest firmware to do this?

I'm on FX 30 Firmware 3.0 and the latest is 4.0

**Comment by Vivienlandon** [comment]
I don't know but my Sony is also not on the latest firmware and it worked.
But maybe the Play Memories App needs to be up to date (I suppose) 
Which you can do via this link (https://www.playmemoriescameraapps.com/portal/) and select your cam
and do not forget to change security policy of your macbook (https://support.d-imaging.sony.co.jp/mac/security/11/en/index.html)

**Comment by Vivienlandon** [comment]
[PMCADownloader.pkg.zip](https://github.com/ma1co/Sony-PMCA-RE/files/14817808/PMCADownloader.pkg.zip)
In case that helps?

**Comment by Logan-87** [comment]
Alright I'm gonna try this right now! Thank you so much again!

**Comment by Logan-87** [comment]
> I don't know but my Sony is also not on the latest firmware and it worked. But maybe the Play Memories App needs to be up to date (I suppose) Which you can do via this link (https://www.playmemoriescameraapps.com/portal/) and select your cam and do not forget to change security policy of your macbook (https://support.d-imaging.sony.co.jp/mac/security/11/en/index.html)

______________


Just one Question about Sony Camera Drivers:

The Sony page says that those drivers are for MacOS 10.13 - 10.15 and it doesn't specify any camera models either. Should I still install it?  or try without these drivers?

Here's what I've done so far;

1. Security Policy  ---> Changed

2. Homebrew Correct Installation  ----> Done

3. Python Installation Via Homebrew  ----> Done

4. Install python-tk  ----->  Done

5. Clone Sony-PMCA-RE GitHub Repo  ---> Done

6. Python Dependencies   --->  Done

7. Errors  ----> None so far

**Comment by Vivienlandon** [comment]
I think it makes sense to install them. I think they are relevant for the usb connection once you run the software (the gui to download the app to you camera). I installed the driver to make sure.

**Comment by Logan-87** [comment]
> I think it makes sense to install them. I think they are relevant for the usb connection once you run the software (the gui to download the app to you camera). I installed the driver to make sure.

---

When you say "Installed", that means just download the zip and open it?

This is what I got;

<img width="1151" alt="Screenshot 2024-03-31 at 18 26 45" src="https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/ae5ef298-65b9-4d7b-b1e7-f6b8a0268211">

**Comment by Logan-87** [comment]
I'm still stuck on "VERIFY CONNECTION" and  it doesn't show the "[Allow button for the system software for "Sony Imaging Products & Solutions Inc." In the " Security & Privacy " window]."

The camera is in Mass Storage Mode and I can see that it's recognized by my Mac in "Image Capture"

**Comment by Logan-87** [comment]
<img width="1265" alt="Screenshot 2024-03-31 at 18 38 04" src="https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/e84f25dd-2a4b-4910-aec1-5658475843cc">

**Comment by Logan-87** [comment]
<img width="1179" alt="Screenshot 2024-03-31 at 18 40 49" src="https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/62f34665-6335-48cf-b7ba-607e279dcdea">

**Comment by Logan-87** [comment]
Also, the PMCA Downloader extension is enabled in safari.

<img width="1198" alt="Screenshot 2024-03-31 at 18 47 09" src="https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/f11a961b-5d01-4134-bcf3-6412eff63d2d">

**Comment by Logan-87** [comment]
@Vivienlandon   Can I add you on telegram or WhatsApp?  I desperately need your help lol

**Comment by Vivienlandon** [comment]
Hm ja I have no idea why this is. Did you also try the driver they posted on the initial GitHub entry here? https://support.d-imaging.sony.co.jp/mac/driver/11/ja/

I don’t know why it’s not working for you. :(

**Comment by Logan-87** [comment]
> Hm ja I have no idea why this is. Did you also try the driver they posted on the initial GitHub entry here? https://support.d-imaging.sony.co.jp/mac/driver/11/ja/
> 
> I don’t know why it’s not working for you. :(

_____________

Those drivers are for Intel Macs only. I have already installed the Apple Silicon Drivers for M1/2/3.

I think it's not related to drivers because my camera is recognized by my Mac.


Also, I tried running the GUI, it recognizes my Camera but doesn't install the app and gives a storage error.

**Comment by SialoKhan** [comment]
![IMG_20240331_200331_935](https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/5b97b7f6-8ed8-47c0-9b22-55fbfc2878d2)

**Comment by Logan-87** [comment]
![20240401_065137](https://github.com/ma1co/Sony-PMCA-RE/assets/114312121/aafdec80-23a7-4b02-bb12-16aa6880fec7)

**Comment by Logan-87** [comment]
@Vivienlandon : 
@gothzeu 


Would you guys please take a look at the error I'm getting in GUI:


"pmca.usb.Unknown.MscException: Mass Storage error: Sense 0x2 0xff 0xff" 



Also, I'm still stuck on "VERIFY CONNECTION" (on Play Memories Camera website) and it doesn't show the "[Allow button for the system software for "Sony Imaging Products & Solutions Inc." In the " Security & Privacy " window]."

The camera is in Mass Storage Mode and I can see that it's recognized by my Mac in "Image Capture"


I'm using v0.17

Here's what I've done so far;

Mac Security Policy ---> Changed (reduced)

Homebrew Correct Installation ----> Done

Python Installation Via Homebrew ----> Done

Install python-tk -----> Done

Clone Sony-PMCA-RE GitHub Repo ---> Done

Python Dependencies ---> Done

**Comment by Logan-87** [comment]
> @Vivienlandon : @gothzeu @aikinai @zanegolas
> 
> Would you guys please take a look at the error I'm getting in GUI:
> 
> "pmca.usb.Unknown.MscException: Mass Storage error: Sense 0x2 0xff 0xff"
> 
> Also, I'm still stuck on "VERIFY CONNECTION" (on Play Memories Camera website) and it doesn't show the "[Allow button for the system software for "Sony Imaging Products & Solutions Inc." In the " Security & Privacy " window]."
> 
> The camera is in Mass Storage Mode and I can see that it's recognized by my Mac in "Image Capture"
> 
> I'm using v0.17
> 
> Here's what I've done so far;
> 
> Mac Security Policy ---> Changed (reduced)
> 
> Homebrew Correct Installation ----> Done
> 
> Python Installation Via Homebrew ----> Done
> 
> Install python-tk -----> Done
> 
> Clone Sony-PMCA-RE GitHub Repo ---> Done
> 
> Python Dependencies ---> Done

-----------------------------------------------------


I think I found the issue (issues).

There are three main modes to do this:

**1. App Installer**    ---> PMCA (if your camera supports the PlayMemories Camera App)


**2. Firmware Updater**  ----> There are two ways to use this:

I.  pmca-gui: In the Tweaks tab, click Start tweaking (updater mode). You can then use the checkboxes to configure your camera's settings.

II.  pmca-console: Run pmca-console updatershell. There are commands available to dump the firmware, execute Linux commands, and to tweak settings.



**3. Service Mode**  --->

It is currently only supported in the command line application:

pmca-console: Run pmca-console serviceshell. There are commands available to dump the firmware, and to execute Linux commands.
Windows Drivers

To use service mode on Windows, custom drivers have to be installed using [Zadig](http://zadig.akeo.ie/):

Make sure the camera is connected in mass storage mode.

In Zadig, check Options -> List All Devices, select the camera, select libusb-win32 and click Replace Driver.

Run pmca-console serviceshell to make the camera switch modes.

Once the camera has switched, repeat the above step to install a driver for service mode.

You should now be able to use pmca-console serviceshell.

To be able to use the camera normally again, the libusb drivers have to be uninstalled in the device manager.


**MY ISSUES:**

1. I have an FX30 and it DOES NOT SUPPORT the PlayMemories Camera App (PMCA).

2. FX 30 is based on CXD90057 Architecture.  Devices based on the CXD90045 and CXD90057 architectures are not compatible with the firmware, since their firmware is cryptographically signed.



Now my only option is to use service mode on a windows PC or linux.

**Comment by Logan-87** [comment]
@Vivienlandon 
@gothzeu 

I did it !!! Check Out --> https://github.com/ma1co/Sony-PMCA-RE/issues/504

Using a Linux VM on my MacBook Pro M1 Pro. Just wanted to say thank you for your help.

---

https://github.com/ma1co/Sony-PMCA-RE/issues/504

**Comment by nivlaoet** [comment]
Hi, Macbook M1 user here. I tried the GUI and got this error about "Cannot connect to remote server, falling back to appstore repository" and subsequently I connected the camera (FX3), tried to get Camera info, and I got this 
Traceback (most recent call last):
File "/Users/travis/build/malco/Sony-PMCA-RE/pmca-gui.py", line 57, in do
File "/Users/travis/build/malco/Sony-PMCA-RE/pmca/commands/usb-py", line 231, in infoCommand
etc etc. Anybody know how I can change it from "travis..." to my own path?
![Screenshot 2024-06-11 at 10 41 50 AM](https://github.com/ma1co/Sony-PMCA-RE/assets/172408241/68b0ddac-d077-43d7-989f-6624bd11f200)
![Screenshot 2024-06-11 at 10 41 50 AM](https://github.com/ma1co/Sony-PMCA-RE/assets/172408241/68b0ddac-d077-43d7-989f-6624bd11f200)

**Comment by crdiaz324** [comment]
> **I managed to run this application successfully!** _Macbook | Apple M1 Max | 14.2.1 Sonoma | Sony Alpha 7sii_
> 
> **Before I did these steps:**
> 
>     * Check if your camera is supported - link from the github script page: https://openmemories.readthedocs.io/devices.html
> 
>     * I used this guide (https://support.d-imaging.sony.co.jp/mac/security/11/en/index.html) to change the security policy on my Mac computer with Apple silicon, so I can do all the following steps.
> 
>     * I watched (https://www.youtube.com/watch?v=p7hpi084Y_s&ab_channel=ProgrammingKnowledge2) to know how to install homebrew the correct way
> 
>     * Made sure I have a correct cable for the camera (needs to be a data cable, like a tether cable) and put the USB Setting to Mass storage, I also removed my SD Card, and removed the cable from the computer (later you can plug it in)
> 
>     * Installed the latest update for the playmemories camera app from this site https://www.playmemoriescameraapps.com/portal/fts/step1.php
> 
>     * Downloaded and installed the latest specific driver for my camera https://support.d-imaging.sony.co.jp/mac/driver/1015/en/index.html  (I don't know if this is needed) or this link which was posted on the github main page of this script: https://support.d-imaging.sony.co.jp/mac/driver/11/ja/
> 
> 
> **Then I went through these steps:** **1. Install Homebrew (if not already installed):**
> 
> **2. Install Python via Homebrew:**
> 
>     * brew install python
> 
> 
> **3. Install python-tk (Tkinter):**
> 
>     * brew install python-tk
> 
> 
> **4. Clone the Sony-PMCA-RE GitHub repository:**
> 
>     * git clone https://github.com/ma1co/Sony-PMCA-RE.git
> 
> 
> **5. Navigate to the cloned directory:**
> 
>     * cd Sony-PMCA-RE/
> 
> 
> **6. Install Python dependencies:**
> 
>     * Create a virtual environment: python3 -m venv myenv
> 
>     * Activate the virtual environment: source myenv/bin/activate
> 
>     * Install requirements: pip install -r requirements.txt
> 
> 
> **7. Handle asyncore module not found error:**
> 
>     * This was due to Python version compatibility. Install an older version of Python that includes asyncore.
> 
>     * brew install python@3.9
> 
>     * Create a new virtual environment with Python 3.9: python3.9 -m venv myenv39
> 
>     * Activate the new environment: source myenv39/bin/activate
> 
>     * Re-install requirements: pip install -r requirements.txt
> 
> 
> **8. Solve _tkinter module not found error:**
> 
>     * Reinstall python-tk for the specific Python version: brew reinstall python-tk@3.9
> 
> 
> **9. Resolve USB backend not found error:**
> 
>     * Install libusb via Homebrew: brew install libusb
> 
> 
> **10. Running the script with sufficient permissions:** - Faced a permissions issue (Access denied (insufficient permissions)). - Solved by running the script with sudo and specifying the virtual environment’s Python executable: sudo myenv39/bin/python ./pmca-gui.py
> 
> **11. Successfully interacted with the camera:** - After addressing the permissions issue, the script was able to switch the camera to app install mode and perform the desired operation
> 
> I used chatGPT to help me through every error I encountered, I explained GPT which guide I was using (the one posted from the user aikinai in the beginning of this thread) and explained that I would not know how to do these things, so it helped me super well to go step by step and solved errors along the way. I drunk a shot once I managed to make it work, felt so proud (I don't know anything about python or code haha)
> 
> Once you are done dont forget to change back your security settings of your macbook.

Just wanted to chime in and say that these instructions worked like a charm for me.  I am on a macbook pro m2 and just bought a Japanese Sony A6700.  It only had Japanese menues so it was pretty hard for me to understand.  After following these directions, I was able to switch the language to English and now everything appears to be working normally.  

Thanks to everyone who contributed to this!

**Comment by SubinPark** [comment]
> > > I was able to run the ./pmca-gui.py .. but when I tried to load the camera, I got the ["no backend"](https://github.com/ma1co/Sony-PMCA-RE/issues/401#issue-1691117228) error. After following @aikinai 's walkthrough, and installing libusb, I now can't run the gui anymore, and get the following error:
> > > `Traceback (most recent call last): File "/Sony-PMCA-RE-master/./pmca-gui.py", line 8, in <module> from pmca.commands.usb import * File "/Sony-PMCA-RE-master/pmca/commands/usb.py", line 11, in <module> from ..apk import * File "/Sony-PMCA-RE-master/pmca/apk/__init__.py", line 1, in <module> from axmlparserpy.axmlprinter import AXMLPrinter ModuleNotFoundError: No module named 'axmlparserpy'`
> > 
> > 
> > Having the same error. Did you ever figure it out?
> 
> Check /opt/homebrew/lib/, there is 3 folders python3.10,python3.11 and python3.12, the modules is install to pythhon3.11, but look like the PMCA is use python3.12, so copy all module from python3.11 to python3.12. than run sudo ./pmca-gui.py, to check if any other error.
> 
> <img alt="image" width="184" src="https://private-user-images.githubusercontent.com/164854418/316426089-f8372341-e416-40ff-a6a1-6bbd9dd3bec2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjA0MjQsIm5iZiI6MTcyMjIyMDEyNCwicGF0aCI6Ii8xNjQ4NTQ0MTgvMzE2NDI2MDg5LWY4MzcyMzQxLWU0MTYtNDBmZi1hNmExLTZiYmQ5ZGQzYmVjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQwMjI4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTUyNmM4NGJjZjFjNDYzZDFjODAwMzlhMzZmNzFlNmYzNjU4OTM5MTQ5N2I3YWUyMDg2OWNiOTE3MTYyMzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TXP1o4TWgkkcDjEMzXCwPM-qKElGRMNFZG82_ralMuA">

I also had the same error ModuleNotFoundError. When running `pip install -r requirements.txt`, check which python version those modules are installed in. I got `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages`. But I had 2 python versions and all modules were installed in the old version (in this case 3.7).

I copied the `site-packages` folder from the one that had all the modules(3.7) and replaced it with `site-packages` folder of the newer python version and I was able to run the v0.18 GUI and unlock the languages. I was running it on intel-based macbook. Running v0.17 didn't work for me as it didn't show service mode.

**Comment by MoridinBG** [comment]
Just enabled languages successfully with Tahoe 26.3 and ILCE-6700 (A6700).
I am using pyenv, so just changed the local version to 3.13. I first tried with 3.9, but that does not like Mac OS 26 and can't read the version correctly
`pyenv install 3.13.1`
`pyenv local 3.13.1`
`pip3 install -r requirements.txt`
`brew install python-tk@3.13` <- this pulled python 3.13 from brew too
`brew install libusb`

I connected the camera in MSC mode, ran `sudo ./pmca-gui.py`, enabled service mode and enabled the languages.
After that I removed the packages I no longer need from brew
`brew remove python-tk@3.13` <- this autoremoved the brew python 3.13
`brew remove libusb`

The camera was still on 1.03 when I did that, I then updated it to 2.00 and the English was still there.
