### ISSUE TITLE
Error: Network connection

### ISSUE THREAD

**Issue by Roadchen** [ma1co/Sony-PMCA-RE#33]
**LOG :**
Starting task

Got task key

Cancelling plugin

Plugin cancelled

Starting download to camera

Progress: Uploading 0%

Error: Network connection

**Comment by NetrunnerAT** [comment]
uhm ... Sony have change usb upload?

```
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Looking for Sony devices
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in app install mode

Using remote server sony-pmca.appspot.com
Starting task
Starting communication
Traceback (most recent call last):
  File "<string>", line 67, in <module>
  File "<string>", line 53, in main
  File "pmca\commands\usb.py", line 224, in installCommand
  File "pmca\commands\usb.py", line 70, in installApp
  File "pmca\installer\__init__.py", line 56, in install
Exception: Response error Result(code=300, message='URL is invalid')
pmca-console returned -1
```

Bad News! Tested with A6300 FW2.00 from 8.6. and old FW work!

**Comment by ma1co** [comment]
@NetrunnerAT Please try the newest builds and let me know if it works: https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts

**Comment by kaysievers** [comment]
> https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts

The gui worked fine for me on a 7sII to install an app. The currently released gui showed the same error as in the report.

**Comment by ma1co** [comment]
Thank you for your feedback, the version was released as v0.11: https://github.com/ma1co/Sony-PMCA-RE/releases

**Comment by NetrunnerAT** [comment]
Feedback ... it works :D great job! 

Tested A6300 FW2.0 and A7Rii FW4.0

**Comment by nardydaido** [comment]
thank you @ma1co this version solved for my a7ii

**Comment by clintlosee** [comment]
Tried the sony-pmca.appspot.com site on MacOs Safari and got Error: Network Connection. Switched to v0.11 of the gui and got [Errno 13] Access denied (insufficient permissions). Tried on A7Rii FW4.0. Any suggestions? I can post GUI log if needed.

**Comment by ma1co** [comment]
@clintlosee Can you please try pmca-gui v0.10 (older version). Do you get the same error?

**Comment by clintlosee** [comment]
Not sure what happened, but I tried v0.10 and got the error mentioned above with 'URL is invalid'. Tried v0.11 again just hoping and everything worked just fine. Thanks for creating something pretty cool!

**Comment by ma1co** [comment]
@clintlosee The issue should be fixed in v0.12. Can you please test and confirm?

**Comment by jsungho** [comment]
It can not be installed on a7r2 (firmware 4.0).
I installed it as pmca-gui-v0.12.(same not installed v0.11 v0.10~~)
The A6000 is installed well on the same PC.

The error log in shown below.
----------------------------------------
Loading app list
Using local server
Found 7 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
Traceback (most recent call last):
  File "<string>", line 54, in do
  File "pmca\commands\usb.py", line 176, in infoCommand
  File "pmca\commands\usb.py", line 164, in getDevice
  File "pmca\commands\usb.py", line 138, in listDevices
  File "pmca\commands\usb.py", line 103, in listDevices
  File "pmca\usb\driver\windows\msc.py", line 116, in <genexpr>
  File "pmca\usb\driver\windows\msc.py", line 171, in _listDevices
  File "pmca\usb\driver\windows\msc.py", line 171, in <genexpr>
  File "pmca\usb\driver\windows\msc.py", line 164, in _getStorageNumber
pywintypes.error: (1, 'DeviceIoControl', '')

**Comment by ma1co** [comment]
@jsungho How did you install it on the a6000, pmca-gui or browser plugin? Which Windows version are you using? Do you have any weird USB devices connected?

**Comment by jsungho** [comment]
@ma1co A6000 was installed ad browser plugin.   windows10 version in in use. There in nothing special about USB connected devices.
Problem always occurs only on A7r2 (FW 4.0)
windows7,8,10 should not all be the same.   .....   other PC are not the same!!!
Both pmca-gui and browser plugin cause an error like the above screen.

**Comment by jsungho** [comment]
@ma1co   I'll test it on another Windows 7 PC.

**Comment by ma1co** [comment]
@jsungho The browser plugin does not work with the newest firmware. You have to use pmca-gui. Can you try running pmca-gui WITHOUT connecting your camera? Do you get the same error?

**Comment by jsungho** [comment]
@ma1co    This is South-Korea, so understand the time difference.   I'll try and reply in about 12 hours.  I am eager to resolve the error.  Thanks a lot for your help.

**Comment by jsungho** [comment]
ㅠㅠ    Now tested !!!
The same error occurs even if A7r2 is not connected.
I do not understand myself either.
A6000 is fine.

Only A7r2 issues ??????????????????????????

------------------- IE Plugin logs below -----------------------
Loading plugin
Plugin loaded
Starting task
Got task key
Cancelling plugin
Plugin cancelled
Starting download to camera
Error: Network connection

------------------- pmca-gui v0.12 logs below --------------------------
Loading app list
Using local server
Found 7 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices
Traceback (most recent call last):
  File "<string>", line 54, in do
  File "pmca\commands\usb.py", line 176, in infoCommand
  File "pmca\commands\usb.py", line 164, in getDevice
  File "pmca\commands\usb.py", line 138, in listDevices
  File "pmca\commands\usb.py", line 103, in listDevices
  File "pmca\usb\driver\windows\msc.py", line 116, in <genexpr>
  File "pmca\usb\driver\windows\msc.py", line 171, in _listDevices
  File "pmca\usb\driver\windows\msc.py", line 171, in <genexpr>
  File "pmca\usb\driver\windows\msc.py", line 164, in _getStorageNumber
pywintypes.error: (1, 'DeviceIoControl', '잘못된 기능입니다.')

**Comment by ma1co** [comment]
@jsungho The issue should be fixed now. Please download the newest pmca-gui build [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).

**Comment by jsungho** [comment]
@ma1co OK!!!   Good
Thank you so much for helping to resolve th error.
Tested pmca-gui-v0.12-2.apk and A7r2(FW4.0).
It works perfectly now.
Thanks to you. I use the FocusBracket well.  ^^
The FocusBracket App also works perfectly in A7r2(FW4.0)

It feels so good to me !!!!!!!!!!!!!!!!!!

**Comment by cosershoterdays** [comment]
I am a student. Using the sony a7ii with FW4.0.when ever I switch to MTP mode or mass storage mode. in IE always error : Network connection. It's my computer problem? Windows 10 32bit PRO. version
How ever, thanks for this project. is sony change the way to install apps? or I had some things mistake in using? I hope someone can help me.THX

**Comment by ma1co** [comment]
@cosershoterdays See, above, you have to use [pmca-gui](https://github.com/ma1co/Sony-PMCA-RE/releases/latest) instead.

**Comment by drumach1ne** [comment]
Hello - I tried all the recent releases of the PMCA-GUI v10-16
Sony a7Rii firmware v.4.0

Im seeing everyone else figured it out - i keep getting the same error - 

USBError: [Errno 13] Access Denied (insufficient permissions)

Please help - Thank you

<img width="728" alt="screen shot 2017-11-30 at 7 35 12 pm" src="https://user-images.githubusercontent.com/34149429/33466873-9d96b3b2-d605-11e7-9428-360dc952a37b.png">

**Comment by mime29** [comment]
If I do : Put the camera on Mass Storage mode.
Then I get No devices found in pmca-gui v0.16
are you sure about your approach ? I have a 7M2 not 7RM2

**Comment by cassera88** [comment]
still doesnt work for me. No matter what i try i still get usb.core.USBError Erno13 Acess denied (insufficient permissions)
