### ISSUE TITLE
macOS Error Connection

### ISSUE THREAD

**Issue by 0xxd0** [ma1co/Sony-PMCA-RE#34]
Version: build v0.12 
OS:  win10, macOS Sierra

for win10, everything works well, but when it comes to macOS, the connection cannot be established

### bash log
host-213-213-213-5:Sony-PMCA-RE user$ python pmca-gui.py

Loading app list
Using local server
Found 7 apps

Using drivers OS-X-MSC, libusb-MTP
Looking for Sony devices

Querying mass storage device

Traceback (most recent call last):
  File "pmca-gui.py", line 54, in do
    infoCommand()
  File "/Users/Alchemist/Developer/Repo/Github/ma1co/Sony-PMCA-RE/pmca/commands/usb.py", line 176, in infoCommand
    device = getDevice(driver)
  File "/Users/Alchemist/Developer/Repo/Github/ma1co/Sony-PMCA-RE/pmca/commands/usb.py", line 164, in getDevice
    devices = list(listDevices(driver))
  File "/Users/Alchemist/Developer/Repo/Github/ma1co/Sony-PMCA-RE/pmca/commands/usb.py", line 138, in listDevices
    for type, drv in driverList.listDevices(SONY_ID_VENDOR):
  File "/Users/Alchemist/Developer/Repo/Github/ma1co/Sony-PMCA-RE/pmca/commands/usb.py", line 103, in listDevices
    for dev in driver.listDevices(vendor):
  File "/Users/Alchemist/Developer/Repo/Github/ma1co/Sony-PMCA-RE/pmca/usb/driver/libusb.py", line 64, in _listDevices
    for dev in usb.core.find(find_all=True, idVendor=vendor):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
NoBackendError: No backend available

**Comment by ma1co** [comment]
You have to install libusb: `brew install libusb`

Or you could use the pre-built [binaries](https://github.com/ma1co/Sony-PMCA-RE/releases/latest).
