### ISSUE TITLE
Official development build link expired

### ISSUE THREAD

**Issue by JiaxuanYou** [ma1co/Sony-PMCA-RE#352]
Thanks for building this library!
In the development build link, the built artifacts are expired.
https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts
Coul you please re-run the build job and generate the artifacts again? Thank you!

**Comment by onesml** [comment]
You can bulid the files on your own by following the console log on that page. https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts

**Comment by ManaHime** [comment]
I tried following the steps from that page but I'm a little confused about the usb dlls.
When I try anything on either the command app or the gui one I get this error message:

Loading app list
Found 11 apps

Traceback (most recent call last):
  File "pmca-gui.py", line 117, in do
  File "pmca-gui.py", line 152, in start
  File "pmca\commands\usb.py", line 659, in senserShellCommand
  File "pmca\commands\usb.py", line 145, in importDriver
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pmca\usb\driver\windows\msc.py", line 6, in <module>
ImportError: DLL load failed while importing win32file: The specified module could not be found.

Do you have any idea what I am doing wrong?

**Comment by bigorbi** [comment]
https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip

**Comment by TGE3416** [comment]
> You can bulid the files on your own by following the console log on that page. https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts

@onesml could you walk me through on how to build the files?
