### ISSUE TITLE
Support for ILCE-7M4

### ISSUE THREAD

**Issue by Pikacciu** [ma1co/Sony-PMCA-RE#363]
Hello there!

After downloading the python console .exe, I plugged my camera in and selected MTP mode, then downloaded Zadig to install libusb-win32 driver.
When I execute the code, here is the message I got, and I cannot access to the service mode to unlock language:

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Traceback (most recent call last):
  File "pmca\usb\driver\generic\libusb.py", line 85, in write
  File "usb\core.py", line 994, in write
  File "usb\backend\libusb0.py", line 549, in bulk_write
  File "usb\backend\libusb0.py", line 686, in __write
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pmca-console.py", line 99, in <module>
  File "pmca-console.py", line 85, in main
  File "pmca\commands\usb.py", line 658, in senserShellCommand
  File "pmca\commands\usb.py", line 220, in getDevice
  File "pmca\commands\usb.py", line 198, in listDevices
  File "pmca\usb\__init__.py", line 80, in __init__
  File "pmca\usb\__init__.py", line 122, in openSession
  File "pmca\usb\driver\generic\__init__.py", line 239, in sendCommand
  File "pmca\usb\driver\generic\__init__.py", line 235, in _writeInitialCommand
  File "pmca\usb\driver\generic\__init__.py", line 207, in _writePtp
  File "pmca\usb\driver\generic\__init__.py", line 97, in write
  File "pmca\usb\driver\generic\libusb.py", line 87, in write
pmca.usb.driver.generic.GenericUsbException
[22564] Failed to execute script 'pmca-console' due to unhandled exception!

Someone know what I can do?
Thank you in advance for your help!

I am looking forward to finally be able to change language on my Japanese camera

**Comment by biteme323** [comment]
Have you figured it out to unlock ILCE-7M4? I am also on the same boat trying to unlock language for a Japan bought camera.

**Comment by Pikacciu** [comment]
Hello, 

Yes please follow this trad, it worked perfectly for me: https://github.com/ma1co/Sony-PMCA-RE/issues/355
