### ISSUE TITLE
Can't establish connection to camera

### ISSUE THREAD

**Issue by datalektiker** [ma1co/Sony-PMCA-RE#37]
Version: v0.12 (nothing else installed just running the binary pmca-gui-v0.12-win.exe)
OS: Win 10 64

LOG:
Loading app list
Using local server
Found 7 apps

Traceback (most recent call last):
  File "<string>", line 54, in do
  File "pmca\commands\usb.py", line 175, in infoCommand
  File "pmca\commands\usb.py", line 116, in importDriver
  File "c:\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "pmca\usb\driver\windows\wpd.py", line 15, in <module>
  File "site-packages\comtypes\client\_generate.py", line 112, in GetModule
  File "site-packages\comtypes\client\_generate.py", line 188, in _CreateWrapper
  File "site-packages\comtypes\client\_generate.py", line 26, in _my_import
ImportError: No module named 'comtypes.gen._2B00BA2F_E750_4BEB_9235_97142EDE1D3E_0_1_0'

This log is from trying to use the "Get camera info" button. Want to install OpenMemories hack. 

Would really love som help with this!

/David

**Comment by datalektiker** [comment]
Needed to install the libusb drivers to get ot going..
