### ISSUE TITLE
console / explorer / gui dont work for me

### ISSUE THREAD

**Issue by niddo** [ma1co/Sony-PMCA-RE#38]
console:
```
C:\Users\user01\Downloads>pmca-console.exe install -o outfile.txt
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M2 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "<string>", line 66, in <module>
  File "<string>", line 52, in main
  File "pmca\commands\usb.py", line 207, in installCommand
  File "pmca\commands\usb.py", line 31, in switchToAppInstaller
  File "pmca\usb\sony.py", line 180, in switchToAppInstaller
  File "pmca\usb\sony.py", line 147, in _sendCommand
  File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006
pmca-console returned -1

C:\Users\user01\Downloads>pmca-console install -i
Loading app list
Using local server
Found 7 apps
 [ 1] com.github.ma1co.pmcademo.app
 [ 2] com.github.ma1co.openmemories.tweak
 [ 3] com.github.ma1co.openmemories.appstore
 [ 4] org.bostwickenator.dofmath
 [ 5] org.bostwickenator.googlephotos
 [ 6] com.obsidium.focusbracket
 [ 7] com.obsidium.bettermanual
Enter number of app to install (0 to abort): 1

Installing com.github.ma1co.pmcademo.app
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M2 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "<string>", line 66, in <module>
  File "<string>", line 52, in main
  File "pmca\commands\usb.py", line 207, in installCommand
  File "pmca\commands\usb.py", line 31, in switchToAppInstaller
  File "pmca\usb\sony.py", line 180, in switchToAppInstaller
  File "pmca\usb\sony.py", line 147, in _sendCommand
  File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006
pmca-console returned -1

```
explorer:
```
Loading plugin

Plugin loaded

Starting task

Got task key

Cancelling plugin

Plugin cancelled

Starting download to camera

Error: Network connection
```

gui:

```
Loading app list
Using local server
Found 7 apps

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M2 is a camera in MTP mode

Model:              DSC-RX100M2
Product code:       0080814150
Serial number:      02923495
Firmware version:   1.10

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M2 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "<string>", line 73, in do
  File "pmca\commands\usb.py", line 207, in installCommand
  File "pmca\commands\usb.py", line 31, in switchToAppInstaller
  File "pmca\usb\sony.py", line 180, in switchToAppInstaller
  File "pmca\usb\sony.py", line 147, in _sendCommand
  File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006
```

**Comment by ma1co** [comment]
The RX100M2 does not have an Android subsystem, it is thus not [supported](https://github.com/ma1co/OpenMemories-Framework/blob/master/docs/Cameras.md). The only known way to run code on this camera is via a custom firmware update. However, there is no easy way to do that (for now).

**Comment by niddo** [comment]
ok thanks for the info  !

**Comment by ma1co** [comment]
@niddo 
There is a new experimental way to tweak settings on older cameras using the firmware update functionality. Read more about it [here](https://github.com/ma1co/Sony-PMCA-RE#tweaking-camera-settings). Keep in mind that you are probably the first person to test this on an RX100M2, so your mileage may vary. If you attempt anything, please let us know!
