### ISSUE TITLE
Issue with installing OpenMemories Tweak

### ISSUE THREAD

**Issue by forgottenroot** [ma1co/Sony-PMCA-RE#392]
Trying to install OpenMemories Tweak on an A6300 with Windows 10. I've tried several versions of the software with no success.

```
Loading app list
Found 11 apps

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Model:              ILCE-6300
Product code:       0032828210
Serial number:      03448314
Firmware version:   2.01
Lens:               Model 0xa0c530 (Firmware 3.01)

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Downloading apk
Analyzing apk

Warning: Invalid apk file

Starting task
Starting communication
Uploading 0%
Traceback (most recent call last):
  File "pmca-gui.py", line 77, in do
  File "pmca\commands\usb.py", line 302, in installCommand
  File "pmca\commands\usb.py", line 73, in installApp
  File "pmca\installer\__init__.py", line 74, in install
  File "pmca\usb\sony.py", line 723, in receive
  File "pmca\usb\sony.py", line 649, in receiveMessage
  File "pmca\usb\sony.py", line 641, in _read
  File "pmca\usb\driver\windows\wpd.py", line 182, in sendReadCommand
  File "pmca\usb\driver\windows\wpd.py", line 144, in _readResponse
  File "pmca\usb\driver\windows\wpd.py", line 139, in _send
Exception: MTP SendCommand failed: 0x-7ff8ffe1

```

**Comment by Sujygunsmoke** [comment]
> Trying to install OpenMemories Tweak on an A6300 with Windows 10. I've tried several versions of the software with no success.
> 
> 
> 
> ```
> 
> Loading app list
> 
> Found 11 apps
> 
> 
> 
> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
> 
> Looking for Sony devices
> 
> 
> 
> Querying MTP device
> 
> Sony Corporation ILCE-6300 is a camera in MTP mode
> 
> 
> 
> Model:              ILCE-6300
> 
> Product code:       0032828210
> 
> Serial number:      03448314
> 
> Firmware version:   2.01
> 
> Lens:               Model 0xa0c530 (Firmware 3.01)
> 
> 
> 
> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
> 
> Looking for Sony devices
> 
> 
> 
> Querying MTP device
> 
> Sony Corporation ILCE-6300 is a camera in MTP mode
> 
> 
> 
> Switching to app install mode
> 
> Waiting for camera to switch...
> 
> Downloading apk
> 
> Analyzing apk
> 
> 
> 
> Warning: Invalid apk file
> 
> 
> 
> Starting task
> 
> Starting communication
> 
> Uploading 0%
> 
> Traceback (most recent call last):
> 
>   File "pmca-gui.py", line 77, in do
> 
>   File "pmca\commands\usb.py", line 302, in installCommand
> 
>   File "pmca\commands\usb.py", line 73, in installApp
> 
>   File "pmca\installer\__init__.py", line 74, in install
> 
>   File "pmca\usb\sony.py", line 723, in receive
> 
>   File "pmca\usb\sony.py", line 649, in receiveMessage
> 
>   File "pmca\usb\sony.py", line 641, in _read
> 
>   File "pmca\usb\driver\windows\wpd.py", line 182, in sendReadCommand
> 
>   File "pmca\usb\driver\windows\wpd.py", line 144, in _readResponse
> 
>   File "pmca\usb\driver\windows\wpd.py", line 139, in _send
> 
> Exception: MTP SendCommand failed: 0x-7ff8ffe1
> 
> 
> 
> ```
> 
> 

Have you fixed the error yet?
