### ISSUE TITLE
[M1 Mac] usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by shunsukefuruyama** [ma1co/Sony-PMCA-RE#401]
Clicking on "Get camera info" in pmca-gui, I get the following error:

`Using drivers OS-X-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices
Traceback (most recent call last):
  File "./pmca-gui.py", line 58, in do
    infoCommand()
  File "/Users/user/Sony-PMCA-RE/pmca/commands/usb.py", line 234, in infoCommand
    device = getDevice(driver)
  File "/Users/user/Sony-PMCA-RE/pmca/commands/usb.py", line 222, in getDevice
    devices = list(listDevices(driver))
  File "/Users/user/Sony-PMCA-RE/pmca/commands/usb.py", line 179, in listDevices
    for dev, type, drv in driverList.listDevices(SONY_ID_VENDOR):
  File "/Users/user/Sony-PMCA-RE/pmca/commands/usb.py", line 129, in listDevices
    for dev in driver.listDevices(vendor):
  File "/Users/user/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 45, in _listDevices
    for dev in usb.core.find(find_all=True, idVendor=vendor):
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/usb/core.py", line 1309, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available`

**Comment by rakeshrgill** [comment]
I got it to work by installing libusb
> brew install libusb

**Comment by mattrfk** [comment]
> I got it to work by installing libusb
> 
> > brew install libusb

This got me going in the right direction, but I also had to do this: (on m2 mac)

    ln -s /opt/homebrew/lib ~/lib

https://stackoverflow.com/questions/70729330/python-on-m1-mbp-trying-to-connect-to-usb-devices-nobackenderror-no-backend-a
