### ISSUE TITLE
Access denied - insufficient permissions

### ISSUE THREAD

**Issue by ell654** [ma1co/Sony-PMCA-RE#411]
Hi, I am trying to connect my Sony A7RII. But I always get this error. 
There is a closed with no solution, so I thought I open a new one. 

Here is a screenshot. Hope anyone can help.
![Bildschirmfoto 2023-06-16 um 13 25 44](https://github.com/ma1co/Sony-PMCA-RE/assets/109351595/7d8139f2-6100-4311-93e0-4f0142605f86)

**Comment by oresamp** [comment]
I have the same but by installing (macOS && Windows 10)

**pmcaFilesystemServer** from [snapshop for new UI](https://github.com/schnatterer/pmcaFilesystemServer/pull/4#issuecomment-1425825659)
```
Querying MTP device
Sony Corporation ILCE-7M2 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Analyzing apk

Package: info.schnatterer.pmcaFilesystemServer
Version: 0.1.1-SNAPSHOT

Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 12%
Downloading 27%
Downloading 42%
Downloading 56%
Downloading 71%
Downloading 86%
Downloading 100%
Installing 0%
Traceback (most recent call last):
  File "pmca-gui.py", line 78, in do
  File "pmca\commands\usb.py", line 300, in installCommand
  File "pmca\commands\usb.py", line 73, in installApp
Exception: Communication error 100: Error completed
```

**PMCADemo.app from the App List**
```
Querying MTP device
Sony Corporation ILCE-7M2 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Downloading apk
Analyzing apk

Package: com.github.ma1co.pmcademo.app
Version: 0.7

Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 100%
Installing 0%
Installing 100%
Uploading 0%
Uploading 100%
Task completed successfully
```

**pmcaFilesystemServer** from App List, that is looking at [ver 0.3.0-pre](https://github.com/schnatterer/pmcaFilesystemServer/releases/tag/0.3.0-pre)
```
Querying MTP device
Sony Corporation ILCE-7M2 is a camera in app install mode

Downloading apk
Traceback (most recent call last):
  File "urllib\request.py", line 1318, in do_open
  File "http\client.py", line 1239, in request
  File "http\client.py", line 1285, in _send_request
  File "http\client.py", line 1234, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 964, in send
  File "http\client.py", line 1392, in connect
  File "http\client.py", line 936, in connect
  File "socket.py", line 724, in create_connection
  File "socket.py", line 713, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pmca-gui.py", line 75, in do
  File "pmca\commands\usb.py", line 300, in installCommand
  File "pmca\commands\usb.py", line 57, in installApp
  File "pmca\appstore\__init__.py", line 87, in asset
  File "pmca\appstore\__init__.py", line 90, in _loadAsset
  File "pmca\util\http.py", line 12, in get
  File "pmca\util\http.py", line 31, in request
  File "urllib\request.py", line 526, in open
  File "urllib\request.py", line 544, in _open
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 1361, in https_open
  File "urllib\request.py", line 1320, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

```

**pmcaFilesystemServer** 0.2.0 (last release ver.) from [link](https://github.com/schnatterer/pmcaFilesystemServer/releases/tag/0.2.0)

```
Querying MTP device
Sony Corporation ILCE-7M2 is a camera in app install mode

Analyzing apk

Package: info.schnatterer.pmcaFilesystemServer
Version: 0.2.0

Starting task
Starting communication
Uploading 0%
Uploading 100%
Downloading 100%
Installing 0%
Installing 100%
Uploading 0%
Uploading 100%
Task completed successfully
```
