### ISSUE TITLE
A6700

### ISSUE THREAD

**Issue by ykim418** [ma1co/Sony-PMCA-RE#422]
Would this work on new a6700?

**Comment by zhangyg** [comment]
Yes, the language tweak works for a a6700 from Japan. I run the command line version from a Linux computer, and use pull request #356, otherwise, the camera will reboot when you select certain languages. Basically, no Chinese languages after the tweak, but other languages are there.

**Comment by ykim418** [comment]
Mine is not from japan. Its from Korea, but i do not have english. Only
language i have is Korean, chinese, and arab languages. But i also want to
be clear, after you help me, can i freely update the firmware? I just got
the camera and it has firmware update available.

**Comment by zhangyg** [comment]
I just updated to firmware 1.01 that I downloaded from US website, and the language settings remain.
Since your camera is from Korean, you probably don't need that patch. All you need to do is using the latest version like https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip and follow the instruction.
You probably can do it in Windows.

**Comment by ykim418** [comment]
> I just updated to firmware 1.01 that I downloaded from US website, and the language settings remain.
> Since your camera is from Korean, you probably don't need that patch. All you need to do is using the latest version like https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip and follow the instruction.
> You probably can do it in Windows.
> 

Thabk you. Going to try tonight and let you know =)

**Comment by fimatr93** [comment]
> I just updated to firmware 1.01 that I downloaded from US website, and the language settings remain. Since your camera is from Korean, you probably don't need that patch. All you need to do is using the latest version like https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip and follow the instruction. You probably can do it in Windows.

So if i have purchased the camera in Japan and i want English, can i use this? Have you tried it? It worked on my 6400 but i think 6700 is different,no?

**Comment by zhangyg** [comment]
> > I just updated to firmware 1.01 that I downloaded from US website, and the language settings remain. Since your camera is from Korean, you probably don't need that patch. All you need to do is using the latest version like https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip and follow the instruction. You probably can do it in Windows.
> 
> So if i have purchased the camera in Japan and i want English, can i use this? Have you tried it? It worked on my 6400 but i think 6700 is different,no?

It works for the a6700 I recently bought in Japan, and I also updated to v1.01 w/o problem.

**Comment by fimatr93** [comment]
> > I just updated to firmware 1.01 that I downloaded from US website, and the language settings remain.
> > Since your camera is from Korean, you probably don't need that patch. All you need to do is using the latest version like https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip and follow the instruction.
> > You probably can do it in Windows.
> 
> Thabk you. Going to try tonight and let you know =)

Could you update if it worked for you?

**Comment by ykim418** [comment]
thank you for the help! i was able to unlock all 35 languages. not that i need all of them, but English is activated! 
in case someone need help, i followed this video step by step.
https://www.youtube.com/watch?v=BJhheKXs39A

**Comment by ykim418** [comment]
> thank you for the help! i was able to unlock all 35 languages. not that i need all of them, but English is activated! 
> in case someone need help, i followed this video step by step.
> https://www.youtube.com/watch?v=BJhheKXs39A

I havent been able to delete libusb driver like video, which i plan to do tonight. I havent been able to test anything yet except checking the language was working. Ill poat after testing tonight.

**Comment by Pazu5512** [comment]
It's good to know it still works even with such a recent model, as PMCA haven't been updated in ages. Hopefully it will work with the soon-to-be-announced A7cII and A7cr :blush:
The anonfiles link posted above for the latest binaries doesn't work anymore though

**Comment by edandersen** [comment]
Can confirm this works on a Japanese A6700 as just updated mine.

I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The ```Windows Binaries.zip``` file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.

**Comment by fimatr93** [comment]
> Can confirm this works on a Japanese A6700 as just updated mine to include English.
> 
> I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The `Windows Binaries.zip` file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.

What is the difference from the other version 0.18-18? Is there more options?

**Comment by edandersen** [comment]
> > Can confirm this works on a Japanese A6700 as just updated mine to include English.
> > I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The `Windows Binaries.zip` file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.
> 
> What is the difference from the other version 0.18-18? Is there more options?

I don't think there are any differences, I've just recompiled the app and hosted it on github instead of a link that is dead.

**Comment by Pazu5512** [comment]
Thanks for the binaries :thumbsup:

**Comment by fortheworld2017** [comment]
This is working with all new models well

**Comment by edandersen** [comment]
@ma1co please release a new version of this officially.

**Comment by fortheworld2017** [comment]
We have all new version now

**Comment by skylors** [comment]
I have an A6700 that I have been trying to get the language options unlocked for to no avail.  

I have the official release v0.18 version and all the links to the 0.18-18 version are dead.  I have no second button for a "service mode" in the pmca-gui, only the "updater mode".

Using the console on windows I got the camera to go into service mode, then I was able to update the driver for "Sony USB Device" to the proper driver, but alas the windows console version does not allow for a "tweak" function (just has help, exit, shell, push, pull).

Going to my linux machine, I can run the pmca console and get all the way to applying the "Unlock all languages" option.  Choosing that and applying leads to an error:

`Error: Cannot overwrite backup`

I re-apply and the error doesn't come up again, so I exit and check my camera and I still have the same language options as before.  All 35 languages are not in fact unlocked.

Tried to follow this:

> Can confirm this works on a Japanese A6700 as just updated mine to include English.
I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The Windows Binaries.zip file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.<

But have no idea where the "Windows Binaries.zip file" is on the fork page, or in the 'Source code' zip file.

I feel like I am going crazy because I am so close.  Anyone got any ideas?

**Comment by fortheworld2017** [comment]
Hello @skylors 
You can build gui version again

**Comment by skylors** [comment]
@fortheworld2017 I ended up using the linux pmca-gui, and the changes actually took.  I didn't have the tkinter library so skipped it in favor of the pmca-console, but that one runs up against an error and changes don't save.

**Comment by rlcapr** [comment]
@ykim418 I found myself in the exact situation as you. I just bought an a6700 here in Korea and only later found out that English is locked. I really appreciated your confirming this works on the a6700. Could you let me know if you were able to update the firmware as normal after you unlocked the English? I appreciate your linking the video that helped you, but if you could give any more info on how you performed this on your a6700 I would really appreciate it. It was an expensive camera and I'm really nervous about damaging it.

**Comment by rlcapr** [comment]
@ykim418 I found myself in the exact situation as you. I just bought an a6700 here in Korea and only later found out that English is locked. I really appreciated your confirming this works on the a6700. Could you let me know if you were able to update the firmware as normal after you unlocked the English? I appreciate your linking the video that helped you, but if you could give any more info on how you performed this on your a6700 I would really appreciate it. It was an expensive camera and I'm really nervous about damaging it.

> > thank you for the help! i was able to unlock all 35 languages. not that i need all of them, but English is activated!
> > in case someone need help, i followed this video step by step.
> > https://www.youtube.com/watch?v=BJhheKXs39A
> 
> I havent been able to delete libusb driver like video, which i plan to do tonight. I havent been able to test anything yet except checking the language was working. Ill poat after testing tonight.

**Comment by dreambold** [comment]
@rlcapr Do you have an Ubuntu machine or a laptop? If so, I can help you with the tweaks!

**Comment by rlcapr** [comment]
> @rlcapr Do you have an Ubuntu machine or a laptop? If so, I can help you with the tweaks!

Yes I have an Ubuntu machine. Thank you for helping, I really appreciate it!

**Comment by dreambold** [comment]
Are you available now? If so, please send me a message to asenfan0723@gmail.com

**Comment by ykim418** [comment]
> @ykim418 I found myself in the exact situation as you. I just bought an a6700 here in Korea and only later found out that English is locked. I really appreciated your confirming this works on the a6700. Could you let me know if you were able to update the firmware as normal after you unlocked the English? I appreciate your linking the video that helped you, but if you could give any more info on how you performed this on your a6700 I would really appreciate it. It was an expensive camera and I'm really nervous about damaging it.
> 
> > > thank you for the help! i was able to unlock all 35 languages. not that i need all of them, but English is activated!
> > > in case someone need help, i followed this video step by step.
> > > https://www.youtube.com/watch?v=BJhheKXs39A
> > 
> > I havent been able to delete libusb driver like video, which i plan to do tonight. I havent been able to test anything yet except checking the language was working. Ill poat after testing tonight.
> 
> 

I was able to update firmware with no problem. And yes, as of now, all languages are unkocked. =)

**Comment by allbusiness1** [comment]
> > @rlcapr Do you have an Ubuntu machine or a laptop? If so, I can help you with the tweaks!
> 
> Yes I have an Ubuntu machine. Thank you for helping, I really appreciate it!

Did you end up getting it to work?

**Comment by rlcapr** [comment]
Yes, it works great. No problems at all. I wasn’t able to get it to work on my windows machine but it worked easily on my Ubuntu machine. My camera was bought in korea and had korean Chinese and a few other languages but I needed English unlocked. On Oct 13, 2023, at 1:48 AM, allbusiness1 ***@***.***> wrote:﻿


@rlcapr Do you have an Ubuntu machine or a laptop? If so, I can help you with the tweaks!

Yes I have an Ubuntu machine. Thank you for helping, I really appreciate it!

Did you end up getting it to work?

**Comment by astrozzj** [comment]
> It's good to know it still works even with such a recent model, as PMCA haven't been updated in ages. Hopefully it will work with the soon-to-be-announced A7cII and A7cr 😊
> The anonfiles link posted above for the latest binaries doesn't work anymore though

It works on my Japanese version A7C2. English is supported while Chinese is still not. NTSC/PAL switch is not supported as well. I use MacBook Pro 14, MacOS 13.4.1, and follow the procedure provided by @aikinai in #327.

> > Can confirm this works on a Japanese A6700 as just updated mine to include English.
> > I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The `Windows Binaries.zip` file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.
> 
> What is the difference from the other version 0.18-18? Is there more options?

Same on A7C2, "Cannot overwrite backup" but works fine. When I tweak again, no error appears at all.

**Comment by astrozzj** [comment]
> It's good to know it still works even with such a recent model, as PMCA haven't been updated in ages. Hopefully it will work with the soon-to-be-announced A7cII and A7cr 😊
> The anonfiles link posted above for the latest binaries doesn't work anymore though

It works on Japanese version A7C2, English is OK, but still no Chinese or other languages.

**Comment by solohsu** [comment]
> > It's good to know it still works even with such a recent model, as PMCA haven't been updated in ages. Hopefully it will work with the soon-to-be-announced A7cII and A7cr 😊
> > The anonfiles link posted above for the latest binaries doesn't work anymore though
> 
> It works on my Japanese version A7C2. English is supported while Chinese is still not. NTSC/PAL switch is not supported as well. I use MacBook Pro 14, MacOS 13.4.1, and follow the procedure provided by @aikinai in #327.
> 
> > > Can confirm this works on a Japanese A6700 as just updated mine to include English.
> > > I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The `Windows Binaries.zip` file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.
> > 
> > 
> > What is the difference from the other version 0.18-18? Is there more options?
> 
> Same on A7C2, "Cannot overwrite backup" but works fine. When I tweak again, no error appears at all.

If you want to enable Chinese, maybe you can try the approach proposed by https://github.com/ma1co/Sony-PMCA-RE/pull/356 : change the region value in BackupHeader from "xxx_J1" to "xxx_CN1"

**Comment by aikinai** [comment]
> It works on my Japanese version A7C2.

I was _just_ thinking about upgrading to an A7C2 and was wondering about that, so thanks for confirming @astrozzj!

**Comment by kkthinksky** [comment]
I have a Japanese version A6700 and try to unlock english language but using pmca-gui in window can't get to the tweak service mode. I did follow everything from this video https://www.youtube.com/watch?v=BJhheKXs39A but can't get the service mode tweak show up and have camera as Sony USB device show up. I install ubuntu on my PC now and wonder where I can find the code and instruction to unlock using ubuntu. Thanks

**Comment by astrozzj** [comment]
> I have a Japanese version A6700 and try to unlock english language but using pmca-gui in window can't get to the tweak service mode. I did follow everything from this video https://www.youtube.com/watch?v=BJhheKXs39A but can't get the service mode tweak show up and have camera as Sony USB device show up. I install ubuntu on my PC now and wonder where I can find the code and instruction to unlock using ubuntu. Thanks

Try this one: https://youtu.be/06x0_Edrph8?si=6h2EHDA5C4sT3EYv

**Comment by kkthinksky** [comment]
> > I have a Japanese version A6700 and try to unlock english language but using pmca-gui in window can't get to the tweak service mode. I did follow everything from this video https://www.youtube.com/watch?v=BJhheKXs39A but can't get the service mode tweak show up and have camera as Sony USB device show up. I install ubuntu on my PC now and wonder where I can find the code and instruction to unlock using ubuntu. Thanks
> 
> Try this one: https://youtu.be/06x0_Edrph8?si=6h2EHDA5C4sT3EYv

Thank you. I try the code from the video below but on the second command 
git clone https://github.com/ma1co/Sony-PMCA-RE
I got the response from ubuntu below
fatal: destination path 'Sony-PMCA-RE' already exists and is not an empty directory.
then after pip install -r requirement.txt
I got Command 'pip' not found, but can be installed with: 
sudo apt install python3-pip
then I run the next sudo apt install python3-tk but after I hit y it reply with many error.

so I am still not able to connect the service. I read the previous post from you mention there is a new release (see below quote) for A6700, I wonder if you can give me some help on the new code line on how to link and use that new release to work on my A6700. Thanks.

"Can confirm this works on a Japanese A6700 as just updated mine to include English.
I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The Windows Binaries.zip file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine."


From video description.
sudo apt install git
git clone https://github.com/ma1co/Sony-PMCA-RE
cd Sony-PMCA-RE
pip install -r requirements.txt
sudo apt install python3-tk
./pmca-gui.py

**Comment by astrozzj** [comment]
> > > I have a Japanese version A6700 and try to unlock english language but using pmca-gui in window can't get to the tweak service mode. I did follow everything from this video https://www.youtube.com/watch?v=BJhheKXs39A but can't get the service mode tweak show up and have camera as Sony USB device show up. I install ubuntu on my PC now and wonder where I can find the code and instruction to unlock using ubuntu. Thanks
> > 
> > 
> > Try this one: https://youtu.be/06x0_Edrph8?si=6h2EHDA5C4sT3EYv
> 
> Thank you. I try the code from the video below but on the second command git clone https://github.com/ma1co/Sony-PMCA-RE I got the response from ubuntu below fatal: destination path 'Sony-PMCA-RE' already exists and is not an empty directory. then after pip install -r requirement.txt I got Command 'pip' not found, but can be installed with: sudo apt install python3-pip then I run the next sudo apt install python3-tk but after I hit y it reply with many error.
> 
> so I am still not able to connect the service. I read the previous post from you mention there is a new release (see below quote) for A6700, I wonder if you can give me some help on the new code line on how to link and use that new release to work on my A6700. Thanks.
> 
> "Can confirm this works on a Japanese A6700 as just updated mine to include English. I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The Windows Binaries.zip file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine."
> 
> From video description. sudo apt install git git clone https://github.com/ma1co/Sony-PMCA-RE cd Sony-PMCA-RE pip install -r requirements.txt sudo apt install python3-tk ./pmca-gui.py

They are normal commands before the last one "./pmca-gui.py". You may need to figure out why you cannot install python3-tk and so on. Just google the error posted in your terminal.

**Comment by dreambold** [comment]
You need to run `python3 ./pmca-gui.py serviceshell`

**Comment by ozz809** [comment]
¿I there a way to do it with windows? I have no experience with programing a need to unlock english for the a6700

**Comment by muhski86** [comment]
> ¿I there a way to do it with windows? I have no experience with programing a need to unlock english for the a6700

Yes, there is! I just unlocked all languages on a A6700 which I bought in China.
I used this Video as a reference (its Vietnamese, but with subtitles).
https://www.youtube.com/watch?v=BJhheKXs39A&ab_channel=Ho%C3%A0ng%C4%90%C3%A2y%21

No programming needed! I used the files the guy linked in the video, but I think they are exactly the same like here.
Only additional step I had to do: After unlocking the languages, I had to restart the camera once, then the languages showed up.

**Comment by Wirumnd** [comment]
> > ¿I there a way to do it with windows? I have no experience with programing a need to unlock english for the a6700
> 
> Yes, there is! I just unlocked all languages on a A6700 which I bought in China. I used this Video as a reference (its Vietnamese, but with subtitles). https://www.youtube.com/watch?v=BJhheKXs39A&ab_channel=Ho%C3%A0ng%C4%90%C3%A2y%21
> 
> No programming needed! I used the files the guy linked in the video, but I think they are exactly the same like here. Only additional step I had to do: After unlocking the languages, I had to restart the camera once, then the languages showed up.

Are u used The same ZVE10 Model on zadig for Sony A6700?  I need your reply please.

**Comment by muhski86** [comment]
> > > ¿I there a way to do it with windows? I have no experience with programing a need to unlock english for the a6700
> > 
> > 
> > Yes, there is! I just unlocked all languages on a A6700 which I bought in China. I used this Video as a reference (its Vietnamese, but with subtitles). https://www.youtube.com/watch?v=BJhheKXs39A&ab_channel=Ho%C3%A0ng%C4%90%C3%A2y%21
> > No programming needed! I used the files the guy linked in the video, but I think they are exactly the same like here. Only additional step I had to do: After unlocking the languages, I had to restart the camera once, then the languages showed up.
> 
> Are u used The same ZVE10 Model on zadig for Sony A6700? I need your reply please.

If you mean if I choose ZVE10 to install the drivers then, no. When you connect the camera to your computer and use zadig, it should show A6700 in the dropdown menu. All other steps are exactly the same.

**Comment by doybid** [comment]
can someone help pls. followed the video tutorial posted here, however when i use the pmca-gui-v0.18-22-ga82f5ba-win. i follow the steps start tweaking (service mode) then it shows this

Loading app list
Found 11 apps

Traceback (most recent call last):
  File "pmca-gui.py", line 117, in do
  File "pmca-gui.py", line 152, in start
  File "pmca\commands\usb.py", line 659, in senserShellCommand
  File "pmca\commands\usb.py", line 146, in importDriver
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pmca\usb\driver\windows\wpd.py", line 21, in <module>
  File "comtypes\client\_generate.py", line 128, in GetModule
  File "comtypes\client\_generate.py", line 162, in _load_tlib
  File "comtypes\typeinfo.py", line 485, in LoadTypeLibEx
  File "_ctypes/callproc.c", line 940, in GetResult
OSError: [WinError -2147312566] Error loading type library/DLL

did again the reinstalling of drivers using zadig
it still wont lead to the part where i uncheck or check the unlock 35 languages-

**Comment by TOL00** [comment]
hello, help me please enable PAL NTSC selection, I do everything as indicated, but in the tweaks tab I only have two options - languages ​​​​and disabling the limit
![photo_2024-03-11_00-15-20](https://github.com/ma1co/Sony-PMCA-RE/assets/162926569/8db3310f-e366-4d13-96e5-1d55814fe70e)

**Comment by muhski86** [comment]
Are you certain that you cannot choose NTSC/PAL already in your camera settings? I can can switch it in my camera, but to be honest, I don't remember if I activated it via this mod here or if it was available by default. I bought a the Chinese language version.

**Comment by TOL00** [comment]
> Are you certain that you cannot choose NTSC/PAL already in your camera settings? I can can switch it in my camera, but to be honest, I don't remember if I activated it via this mod here or if it was available by default. I bought a the Chinese language version.

Unfortunately, this setting is not available in the camera menu.

**Comment by DrewTNBD** [comment]
Hello. A new a6700 user here too. I managed to get my languages unlocked, but I also do not have the PAL/NTSC selection option showing up in neither the camera itself, nor the pcma-gui application. Anyone know why?

**Comment by dg-fullstack** [comment]
Is there anyone who can customise UI of sony a6700?

**Comment by Dorian99999** [comment]
I have the same problem, no pal/secam selection since update 1.03 on a 6700, when I do the procedure explained in the video I get the message no tweak available.

**Comment by Nebulater** [comment]
> I have the same problem, no pal/secam selection since update 1.03 on a 6700, when I do the procedure explained in the video I get the message no tweak available.

I just bought an A6700 from Japan and I followed the steps of the video, only to also get a "no tweak available". I wasn't able to even get to the page that has the language unlock box on it.

**Comment by triplife007** [comment]
> I just updated to firmware 1.01 that I downloaded from US website, and the language settings remain. Since your camera is from Korean, you probably don't need that patch. All you need to do is using the latest version like https://anonfiles.com/y1V5K7B7y0/pmca-v0.18-18-gd634e6c-win_zip and follow the instruction. You probably can do it in Windows.

Is this latest version link available? not able to reach the path, also in stable or dev releases no new items after 2022. Am I missing something can you help me with a download link please.

A6700 bought from japan.

**Comment by triplife007** [comment]
> Hello. A new a6700 user here too. I managed to get my languages unlocked, but I also do not have the PAL/NTSC selection option showing up in neither the camera itself, nor the pcma-gui application. Anyone know why?

can you share the download link of the windows binaries you tried. A6700 bought from japan.

**Comment by muhski86** [comment]
> I have the same problem, no pal/secam selection since update 1.03 on a 6700, when I do the procedure explained in the video I get the message no tweak available.

Strange... I just updated via the creators app to 1.03 and all my settings remain... Language settings as well as PAL/NTSC selector...
I have a Chinese/HK camera.

**Comment by beason409** [comment]
Do someone meet this problem? I got my a6700 connect to my linux computer in MSC mode,the linux can recognize it and I can see my photos from linux.  But this program didn't find my device, always show Error Like"raise USBError(_strerror(ret), ret, _libusb_errno[ret])usb.core.USBError: [Errno 13] Access denied (insufficient permissions)" what can I do? Please Help!!!!!

**Comment by beason409** [comment]
> Yes, the language tweak works for a a6700 from Japan. I run the command line version from a Linux computer, and use pull request #356, otherwise, the camera will reboot when you select certain languages. Basically, no Chinese languages after the tweak, but other languages are there.

want to know which Linux system you used？Linuxmint？because I try Linux like you but the command line program did not recognize my a6700 from Japan，just some “raise USB error”

**Comment by realzuoc** [comment]
> > It's good to know it still works even with such a recent model, as PMCA haven't been updated in ages. Hopefully it will work with the soon-to-be-announced A7cII and A7cr 😊
> > The anonfiles link posted above for the latest binaries doesn't work anymore though
> 
> It works on my Japanese version A7C2. English is supported while Chinese is still not. NTSC/PAL switch is not supported as well. I use MacBook Pro 14, MacOS 13.4.1, and follow the procedure provided by @aikinai in #327.
> 
> > > Can confirm this works on a Japanese A6700 as just updated mine to include English.
> > > I've forked and rebuilt the master branch and published a new release here: https://github.com/edandersen/Sony-PMCA-RE/releases/tag/master. The `Windows Binaries.zip` file has the console app and GUI that works with the A6700. It did complain about "unable to something something backup" with a python stack trace after applying the language tweak but it works fine.
> > 
> > 
> > What is the difference from the other version 0.18-18? Is there more options?
> 
> Same on A7C2, "Cannot overwrite backup" but works fine. When I tweak again, no error appears at all.

I think I have the same situation.
My device is A7RV, Japan version, the service shell give two option in tweak sub menu, the limit of the video recording, and the language 35 option, however, after unlock all the language and exit, when select language on the camera, it could not circulate to all language option, it stops at Vietnamese and Arabic, then the camera would reboot automatically. Because English is on 1st place, so it is obvious that Eng is ok to use. However, for language inside the unreachable selections, it seems no use.

**Comment by astrozzj** [comment]
> > I have the same problem, no pal/secam selection since update 1.03 on a 6700, when I do the procedure explained in the video I get the message no tweak available.
> 
> Strange... I just updated via the creators app to 1.03 and all my settings remain... Language settings as well as PAL/NTSC selector... I have a Chinese/HK camera.

I think Chinese/HK camera has PAL/NTSC originally. Those cannot switch are from Japan I guess.

**Comment by BartoszMurzyn** [comment]
> @rlcapr Do you have an Ubuntu machine or a laptop? If so, I can help you with the tweaks!

What about MacBooks?

**Comment by xiaofanpark** [comment]
![image](https://github.com/user-attachments/assets/f17d98d0-1c5c-4678-bc58-550a6cbdcedd)
Windows solution not works with 6700 V1.0.3. Shows no tweaks available

**Comment by haqigokil** [comment]
if you find the problem "no tweak available" you should use zadig with version 2.8, do not use the latest version.

**Comment by roshankhatri3461** [comment]
> > > @rlcapr Do you have an Ubuntu machine or a laptop? If so, I can help you with the tweaks!
> > 
> > 
> > Yes I have an Ubuntu machine. Thank you for helping, I really appreciate it!
> 
> Did you end up getting it to work?

I have laptop can you help me please

**Comment by roshankhatri3461** [comment]
> ![image](https://private-user-images.githubusercontent.com/42580548/378065972-f17d98d0-1c5c-4678-bc58-550a6cbdcedd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDQwMDMsIm5iZiI6MTczMzMwMzcwMywicGF0aCI6Ii80MjU4MDU0OC8zNzgwNjU5NzItZjE3ZDk4ZDAtMWM1Yy00Njc4LWJjNTgtNTUwYTZjYmRjZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA5MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMzYzM2Y1NWY3MjBjZGQ4MjA5OTQ3ZjlkMDhlNmZlY2U3NGJjYjEwMjA2YjU1ZTc2MWE3OTA0YjAzMjVjYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MPoaAy__TUpaJqsARKD0j3t8U5OqquA_qHXAcwQZGRI) Windows solution not works with 6700 V1.0.3. Shows no tweaks available

I have same problem it shows no tweaks available how can i fix thish problem?

**Comment by roshankhatri3461** [comment]
> I have the same problem, no pal/secam selection since update 1.03 on a 6700, when I do the procedure explained in the video I get the message no tweak available.

Do you get any solution?

**Comment by MrGreeneyed** [comment]
> ![image](https://github.com/user-attachments/assets/f17d98d0-1c5c-4678-bc58-550a6cbdcedd) Решение Windows не работает с 6700 V1.0.3. Показывает недоступные настройки

As a result, someone managed to change the languages to English to A6700 firmware version 1.03?

**Comment by CostardRouge** [comment]
The GUI didnot worked for me but the console binary did:

> sudo ./pmca-console.py serviceshell
> tweak ...

**Comment by pokeimon** [comment]
Would the language mod work with the new 2.0 firmware release?

**Comment by GiovanniTRA** [comment]
> Would the language mod work with the new 2.0 firmware release?

It does work on Sony A6700 firmware 2.0. Tested it on macOS Sonoma 14.3
