### ISSUE TITLE
Whether dsc-w810 is supported

### ISSUE THREAD

**Issue by rosenari** [ma1co/Sony-PMCA-RE#424]
Does Sony-PMCA-RE support dsc-w810??

**Comment by Quwuei** [comment]
not support. PMCA supports only some models using Sony BIONZ image processors. The W810 uses the Zoran Coach image processor.

It's a different platform. The W810 is completely useless in service mode.

**Comment by SamiMohr** [comment]
Same question here.

When getting the camera info in gui I receive: 

`Traceback (most recent call last):
  File "pmca-gui.py", line 56, in do
  File "pmca\commands\usb.py", line 256, in infoCommand
  File "pmca\usb\sony.py", line 351, in getLensInfo
  File "pmca\usb\sony.py", line 276, in _sendCommand
  File "pmca\usb\sony.py", line 102, in sendSonyExtCommand
  File "pmca\usb\driver\generic\__init__.py", line 171, in sendReadCommand
Exception: Mass storage read error`

Using tweak returns
`Getting device info
Using firmware for model DSC-W810`

Switching to install mode returns 
`Switching to app install mode
Waiting for camera to switch...
Operation timed out. Please run this command again when your camera has connected.
`

Help would be appreciated
