### ISSUE TITLE
Sony SR11 - Can't install OpenMemories Tweak or use updater mode

### ISSUE THREAD

**Issue by pamflambe** [ma1co/Sony-PMCA-RE#426]
Would love to help get SR11/SR12 supported if possible, got 2 camcorders stuck in Japanese currently.
Here are the logs:

**Install app:**
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Switching to app install mode
Waiting for camera to switch...
Operation timed out. Please run this command again when your camera has connected.

**Start tweaking (updater mode):**
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 57, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 244, in infoCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 251, in getCameraInfo
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 75, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 40, in _checkResponse
pmca.usb.MscException: Mass storage error: Sense 0x9 0x81 0x83

**Comment by nesquik9** [comment]
also have this issue. the sr11 doesnt appear on the compatibility list all i wanted to do was change my imported camcorder from japanese to english, but im not sure its possible

**Comment by bigguy1997** [comment]
ive been able to get pmca to communicate with my sr11 although doing so gives zero results for tweaking
![image](https://github.com/user-attachments/assets/a602969f-b278-4920-8065-87346dfcc123)

i followed the service mode guide in the readme file while using a dev build (v0.18-14)

**Comment by phillip9933** [comment]
There are issues with the windows build.  I cannot guarantee this will solve your issue but please try using Linux instead.  If you don't have a Linux PC available I have out together a love cd you can use.

https://github.com/ma1co/Sony-PMCA-RE/issues/459#issuecomment-2208164901

**Comment by bigguy1997** [comment]
> There are issues with the windows build. I cannot guarantee this will solve your issue but please try using Linux instead. If you don't have a Linux PC available I have out together a love cd you can use.
> 
> [#459 (comment)](https://github.com/ma1co/Sony-PMCA-RE/issues/459#issuecomment-2208164901)

i tried your ubuntu build and followed everything from the issue you mentioned, shows the same results as the windows build just no pop up! i better start on my japanese since @ma1co hasnt updated the build in a while!!
![image](https://github.com/user-attachments/assets/a2771e54-6ca3-4ffc-aaef-b1fd5f99e73a)

**Comment by dzastsed** [comment]
Hey, you can swap language to english if you get serviceshell access with CLI version of this tool. You need to run this command:
`cp /usr/local/Fsk/applications/data/language/english.bin /usr/local/Fsk/applications/data/language/japanese.bin`
