### ISSUE TITLE
Here you can get PMCA 18.22 GUI and console with a HowTo video

### ISSUE THREAD

**Issue by masterflai** [ma1co/Sony-PMCA-RE#429]
After the Development Branch was deleted, there are only a few sources for the last version 18.22 of the PMCA tools. I have found a current video on Youtube, which on the one hand shows exactly how to proceed in order to be able to use the service mode. But at the same time the Youtuber has also provided the two files in the latest version 18.22. Have fun and success modding the camera. 

Note: The changes can cause irreparable damage to the camera. Please consider very carefully what you want to achieve and what risks you take. I am neither the creator of the video, nor the linked files. Please always check downloaded files for viruses before using them, as the content could change at any time.

[HowToVideo](https://www.youtube.com/watch?v=82A_SxMjtc0)

[PMCA GUI and console 18.22](https://app.box.com/s/0u2gyrrtwoeosvghpv902e8cwzk537i3)

**Comment by dreambold** [comment]
I managed to run the script in Ubuntu 22.04 and it works perfectly from the console. Might need to install some dependencies, of course. 

Just run `./pmca-console.py serviceshell` and it will prompt options to configure for the mod.

**Comment by foreigncarnut** [comment]
This does not support the DSC-R1. Is there a way to add this support? Trying to unlock languages

**Comment by masterflai** [comment]
> This does not support the DSC-R1. Is there a way to add this support? Trying to unlock languages

The project is no longer being developed. Unless the R1 is natively supported, there is no real chance of a future fix. However, the camera itself is so old that the old mechanism without encryption should still be available. I would still advise against trying this out. The risk of permanent damage is unfortunately very high.

**Comment by foreigncarnut** [comment]
Thank You for your response. I thought as much but the Sony policy is very disappointing. The arbitrary marketing decision to limit languages just makes customers mad. It really serves no real purpose. 

What did you mean by the old mechanism without encryption still being available? What is this and where would it be? I saw a solution for other cameras by a person named Vitaliy Keselev but it was over my head and you need to download a Linux kernel and package from the sony distribution site but was not able to find them for my DSC-R1 camera. So I do not think I will ever be able to get English on the camera. Not sure why the firmware could not be extracted from an english camera and loaded into a japanese camera, but that is also over my head.

**Comment by masterflai** [comment]
> Thank You for your response. I thought as much but the Sony policy is very disappointing. The arbitrary marketing decision to limit languages just makes customers mad. It really serves no real purpose.
> 
> What did you mean by the old mechanism without encryption still being available? What is this and where would it be? I saw a solution for other cameras by a person named Vitaliy Keselev but it was over my head and you need to download a Linux kernel and package from the sony distribution site but was not able to find them for my DSC-R1 camera. So I do not think I will ever be able to get English on the camera. Not sure why the firmware could not be extracted from an english camera and loaded into a japanese camera, but that is also over my head.

Sony began to encrypt the memory areas of the later cameras to prevent investigations and manipulation. One reason for the non-existence of the DSC-R1 could simply be its exclusivity. The model was extremely expensive by the standards of the time and consequently very rare to find. Those who owned one rarely had the willingness to examine it.

So how should you proceed? It's best to use the last build package linked above. You should then use the console version if you can, as this version has the greatest functional scope. Then there are two approaches via updatershell or serviceshell. While the updatershell did not work for all models, the serviceshell always worked for all[ linked models](https://openmemories.readthedocs.io/devices.html). Your model dates from this time and could well work perfectly with the serviceshell. Just try reading out and accessing it first. Remember, however, that you will need to install the appropriate USB drivers for this to work.

**Comment by foreigncarnut** [comment]
Thanks once more for your reply. This gives me a little hope even though my camera is not listed.

Let me explain what I have done so far.
1. Ran Zadig to install alternative USB drivers.
2. Ran pmca-console-v0.18-22-ga82f5ba-win.exe to put camera into service mode
3. Ran pmca-gui-v0.18-22-ga82f5ba-win.exe to try and install and run program

The results I get are:
Using drivers Windows-MSC, Windows-MIP, Windows-vendor-specific, libusb-M5C, libusb-MIP, libusb-vendor-specific Looking for Sony devices
Querying mass storage device
No devices found. Please make sure that camera is connected.

I will view the video to see if maybe I can try something different. I will see if I can figure out how to use the serviceshell. I did not see any serviceshell but maybe missed it

**Comment by masterflai** [comment]
I would definitely use the console version. Make sure you install the correct drivers beforehand and check them in the device manager if necessary. It is true that the mass storage device is no longer recognized if the alternative drivers are used. It is therefore essential to remove this driver when you are finished. If you receive the message that the mass storage device was not found, it is possible that you have already installed the driver correctly. Then try using Console. There were also videos, but I no longer have them in front of me.

**Comment by foreigncarnut** [comment]
I tried again with no success. I did notice one thing though In Zadig, I can install either libusb-win32 (v1.4.0.0) and libusbK (v3.1.0.0) and they both install successfully but the WCID still always has a red X next to it instead of a green check. 
I have tried to install either one and then run pmca-console-v0.18-22-ga82f5ba-win.exe with either one and the red X never goes away. Maybe it is a USB issue?

**Comment by masterflai** [comment]
The issue with the USB drivers also bothered me a bit, but eventually it worked. I would assume that the drivers are not installed correctly if they are not marked green.

**Comment by foreigncarnut** [comment]
The thing is that the camera does appear in device manager under the device driver that was just installed. Installing the device driver does move it out of the USB section and the driver does show correctly. Also Zadig does show that it was installed correctly. The arrow does also show green. Only the WCID shows a red X. Do you have any ideas or suggestions for this?

**Comment by masterflai** [comment]
Unfortunately, I'm no longer entirely familiar with Zadig. I last used it months ago and there is now a newer version. Maybe the [Zadig help section ](https://github.com/pbatard/libwdi/wiki/Zadig)will help you here.

**Comment by foreigncarnut** [comment]
Thank you. I do not know how to use the console correctly. When I run it, it just flashes and then goes away. I think it is changing the mode on the camera but it gives me no opportunity to enter commands

**Comment by foreigncarnut** [comment]
Still not working but when I try to run serviceshell in console, at least I get some kind of tracing

Maybe someone that knows the driver can address it?

 

D:\Browser Downloads>pmca-console-v0.18-22-ga82f5ba-win serviceshell

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific

Looking for Sony devices

 

Querying mass storage device

Traceback (most recent call last):

  File "pmca\usb\driver\generic\libusb.py", line 91, in classInterfaceRequestOut

  File "usb\core.py", line 1089, in ctrl_transfer

  File "usb\backend\libusb0.py", line 609, in ctrl_transfer

  File "usb\backend\libusb0.py", line 447, in _check

usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: The semaphore timeout period has expired.\r\n\n'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "pmca-console.py", line 104, in <module>

  File "pmca-console.py", line 88, in main

  File "pmca\commands\usb.py", line 660, in senserShellCommand

  File "pmca\commands\usb.py", line 222, in getDevice

  File "pmca\commands\usb.py", line 184, in listDevices

  File "pmca\usb\__init__.py", line 26, in __init__

  File "pmca\usb\__init__.py", line 50, in reset

  File "pmca\usb\driver\generic\__init__.py", line 180, in sendCommand

  File "pmca\usb\driver\generic\__init__.py", line 177, in _writeCommand

  File "pmca\usb\driver\generic\libusb.py", line 93, in classInterfaceRequestOut

pmca.usb.driver.generic.GenericUsbException

**Comment by foreigncarnut** [comment]
In running the info command, I get

 

D:\Browser Downloads>pmca-console-v0.18-22-ga82f5ba-win info

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific

Looking for Sony devices

 

Querying mass storage device

Traceback (most recent call last):

  File "pmca\usb\driver\generic\libusb.py", line 91, in classInterfaceRequestOut

  File "usb\core.py", line 1089, in ctrl_transfer

  File "usb\backend\libusb0.py", line 609, in ctrl_transfer

  File "usb\backend\libusb0.py", line 447, in _check

usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: The semaphore timeout period has expired.\r\n\n'

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "pmca-console.py", line 104, in <module>

  File "pmca-console.py", line 68, in main

  File "pmca\commands\usb.py", line 234, in infoCommand

  File "pmca\commands\usb.py", line 222, in getDevice

  File "pmca\commands\usb.py", line 184, in listDevices

  File "pmca\usb\__init__.py", line 26, in __init__

  File "pmca\usb\__init__.py", line 50, in reset

  File "pmca\usb\driver\generic\__init__.py", line 180, in sendCommand

  File "pmca\usb\driver\generic\__init__.py", line 177, in _writeCommand

  File "pmca\usb\driver\generic\libusb.py", line 93, in classInterfaceRequestOut

pmca.usb.driver.generic.GenericUsbException

[41912] Failed to execute script 'pmca-console' due to unhandled exception!

**Comment by foreigncarnut** [comment]
This is what happens when I run the info command with the original windows USB driver

 

D:\Browser Downloads>pmca-console-v0.18-22-ga82f5ba-win info

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific

Looking for Sony devices

 

Querying mass storage device

 

No devices found. Please make sure that the camera is connected.

 

As you can see, it fails immediately. So that means the ZADIG driver is partially working.

**Comment by masterflai** [comment]
I would recommend organizing one of the listed compatible cameras for a first try. Many entry-level models are now available for just a few euros. Then you can try everything out at your leisure and gain experience, and you will also know that it should theoretically work. With your model, you just don't know yet. Everything I can see suggests a problem with the USB cable, the driver or a lack of basics.

**Comment by masterflai** [comment]
![2023-09-03 11_06_10](https://github.com/ma1co/Sony-PMCA-RE/assets/32191717/ea94fbce-f80c-4020-9141-9ae36b36fdc5)

This is how it should look like.

**Comment by rsmallfoot-debug** [comment]
> After the Development Branch was deleted, there are only a few sources for the last version 18.22 of the PMCA tools. I have found a current video on Youtube, which on the one hand shows exactly how to proceed in order to be able to use the service mode. But at the same time the Youtuber has also provided the two files in the latest version 18.22. Have fun and success modding the camera.
> 
> Note: The changes can cause irreparable damage to the camera. Please consider very carefully what you want to achieve and what risks you take. I am neither the creator of the video, nor the linked files. Please always check downloaded files for viruses before using them, as the content could change at any time.
> 
> [HowToVideo](https://www.youtube.com/watch?v=82A_SxMjtc0)
> 
> [PMCA GUI and console 18.22](https://app.box.com/s/0u2gyrrtwoeosvghpv902e8cwzk537i3)

THANK YOU !!!  using PMCA 18-22 worked on a6700 sony with firmware 2.0 - thanks for providing the pmca download - awsome!!

**Comment by masterflai** [comment]
> > After the Development Branch was deleted, there are only a few sources for the last version 18.22 of the PMCA tools. I have found a current video on Youtube, which on the one hand shows exactly how to proceed in order to be able to use the service mode. But at the same time the Youtuber has also provided the two files in the latest version 18.22. Have fun and success modding the camera.
> > Note: The changes can cause irreparable damage to the camera. Please consider very carefully what you want to achieve and what risks you take. I am neither the creator of the video, nor the linked files. Please always check downloaded files for viruses before using them, as the content could change at any time.
> > [HowToVideo](https://www.youtube.com/watch?v=82A_SxMjtc0)
> > [PMCA GUI and console 18.22](https://app.box.com/s/0u2gyrrtwoeosvghpv902e8cwzk537i3)
> 
> THANK YOU !!! using PMCA 18-22 worked on a6700 sony with firmware 2.0 - thanks for providing the pmca download - awsome!!

That's quite interesting. The firmware of Sony A6700 is completely encrypted and shouldn't be compatible with the old methods of analyzing and modding. Can you tell us what you have done or changed and via which mode? That would be great.

**Comment by rsmallfoot-debug** [comment]
> > > After the Development Branch was deleted, there are only a few sources for the last version 18.22 of the PMCA tools. I have found a current video on Youtube, which on the one hand shows exactly how to proceed in order to be able to use the service mode. But at the same time the Youtuber has also provided the two files in the latest version 18.22. Have fun and success modding the camera.
> > > Note: The changes can cause irreparable damage to the camera. Please consider very carefully what you want to achieve and what risks you take. I am neither the creator of the video, nor the linked files. Please always check downloaded files for viruses before using them, as the content could change at any time.
> > > [HowToVideo](https://www.youtube.com/watch?v=82A_SxMjtc0)
> > > [PMCA GUI and console 18.22](https://app.box.com/s/0u2gyrrtwoeosvghpv902e8cwzk537i3)
> > 
> > 
> > THANK YOU !!! using PMCA 18-22 worked on a6700 sony with firmware 2.0 - thanks for providing the pmca download - awsome!!
> 
> That's quite interesting. The firmware of Sony A6700 is completely encrypted and shouldn't be compatible with the old methods of analyzing and modding. Can you tell us what you have done or changed and via which mode? That would be great.

My goal was to unlock the languages - which it did - it now has 35 languages.  I just used Zadig for the driver (libusb) and then the gui of pmca 18-22.  Under tweak.....it had the option to "unlock languages...." I checked this and it worked.

**Comment by masterflai** [comment]
Wow, very good. I didn't think this would still be possible with the A6700. I have it here and I'm going to test it. 

Very important for untested devices: Your camera may display a black screen after a reset of the settings when the language patch was active. 

Don't panic! 

If this happens, you can connect the camera to the computer via USB cable, switch it on and uninstall the language patch. Then restart it and everything works perfectly again. Until now, I had only seen this phenomenon on the Sony A7R Mark 2 models. 

Since this is the current Sony firmware, the language patch should also work on other current models.

Thank you for sharing this with us.
