### ISSUE TITLE
Exception: Response code not OK: 0x2006, SONY FDR AX53, Firmware 1.02

### ISSUE THREAD

**Issue by DocM1** [ma1co/Sony-PMCA-RE#44]
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation FDR-AX53 is a camera in MTP mode

Switching to app install mode
Traceback (most recent call last):
  File "<string>", line 73, in do
  File "pmca\commands\usb.py", line 207, in installCommand
  File "pmca\commands\usb.py", line 31, in switchToAppInstaller
  File "pmca\usb\sony.py", line 180, in switchToAppInstaller
  File "pmca\usb\sony.py", line 147, in _sendCommand
  File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
  File "pmca\usb\__init__.py", line 58, in _checkResponse
Exception: Response code not OK: 0x2006

**Comment by luuziiyoo** [comment]
My axp55 is exactly the same as yours.

**Comment by ma1co** [comment]
You have to enable usb app installation first. Use the `pmca-console updatershell` command or the _Tweak_ tab in pmca-gui.

**Comment by kibo089** [comment]
SONY SLT-A58

everything goes well but the Sony a58 has a limit of 23.22min and again the recording at that limit is interrupted. I'm asking for help.
