### ISSUE TITLE
Can't find camera on mac

### ISSUE THREAD

**Issue by fisherbateman** [ma1co/Sony-PMCA-RE#460]
Keep getting the error 

> Using drivers OS-X-MSC, libusb-MTP
Looking for Sony devices
No devices found. Ensure your camera is connected. 

The camera is definitely connected, as I can access the photo files through the USB drive option on my mac, as well as being able to see it (DSC T77) in the System Information apple tab. Am I doing something wrong? Is there something else I need to do? Thanks.

**Comment by dreambold** [comment]
Did you set the USB connection mode to Mass Storage?

**Comment by fisherbateman** [comment]
> Did you set the USB connection mode to Mass Storage?

![IMG_0023 2](https://github.com/ma1co/Sony-PMCA-RE/assets/150328979/3cf959c2-cae2-482e-9693-f30a9d90938e)

I'm pretty sure it is in Mass Storage mode whenever I plug it in. Picture for reference.

**Comment by fisherbateman** [comment]
My bad, installed the drivers and it recognizes the camera now. Instead, now I get this message:

> File "/Users/travis/build/ma1co/Sony-PMCA-RE/pmca/usb/__init__.py, line 38, in _checkResponse
pmca.usb.UnknownMscException: Mass storage error: Sense 0x2 0xff 0xff

Any idea what I need to do about this? Should I start another thread since I have figured out the silly reason for my first mistake?

**Comment by anablxss** [comment]
@fisherbateman I still haven't figured out how to get the app to see the camera... how did you install the drivers??

**Comment by Pingwow** [comment]
Sorry, I also got the same message
downloaded drivers from https://www.sony.com/electronics/support/e-mount-body-ilce-1-series/ilce-1/software/00268925
Sony A7C2
```Installing com.github.ma1co.openmemories.tweak
Using drivers OS-X-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to app install mode
Traceback (most recent call last):
  File "pmca-console.py", line 99, in <module>
  File "pmca-console.py", line 73, in main
  File "pmca/commands/usb.py", line 280, in installCommand
  File "pmca/usb/sony.py", line 338, in switchToAppInstaller
  File "pmca/usb/sony.py", line 276, in _sendCommand
  File "pmca/usb/sony.py", line 95, in sendSonyExtCommand
  File "pmca/usb/__init__.py", line 44, in _checkResponse
pmca.usb.UnknownMscException: Mass storage error: Sense 0x2 0xff 0xff

**Comment by evelynmaire** [comment]
I'm having the same issue, camera is in mass storage mode, appears on my computer, but isn't detected by the app in order to run it 
ETA: drivers are installed
