### ISSUE TITLE
Sony PMCA Insufficent Permission Linux mint

### ISSUE THREAD

**Issue by TheTrueProNoob** [ma1co/Sony-PMCA-RE#470]
Hello everyone,

i'm trying to access my Sony ZV1F to be able to change the language but i always get an Insufficient permission, when i try to connect to it with the PMCA Sofware.

My linux is Mint Cinnamon 21.2 version 5.8.4.

i really want to fix this camera and i never touched a terminal of a pc in my life, maybe its just a stupid mistake but my noob eyes cant see it. 

this is what i did with the terminal 

_**kuma@kuma-Surface-Pro-3:~$ cd Sony-PMCA-RE
kuma@kuma-Surface-Pro-3:~/Sony-PMCA-RE$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Ignoring comtypes: markers 'sys_platform == "win32"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Requirement already satisfied: asn1crypto in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: axmlparserpy==0.0.4 in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.0.4)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: pycparser==2.17 in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.17)
Requirement already satisfied: pycryptodomex in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (3.19.0)
Requirement already satisfied: pyinstaller in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (6.2.0)
Requirement already satisfied: pyusb in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.2.1)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from -r requirements.txt (line 10)) (5.4.1)
Requirement already satisfied: tlslite-ng in /home/kuma/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.7.6)
Requirement already satisfied: altgraph in /home/kuma/.local/lib/python3.10/site-packages (from pyinstaller->-r requirements.txt (line 7)) (0.17.4)
Requirement already satisfied: packaging>=22.0 in /home/kuma/.local/lib/python3.10/site-packages (from pyinstaller->-r requirements.txt (line 7)) (23.2)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in /home/kuma/.local/lib/python3.10/site-packages (from pyinstaller->-r requirements.txt (line 7)) (2023.10)
Requirement already satisfied: setuptools>=42.0.0 in /usr/lib/python3/dist-packages (from pyinstaller->-r requirements.txt (line 7)) (59.6.0)
Requirement already satisfied: ecdsa in /home/kuma/.local/lib/python3.10/site-packages (from tlslite-ng->-r requirements.txt (line 11)) (0.18.0)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa->tlslite-ng->-r requirements.txt (line 11)) (1.16.0)
kuma@kuma-Surface-Pro-3:~/Sony-PMCA-RE$ ./pmca-gui.py

Loading app list
Found 11 apps

No native drivers available
Using drivers libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices
Traceback (most recent call last):
  File "/home/kuma/Sony-PMCA-RE/./pmca-gui.py", line 58, in do
    infoCommand()
  File "/home/kuma/Sony-PMCA-RE/pmca/commands/usb.py", line 234, in infoCommand
    device = getDevice(driver)
  File "/home/kuma/Sony-PMCA-RE/pmca/commands/usb.py", line 222, in getDevice
    devices = list(listDevices(driver))
  File "/home/kuma/Sony-PMCA-RE/pmca/commands/usb.py", line 179, in listDevices
    for dev, type, drv in driverList.listDevices(SONY_ID_VENDOR):
  File "/home/kuma/Sony-PMCA-RE/pmca/commands/usb.py", line 130, in listDevices
    yield dev, driver.classType, driver.openDevice(dev)
  File "/home/kuma/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 30, in openDevice
    return MscBbbDriver(backend)
  File "/home/kuma/Sony-PMCA-RE/pmca/usb/driver/generic/__init__.py", line 75, in __init__
    self.epIn = list(self._findEndpoints(self.USB_ENDPOINT_TYPE_BULK, self.USB_ENDPOINT_IN))
  File "/home/kuma/Sony-PMCA-RE/pmca/usb/driver/generic/__init__.py", line 83, in _findEndpoints
    for ep in self.backend.getEndpoints():
  File "/home/kuma/Sony-PMCA-RE/pmca/usb/driver/generic/libusb.py", line 65, in getEndpoints
    return self.dev.get_active_configuration()[(0, 0)]
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/core.py", line 921, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/core.py", line 249, in get_active_configuration
    self.managed_open()
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/backend/libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/backend/libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/kuma/.local/lib/python3.10/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)**_

thanks you for you time.

**Comment by H4ML-Aplek** [comment]
Do this in this order in the console

sudo su
sudo apt update
sudo apt install git
sudo apt install python3-tk
sudo apt install python3-pip
git clone https://github.com/ma1co/Sony-PMCA-RE
cd Sony-PMCA-RE
pip install -r requirements.txt
./pmca-gui.py


If you do this you get all permessions and no errors

**Comment by WheresPabs** [comment]
> Do this in this order in the console
> 
> sudo su sudo apt update sudo apt install git sudo apt install python3-tk sudo apt install python3-pip git clone https://github.com/ma1co/Sony-PMCA-RE cd Sony-PMCA-RE pip install -r requirements.txt ./pmca-gui.py
> 
> If you do this you get all permessions and no errors

I followed the steps without sudo, and the app worked fine. However, I received an "insufficient permissions" error when the camera was in storage mode. When I tried using the root user for my VM, it still didn’t work, and running ./pmca-gui.py resulted in an error.

`Traceback (most recent call last):
  File "/home/parallels/Sony-PMCA-RE/./pmca-gui.py", line 8, in <module>
    from pmca.commands.usb import *
  File "/home/parallels/Sony-PMCA-RE/pmca/commands/usb.py", line 11, in <module>
    from ..apk import *
  File "/home/parallels/Sony-PMCA-RE/pmca/apk/__init__.py", line 1, in <module>
    from axmlparserpy.axmlprinter import AXMLPrinter
ModuleNotFoundError: No module named 'axmlparserpy'
`
