### ISSUE TITLE
Does this work on fx30?

### ISSUE THREAD

**Issue by reicordero** [ma1co/Sony-PMCA-RE#503]
planning to buy a cheaper fx30 from Japan. Just wondering if I could tweak it with this.

**Comment by Logan-87** [comment]
Trying to figure out the same thing for my FX 30.

P. S. I'm creating a telegram group of you wanna join for this issue, since it's so hard to get the information and get in touch with the people who have successfully done it. 

Here's the link:

https://t.me/+XkprnDnLFoxlNmQ1

**Comment by Lunar-525** [comment]
No its not working on my FX30 with 4.0 firmware which bought in China mainland, it shows "
Traceback (most recent call last):
  File "pmca-gui.py", line 56, in do
  File "pmca\commands\usb.py", line 245, in infoCommand
  File "pmca\usb\sony.py", line 283, in getCameraInfo
  File "pmca\usb\sony.py", line 276, in _sendCommand
  File "pmca\usb\sony.py", line 129, in sendSonyExtCommand
  File "pmca\usb\driver\windows\wpd.py", line 167, in sendWriteCommand
  File "pmca\usb\driver\windows\wpd.py", line 139, in _send
Exception: MTP SendCommand failed: 0x-7ff8ffe1
" when Im trying to get camera info.
