### ISSUE TITLE
Fail to install app

### ISSUE THREAD

**Issue by SchenkQuan** [ma1co/Sony-PMCA-RE#52]
When I was trying to install any app to my A6300 after acquiring camera info, the pmca-gui v0.15 shown:
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Model:              ILCE-6300
Product code:       0032828270
Serial number:      05122088
Firmware version:   2.00
Lens:               Model 0x12a08019 (Firmware 1.09)

Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6300 is a camera in MTP mode

Switching to app install mode
Waiting for camera to switch...
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 74, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 255, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 58, in installApp
  File "C:\projects\sony-pmca-re\pmca\marketserver\server.py", line 61, in __init__
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 0: invalid continuation byte

and the camera has switched to the app downloading mode, but there was no app installed. 
what's going on??

**Comment by ma1co** [comment]
@SchenkQuan It seems that your hostname contains non-ascii characters. Can you open a command prompt and run `hostname`? This seems to be a python-related limitation. You might have to rename your machine...

**Comment by SchenkQuan** [comment]
Sure. The console returned Chinese characters(for I'm living in China haha) is it the reason why it's not working? I am changing the name now and the computer need to be rebooted.

**Comment by SchenkQuan** [comment]
OMG it's working! I love you more than I can say!
