### ISSUE TITLE
can someone suggest what other things to do if your device is not supported by thisss?

### ISSUE THREAD

**Issue by koyitokyo** [ma1co/Sony-PMCA-RE#533]
i tried several times only to find out that the camera is not supported, the camera is sony dsc-hx7v btww! if y'all know any other way, please do tell. thank youuu!

**Comment by VinBones** [comment]
hello. Lil story here, I managed to do this on the same camera model 2 months ago using the Dev build (pmca-gui-v0.18-22-ga82f5ba-win). Now I got another camera of the same model and it isn't working... tried it again on the tweaked one and it somehow now doesn't support it. It's either the USB or the drivers messing up... will see if I can redo what I did. Another possibility is the computer running the program too fast, read it somewhere here a while ago but can't remember the rest.

**Comment by koyitokyo** [comment]
aw, okay thank you!

**Comment by VinBones** [comment]
> aw, okay thank you!

Hey I figured it out!! :) have to use .14 dev build. Here's the file. 

[pmca-console.and.gui-v0.18-14-gd7267ea-win.zip](https://github.com/user-attachments/files/16082669/pmca-console.and.gui-v0.18-14-gd7267ea-win.zip)

![449813238_1137047147577952_138171880294504975_n](https://github.com/ma1co/Sony-PMCA-RE/assets/156333416/1450384d-78cb-4717-b1bb-c251f0fcb75b)
![448726703_980119007233401_744779147241028053_n](https://github.com/ma1co/Sony-PMCA-RE/assets/156333416/3e976db0-acce-4225-aa47-31445b2bad0d)

**Comment by koyitokyo** [comment]
THANK YOUUU! Will try later 🫶🥹

**Comment by koyitokyo** [comment]
the camera suddenly disconnects when I click the service modeee aaaa

**Comment by koyitokyo** [comment]
WAIT THANK YOU, I DID ITTT! YOU'RE A LIFESAVERRR

**Comment by VinBones** [comment]
> the camera suddenly disconnects when I click the service modeee aaaa



> WAIT THANK YOU, I DID ITTT!

no problem 😎 gotta say this camera is so nice to use also

**Comment by Shade3692** [comment]
> WAIT THANK YOU, I DID ITTT! YOU'RE A LIFESAVERRR

How did u fix this I am running into the same problem

**Comment by koyitokyo** [comment]
I used this! This is from VinBones, all credits to him. Hey I figured it out!! :) have to use .14 dev build. Here's the file.

[pmca-console.and.gui-v0.18-14-gd7267ea-win.zip](https://github.com/user-attachments/files/16082669/pmca-console.and.gui-v0.18-14-gd7267ea-win.zip) Download Zadig as well and plug your camera into your PC or Laptop and open Zadig, click options and then click list all devices. Find your camera and change the driver into libusbk, and wait for it. After that, open the the pmca gui that you downloaded. Check your camera info first then go to tweaks and click service mode. Wait until a window opens up with tickboxes in it then tick the languages. That's itt!

**Comment by koyitokyo** [comment]
After enabling it, I went back to zadig and changed the driver into the windows one just to be safe!

**Comment by Shade3692** [comment]
> I used this! This is from VinBones, all credits to him. Hey I figured it out!! :) have to use .14 dev build. Here's the file.
> 
> [pmca-console.and.gui-v0.18-14-gd7267ea-win.zip](https://github.com/user-attachments/files/16082669/pmca-console.and.gui-v0.18-14-gd7267ea-win.zip) Download Zadig as well and plug your camera into your PC or Laptop and open Zadig, click options and then click list all devices. Find your camera and change the driver into libusbk, and wait for it. After that, open the the pmca gui that you downloaded. Check your camera info first then go to tweaks and click service mode. Wait until a window opens up with tickboxes in it then tick the languages. That's itt!

I did everything and followed the steps but each time it gives me this:

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to service mode
Traceback (most recent call last):
  File "pmca\usb\driver\generic\libusb.py", line 79, in read
  File "usb\core.py", line 1034, in read
  File "usb\backend\libusb0.py", line 558, in bulk_read
  File "usb\backend\libusb0.py", line 697, in __read
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pmca-gui.py", line 117, in do
  File "pmca-gui.py", line 152, in start
  File "pmca\commands\usb.py", line 669, in senserShellCommand
  File "pmca\usb\sony.py", line 920, in authenticate
  File "pmca\usb\sony.py", line 914, in _sendAuthPacket
  File "pmca\usb\driver\generic\__init__.py", line 94, in read
  File "pmca\usb\driver\generic\libusb.py", line 81, in read
pmca.usb.driver.generic.GenericUsbException

After a bit I think at one point it did show me the boxes but for the languages it said 1/35 and when clicked it gave me that same message above. I don't know how to fix it.

**Comment by Shade3692** [comment]
I got it to work after a bit. Thank you so much for you help. You a real one

**Comment by koyitokyo** [comment]
You're welcome!

**Comment by Nebulater** [comment]
> > I used this! This is from VinBones, all credits to him. Hey I figured it out!! :) have to use .14 dev build. Here's the file.
> > [pmca-console.and.gui-v0.18-14-gd7267ea-win.zip](https://github.com/user-attachments/files/16082669/pmca-console.and.gui-v0.18-14-gd7267ea-win.zip) Download Zadig as well and plug your camera into your PC or Laptop and open Zadig, click options and then click list all devices. Find your camera and change the driver into libusbk, and wait for it. After that, open the the pmca gui that you downloaded. Check your camera info first then go to tweaks and click service mode. Wait until a window opens up with tickboxes in it then tick the languages. That's itt!
> 
> I did everything and followed the steps but each time it gives me this:
> 
> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific Looking for Sony devices
> 
> Querying mass storage device Sony DSC is a camera in mass storage mode
> 
> Switching to service mode Traceback (most recent call last): File "pmca\usb\driver\generic\libusb.py", line 79, in read File "usb\core.py", line 1034, in read File "usb\backend\libusb0.py", line 558, in bulk_read File "usb\backend\libusb0.py", line 697, in __read File "usb\backend\libusb0.py", line 447, in _check usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "pmca-gui.py", line 117, in do File "pmca-gui.py", line 152, in start File "pmca\commands\usb.py", line 669, in senserShellCommand File "pmca\usb\sony.py", line 920, in authenticate File "pmca\usb\sony.py", line 914, in _sendAuthPacket File "pmca\usb\driver\generic__init__.py", line 94, in read File "pmca\usb\driver\generic\libusb.py", line 81, in read pmca.usb.driver.generic.GenericUsbException
> 
> After a bit I think at one point it did show me the boxes but for the languages it said 1/35 and when clicked it gave me that same message above. I don't know how to fix it.

I'm trying to do this with an A6700, and I'm getting this:

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying mass storage device
Traceback (most recent call last):
  File "pmca\usb\driver\generic\libusb.py", line 85, in write
  File "usb\core.py", line 986, in write
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 229, in setup_request
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 178, in managed_claim_interface
  File "usb\backend\libusb0.py", line 537, in claim_interface
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [claim_interface] could not claim interface 0, win error: Cannot create a file when that file already exists.\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pmca-gui.py", line 117, in do
  File "pmca-gui.py", line 152, in start
  File "pmca\commands\usb.py", line 660, in senserShellCommand
  File "pmca\commands\usb.py", line 222, in getDevice
  File "pmca\commands\usb.py", line 184, in listDevices
  File "pmca\usb\__init__.py", line 26, in __init__
  File "pmca\usb\__init__.py", line 50, in reset
  File "pmca\usb\driver\generic\__init__.py", line 138, in sendCommand
  File "pmca\usb\driver\generic\__init__.py", line 118, in _writeCommand
  File "pmca\usb\driver\generic\__init__.py", line 97, in write
  File "pmca\usb\driver\generic\libusb.py", line 87, in write
pmca.usb.driver.generic.GenericUsbException

What did you do that helped your situation? It's a different camera but I'm hoping it might work...

**Comment by Nebulater** [comment]
I managed to get the window for the language to open but when I click it I get:

Waiting for camera to switch...
Found a camera in service mode
Authenticating
Traceback (most recent call last):
  File "pmca-gui.py", line 184, in do
  File "pmca\platform\tweaks.py", line 179, in setEnabled
  File "pmca\platform\tweaks.py", line 54, in setEnabled
  File "pmca\platform\backup.py", line 78, in writeProp
  File "pmca\platform\backup.py", line 49, in write
  File "pmca\platform\backup.py", line 34, in write
  File "pmca\platform\backend\senser.py", line 32, in writeBackup
  File "pmca\usb\sony.py", line 1041, in writeBackup
  File "pmca\usb\sony.py", line 993, in _sendAdjustControlPacket
Exception: Senser adjust control error 129

**Comment by koyitokyo** [comment]
https://www.youtube.com/watch?v=BJhheKXs39A

try following this step by step video 😁 let me know if it works or not

**Comment by blackcatfrom92** [comment]
Hi everyone,

I have been using the PMCA hack since the past few years, never had a single problem, was working top notch.
Then, one day, I noticed the Sony Alpha 7s camera not being able to record over 24min of video.
I have then tried several times to delete, then reinstall the PMCA application with Open Memories Tweak, no success, my camera is still blocked with the original 24min record limit.

Could someone please help me out or give me any advice on something I might be doing wrong?

Thanks to all.
Cheers.

Flo
