### ISSUE TITLE
Enhancement: Confirm that RX100M7 can be used to unlock the language but still buggy

### ISSUE THREAD

**Issue by ws2bhhh** [ma1co/Sony-PMCA-RE#538]
Version: v0.18 [a82f5ba](https://github.com/ma1co/Sony-PMCA-RE/commit/a82f5baaa8e9c3d9f28f94699e860fb2e48cc8e0), using github workflow to build
OS: Windows 11
Driver: **Zadig 2.9.788, libusbK**

The tweaks isn't perfect: when I "slide" over unavailable languages in the language menu, the camera UI reboot. 
Related commit: https://github.com/ma1co/Sony-PMCA-RE/pull/356

**Comment by charoducer** [comment]
oh, plz help me

**Comment by charoducer** [comment]
I am an rx user living in Korea. What did you do with this camera that was locked in English?

**Comment by charoducer** [comment]
@ma1co plz help me
Traceback (most recent call last):
  File "pmca-gui.py", line 184, in do
  File "pmca\platform\tweaks.py", line 179, in setEnabled
  File "pmca\platform\tweaks.py", line 54, in setEnabled
  File "pmca\platform\backup.py", line 78, in writeProp
  File "pmca\platform\backup.py", line 49, in write
  File "pmca\platform\backup.py", line 34, in write
  File "pmca\platform\backend\senser.py", line 32, in writeBackup
  File "pmca\usb\sony.py", line 1041, in writeBackup
  File "pmca\usb\sony.py", line 993, in _sendAdjustControlPacket
Exception: Senser adjust control error 129
What does this mean?

**Comment by ws2bhhh** [comment]
> @ma1co plz help me Traceback (most recent call last): File "pmca-gui.py", line 184, in do File "pmca\platform\tweaks.py", line 179, in setEnabled File "pmca\platform\tweaks.py", line 54, in setEnabled File "pmca\platform\backup.py", line 78, in writeProp File "pmca\platform\backup.py", line 49, in write File "pmca\platform\backup.py", line 34, in write File "pmca\platform\backend\senser.py", line 32, in writeBackup File "pmca\usb\sony.py", line 1041, in writeBackup File "pmca\usb\sony.py", line 993, in _sendAdjustControlPacket Exception: Senser adjust control error 129 What does this mean?

Unfortunately, my camera originally was locked to Japanese. Now this camera can be set to English, which is good enough for me.
Maybe it has something to do with a wrong driver selection. I use libusbK. 
What is your specific camera model, PMCA and Zadig version? This helps to solve the problem.

**Comment by CE560** [comment]
@ws2bhhh i'm also trying to language unlock a RX100M7, but im having issues with v0.18-22-ga82f5ba build on windows 11. What do you mean built using github workflows?

I am using Zadig 2.9.788 libusb0 v1.4.0.0

When I try the camera in MTP mode and PMCA tweaking mode in updater I get this message:

_Querying MTP device
Sony Corporation DSC-RX100M7 is a camera in MTP mode

Model:              DSC-RX100M7
Product code:       0080818800
Serial number:      00027567
Firmware version:   1.00

Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices

Querying MTP device
Sony Corporation DSC-RX100M7 is a camera in MTP mode

Getting device info
Using firmware for model DSC-RX100M7

Error: Model "DSC-RX100M7" does not support custom firmware updates. Please check the compatibility list._

When I use mass storage mode (also with libusb0 driver installed) to try to enter service mode it appears PMCA does not see the camera even though Zadig does it gives me this:

_Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
Looking for Sony devices
Traceback (most recent call last):
  File "pmca-gui.py", line 58, in do
  File "pmca\commands\usb.py", line 234, in infoCommand
  File "pmca\commands\usb.py", line 222, in getDevice
  File "pmca\commands\usb.py", line 179, in listDevices
  File "pmca\commands\usb.py", line 130, in listDevices
  File "pmca\usb\driver\generic\libusb.py", line 30, in openDevice
  File "pmca\usb\driver\generic\__init__.py", line 75, in __init__
  File "pmca\usb\driver\generic\__init__.py", line 83, in _findEndpoints
  File "pmca\usb\driver\generic\libusb.py", line 65, in getEndpoints
  File "usb\core.py", line 921, in get_active_configuration
  File "usb\core.py", line 113, in wrapper
  File "usb\core.py", line 255, in get_active_configuration
usb.core.USBError: [Errno None] Configuration not set_

I was able to get it to see the camera once and got it into service mode by installing the libusb0 drivers on the "sony usb device" but in PMCA it said that no services were available for this model.

any idea how to fix this? I would really love to unlock the menu languages rather than trying to sell this one and try to find someone that will ship a US model to Japan. Thanks!

**Comment by ws2bhhh** [comment]
> @ws2bhhh i'm also trying to language unlock a RX100M7, but im having issues with v0.18-22-ga82f5ba build on windows 11. What do you mean built using github workflows?

@CE560 I forked the project, and then modified the workflow file in my fork to run the build action manually. It is hard to discribe how to do this.
The link to the workflow file I edited is: https://github.com/ma1co/Sony-PMCA-RE/tree/master/.github/workflows
> I am using Zadig 2.9.788 libusb0 v1.4.0.0

Try **libusbK**. In my situation the other driver just reboots the camera and makes no changes. Trying different drivers or replacing the cable might help, I think.

**Comment by Rexaz** [comment]
Itis work for me on RX100M6.
Thank you.

**Comment by Derfro22** [comment]
Hello, does it work on the RX100M7 now?
Thank you so much :))

**Comment by CE560** [comment]
> Hello, does it work on the RX100 VII now? Thank you so much :))

Confirmed working on the Mk7, but only on MacOS by building a git clone in the command shell (I have a M1 MacBook Pro but I don't think it will matter which model), then opening the GUI with a command prompt. I was able to unlock all languages from a Japanese market model locked to Japanese. I didn't try any other features of the program. Follow directions here:

https://github.com/ma1co/Sony-PMCA-RE/issues/528

It likely works just as well through Linux if you were to have a base Linux OS installed and installed via a command prompt git clone, however it did not work with Linux as a VM on MacOS or Windows 11. Through the VM all drivers were installed and it saw the camera and all appeared okay, but it would crash when trying to save the language unlock in the camera. I was unable to get it to work at all through the windows .exe on windows 10 or 11, I tried like 5 different versions.

**Comment by Derfro22** [comment]
Hello @CE560 , thank you so much for your quick reply! By any chance, are you in Tokyo right now? 🥲 I have a friend there, but he doesn’t have a computer or programming knowledge. However, he would really like to buy this camera and set it up in English.
Thanks :))

**Comment by charoducer** [comment]
Oh wow, so many responses! Thank you all so much!

Actually, I made a huge mistake back then.
I was supposed to install a file on my RX100M7, but I somehow ended up installing it on a wireless mouse hub instead.

As a result, I had no choice but to throw away the mouse.
But thanks to the instructions on GitHub, I managed to fix everything, and now I can even use Korean!
(Though in the end, my company needed a better camera, so I had to take on a part-time job and painfully upgrade to a Sony A7C2.)

Time has passed since then—back in those days, I had to rely on Google Translate,
but now we live in a world where I can conveniently use ChatGPT for translation.

Thank you all!

**Comment by ws2bhhh** [comment]
> It likely works just as well through Linux if you were to have a base Linux OS installed and installed via a command prompt git clone, however it did not work with Linux as a VM on MacOS or Windows 11. Through the VM all drivers were installed and it saw the camera and all appeared okay, but it would crash when trying to save the language unlock in the camera. I was unable to get it to work at all through the windows .exe on windows 10 or 11, I tried like 5 different versions.

Glad to hear that! I was wondering if you could set the camera language to the language in the lower half of the language selection list? I can't “slide over” some of the languages after unlocking to check the languages in the bottom half of the language selection list, especially the ones that are written from right to left. My RX100M7 reboots whenever I try to do this😥

**Comment by kishontilaci** [comment]
It works. Just bought an RX100M7 (RX100 VII) in Japan.
Using my Mac (Tahoe 26.0.1) in terminal, I just copied the youtube video example commands (which used linux):

clone https://github.com/ma1co/Sony-PMCA-RE
cd Sony-PMCA-RE
pip3 install -r requirements.txt
python3 ./pmca-gui.py

Start tweaking only worked in service mode. Make sure to have libusb installed (brew install libusb).

**Comment by rsk1977g-sys** [comment]
I also found this YouTube video claiming to change the language on RX100 M7 (https://www.youtube.com/watch?v=WM_PoshgLPY
).
However, I tried the same steps with my Japanese version (DSC-RX100M7 JPN) and it did not work — the camera either shows "unknown device" or ignores the tweak.
Does anyone know if this method only works for non-Japanese firmware?

**Comment by ws2bhhh** [comment]
> I also found this YouTube video claiming to change the language on RX100 M7 (https://www.youtube.com/watch?v=WM_PoshgLPY ). However, I tried the same steps with my Japanese version (DSC-RX100M7 JPN) and it did not work — the camera either shows "unknown device" or ignores the tweak. Does anyone know if this method only works for non-Japanese firmware?

Of course not. My camera is also a JPN model.
