### ISSUE TITLE
plz help me (sony rx100m7 language unlock,)

### ISSUE THREAD

**Issue by charoducer** [ma1co/Sony-PMCA-RE#554]
~You may sound weird because you use a translator~

Hello, I'm an ordinary office worker in Korea, rx100m7 user

I bought a secondhand rx100m7 yesterday
The seller bought this camera in the UK and was told that no language other than English was allowed

So I studied about pmca since yesterday. I was lucky enough to find gd7267ea-win, and I've gone all the way to the photographic stage

However, it automatically releases when you press the unlock all languages button
I know a lot of users are getting help from the hard work of people here. Finally, I'd like to ask if there's a person who can help me with this situation
![2024-08-17 14 33 38](https://github.com/user-attachments/assets/84ac7844-4070-4fc6-a87c-af296d62aa05)

This is the error code

Traceback (most recent call last):
  File "pmca-gui.py", line 184, in do
  File "pmca\platform\tweaks.py", line 179, in setEnabled
  File "pmca\platform\tweaks.py", line 54, in setEnabled
  File "pmca\platform\backup.py", line 78, in writeProp
  File "pmca\platform\backup.py", line 49, in write
  File "pmca\platform\backup.py", line 34, in write
  File "pmca\platform\backend\senser.py", line 32, in writeBackup
  File "pmca\usb\sony.py", line 1041, in writeBackup
  File "pmca\usb\sony.py", line 993, in _sendAdjustControlPacket
Exception: Senser adjust control error 129

**Comment by Sujygunsmoke** [comment]
contact my email , i can help
sujygunsmoke@gmail.com

**Comment by yugengliu1030** [comment]
mine is RX100M6 having the same error 129,using pmca 0.18-14. and shows no tweaks in other version such as 0.18-18, 0.22. anyone can help with me? my email address: yugeng_liu@live.cn
