### ISSUE TITLE
Mass Storage Error with Sony HDR-XR520V

### ISSUE THREAD

**Issue by titlefightfan5** [ma1co/Sony-PMCA-RE#560]
When I press _Get camera info_, I get this:

> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode
> 
> Traceback (most recent call last):
>   File "pmca-gui.py", line 56, in do
>   File "pmca\commands\usb.py", line 245, in infoCommand
>   File "pmca\usb\sony.py", line 283, in getCameraInfo
>   File "pmca\usb\sony.py", line 276, in _sendCommand
>   File "pmca\usb\sony.py", line 95, in sendSonyExtCommand
>   File "pmca\usb\__init__.py", line 42, in _checkResponse
> pmca.usb.InvalidCommandException: Mass storage error: Sense 0x5 0x20 0x0
> 

And when I try to start tweaking, I get this:

> Using drivers Windows-MSC, Windows-MTP, Windows-vendor-specific, libusb-MSC, libusb-MTP, libusb-vendor-specific
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode
> 
> Getting device info
> Error: Cannot determine camera model

I've tried replacing the driver using Zadig to _libusb-win32_, but that did not change anything. I'm on windows trying to unlock all languages. Any advice on how to proceed?

**Comment by Sujygunsmoke** [comment]
contact my email, i can help
sujygunsmoke@gmail.com

**Comment by zane4004** [comment]
Did you ever fix this? Im running into the same problem
