### ISSUE TITLE
Sony A7IV: cannot change language

### ISSUE THREAD

**Issue by UmbaSimpy** [ma1co/Sony-PMCA-RE#582]
Hi guys.

I'm trying to change language on a Sony A7 IV bought in Japan. (firmware is 4.0)
I can set the device in service mode, and with the latest dev build I get to this point and after I selecting anything it freezes and does nothing:
![image](https://github.com/user-attachments/assets/26106746-eb67-42cb-9c37-fdb2ce6ad905)

Error is as follows:

> Querying mass storage device
Sony DSC is a camera in mass storage mode

Switching to service mode

Waiting for camera to switch...
Found a camera in service mode
Authenticating
Traceback (most recent call last):
  File "pmca\usb\driver\generic\libusb.py", line 79, in read
  File "usb\core.py", line 1034, in read
  File "usb\backend\libusb0.py", line 558, in bulk_read
  File "usb\backend\libusb0.py", line 697, in __read
  File "usb\backend\libusb0.py", line 447, in _check
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pmca-gui.py", line 184, in do
  File "pmca\platform\tweaks.py", line 179, in setEnabled
  File "pmca\platform\tweaks.py", line 54, in setEnabled
  File "pmca\platform\backup.py", line 78, in writeProp
  File "pmca\platform\backup.py", line 49, in write
  File "pmca\platform\backup.py", line 34, in write
  File "pmca\platform\backend\senser.py", line 32, in writeBackup
  File "pmca\usb\sony.py", line 1041, in writeBackup
  File "pmca\usb\sony.py", line 991, in _sendAdjustControlPacket
  File "pmca\usb\sony.py", line 857, in sendSenserPacket
  File "pmca\usb\driver\generic\__init__.py", line 94, in read
  File "pmca\usb\driver\generic\libusb.py", line 81, in read
pmca.usb.driver.generic.GenericUsbException
Cannot sync backup
Done

Does anybody know how to do it?

**Comment by LeMouth** [comment]
try with pmca 0.18-22 version
