### ISSUE TITLE
usb.core.USBError error message on OSX

### ISSUE THREAD

**Issue by mattijsf** [ma1co/Sony-PMCA-RE#6]
When executing `./pmca-v0.3-osx install -o outfile.txt` I get the following error message:

```bash
./pmca-v0.3-osx install -o outfile.txt
Using libusb
Looking for Sony devices
Traceback (most recent call last):
  File "<string>", line 170, in <module>
  File "<string>", line 164, in main
  File "<string>", line 76, in installCommand
  File "pmca/usb/driver/libusb.py", line 35, in listDevices
  File "usb/core.py", line 875, in get_active_configuration
  File "usb/core.py", line 102, in wrapper
  File "usb/core.py", line 242, in get_active_configuration
usb.core.USBError: [Errno None] Configuration not set
pmca returned -1
```

Any clue what is going on? I got it working fine on a windows machine but just not on my (development) Macbook. 

I have to add that the https://playmemoriescameraapps.com also doesn't play nice together with the A6000 on my mac (tried with Safari) and I did install the plugin `.pkg` and restarted my Mac. But it just fails to switch the camera into 'Download mode' The error is likely related but maybe you can help me out pinpointing what it could be.

For what it's worth I'm running:
OSX: El Capitan (10.11.4 (15E65))
libusb: stable 1.0.20
A6000: v3.10

**Comment by mattijsf** [comment]
Maybe worth mentioning: I'm looking into the possibility to build a (bulk) one-way FTP sync app. I know there is a stub framework available but it would be great to run it on the actual camera when testing / debugging (on my mac).

**Comment by ma1co** [comment]
I made some changes to the device scan code. Can you try the latest release (v0.4)? If it still doesn't work, try switching between MTP / mass storage mode on your camera.

**Comment by mattijsf** [comment]
I'm currently running from source against `master` that includes your last 0.4 changes.

It works better now, but still not as expected.

`$ python pmca.py install -o outfile.txt`

```bash
Using libusb
Looking for Sony devices

Querying MTP device
Sony Corporation ILCE-6000 is a camera in MTP mode
Switching to app install mode. Please run this command again when the camera has switched modes.
$
```

_Camera switches correctly into 'Application Download' mode_

`$ python pmca.py install -o outfile.txt`

```bash
Using libusb
Looking for Sony devices
No devices found. Ensure your camera is connected.
$
```

I get the same results using the 0.4 binary release.

**Comment by mattijsf** [comment]
That was in `MTP` mode btw. This is was I get when I put the camera in `Mass Storage` mode:

`$ python pmca.py install -o outfile.txt`

```bash
Using libusb
Looking for Sony devices

Querying mass storage device
Traceback (most recent call last):
  File "pmca.py", line 172, in <module>
    main()
  File "pmca.py", line 166, in main
    installCommand(args.server, args.driver, args.apkFile, args.outFile)
  File "pmca.py", line 88, in installCommand
    info = MscDevice(drv).getDeviceInfo()
  File "/Users/mattijs/Development/sandbox/git/Sony-PMCA-RE/pmca/usb/__init__.py", line 17, in __init__
    self.reset()
  File "/Users/mattijs/Development/sandbox/git/Sony-PMCA-RE/pmca/usb/__init__.py", line 25, in reset
    self.driver.sendCommand(6 * '\x00')
  File "/Users/mattijs/Development/sandbox/git/Sony-PMCA-RE/pmca/usb/driver/libusb.py", line 98, in sendCommand
    self._writeCommand(self.DIRECTION_WRITE, command, 0)
  File "/Users/mattijs/Development/sandbox/git/Sony-PMCA-RE/pmca/usb/driver/libusb.py", line 88, in _writeCommand
    command = command.ljust(16, '\x00'),
  File "/Users/mattijs/Development/sandbox/git/Sony-PMCA-RE/pmca/usb/driver/libusb.py", line 72, in write
    return self.dev.write(self.epOut, data)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/Library/Python/2.7/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/Library/Python/2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
$
```

**Comment by mattijsf** [comment]
There some info about the `[Errno 13] Access denied (insufficient permissions)` error here: https://bitbucket.org/benallard/galileo/issues/60/no-backend-available-when-running-on-mac

Seems like an OSX kernel driver is claiming the device in Mass Storage mode and therefore pmca can't use it. I tried unmounting everything but that doesn't help. Elevating permissions with sudo also does not help.

My best bet would be to get it working in MTP mode... don't know how though.

**Comment by mattijsf** [comment]
Closing. Restarting my Mac fixed the last mentioned MTP mode issue. There are some quirks with the connection though. But at least I'm now getting a populated `outfile`. I'll create new issue(s) for the other problems I see if you don't mind.

Thank you for your support!

**Comment by ma1co** [comment]
That's a bit weird that your camera did't show up after switching... Probably an OS X issue, not much I can do there... Good that it works now.

Concerning mass storage mode: I guess it's a kernel driver or something. Can you try to run `kextstat` before and after plugging in the camera? Is there a new driver being loaded? Try to unload it with `kextunload -b com.apple.driver.thedrivername`
