### ISSUE TITLE
HDR-AS300 support

### ISSUE THREAD

**Issue by whoever42** [ma1co/Sony-PMCA-RE#65]
How can I create fdat files for new cameras? I don't see HDR-AS300 on the list, however, it's technically almost the same camera as FDR-X3000, which is supported.

**Comment by mungewell** [comment]
Same(ish) question asked here:
https://github.com/ma1co/fwtool.py/issues/7

@ma1co said "bug him for instructions" (paraphrased ;-)

**Comment by ma1co** [comment]
@whoever42 Exactly. If you own the AS300, please tell me so we can work on a solution.

**Comment by whoever42** [comment]
oh, somehow missed your reply.
@ma1co yes, I do own AS300

**Comment by ma1co** [comment]
As a first step, we'd have to dump the AS300 firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x61010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1738472/0x61010000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x61010000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by whoever42** [comment]
Will RPi work?

> No native drivers available
> Using drivers libusb-MSC, libusb-MTP
> Looking for Sony devices
> 
> Querying mass storage device
> Sony Camcorder is a camera in mass storage mode
> 
> Trying 100 firmware images
> Firmware update error: Invalid version
> Success: Found matching file: gen3_0x61010035_0.dat

pmca-console.py info

> Model:              HDR-AS300

how do I make respective fdat/hdr files for updatershell?

**Comment by ma1co** [comment]
Thank you, the AS300 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Connect the camera.
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware (this will take some time to complete): `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by sony-l** [comment]
@ ma1co 
Using drivers Windows-MSC, Windows-MTP
Looking for Sony devices

Querying mass storage device
Sony Camcorder is a camera in mass storage mode

Trying 100 firmware images
Firmware update error: Invalid region
Success: Found matching file: gen3_0x61010032_0.dat

how do i dump the firmware?

**Comment by ma1co** [comment]
@sony-l Which camera model?

**Comment by sony-l** [comment]
@ ma1co cx680

**Comment by sony-l** [comment]
@ ma1co I write the wrong firmware,then,my cx680 can not exit the updatermode.

**Comment by ma1co** [comment]
@sony-l The region parameter is still invalid. Please download [0x61010000_1.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1748930/0x61010000_1.zip) and run the command for the new zip file: `pmca-console guess_firmware -f 0x61010000_1.zip`

**Comment by sony-l** [comment]
@ ma1co
Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen3_0x61010032_1.dat

**Comment by ma1co** [comment]
@sony-l Thanks, the CX680 is now supported. Can you dump the firmware according to my post above and upload it to the dropbox link?

**Comment by sony-l** [comment]
Great, I will upload it later

**Comment by sony-l** [comment]
@ma1co  I can not get it back to normal mode after dump

**Comment by ma1co** [comment]
@sony-l Typing `exit` does not work? In the worst case, you can remove the battery.

**Comment by sony-l** [comment]
@ma1co I have type exit. But it do not work. remove the battery,the same.

**Comment by ma1co** [comment]
@sony-l What happens? Just a black screen? Does it connect over USB?

**Comment by sony-l** [comment]
@ma1co  led is on. black screen, can connect over USB, updatermode

**Comment by ma1co** [comment]
@sony-l Running `pmca-console updatershell -m HDR-CX680` should bring you back to the updater shell. Can you post the output of `shell ls -lR /setting`

**Comment by sony-l** [comment]
@ma1co  Sony Camcorder is a camera in updater mode

Initializing firmware update
Writing firmware
0%
100%
Starting updater shell...

Welcome to the USB debug shell.
Type `help` for the list of supported commands.
Type `exit` to quit.
>exit
Done
The camera do not reboot

**Comment by ma1co** [comment]
@sony-l Again, please post the output of `shell ls -lR /setting`

**Comment by sony-l** [comment]
@ma1co  setting:
-rw-r--r--    1 0        0          711673 Jan  1 00:03 Backup.bak
-rw-r--r--    1 0        0          711673 Jan  1 00:03 Backup.bin
-rw-r--r--    1 0        0           81838 Jan  1 00:00 DmmConfig.bin
drwxr-xr-x    2 0        0           16384 Jan  1 00:00 appfw_infra
drwxrwxrwx    2 0        0           16384 Jan  1  1980 gps
-rw-r--r--    1 0        0         1350656 Jan  1 00:00 init_bk.bak
-rw-r--r--    1 0        0            1632 Jan  1 00:00 kemco.txt
drwxrwxrwx    2 0        0           16384 Jan  1  1980 mode
-rw-r--r--    1 0        0            3612 Jan  1 00:00 ulogio.bin
drwxr-xr-x    2 0        0           16384 Jan  1  1980 updater

/setting/appfw_infra:

/setting/gps:

/setting/mode:

/setting/updater:
-r--r--r--    1 0        0               2 Jan  1 00:01 dat4
-rw-r--r--    1 0        0               0 Jan  1  1980 mode

**Comment by ma1co** [comment]
@sony-l Please try `shell rm /setting/updater/mode` and then `exit`

**Comment by sony-l** [comment]
@ma1co It is back to the normal mode

**Comment by sony-l** [comment]
@ma1co  how do i updater the firmware?

**Comment by ma1co** [comment]
@sony-l Please upload the firmware dump to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

**Comment by sony-l** [comment]
@ma1co  any another way to upload? I must use the vpn . It is slowly

**Comment by ma1co** [comment]
@sony-l Feel free to upload it somewhere else and post a link.

**Comment by sony-l** [comment]
@ma1co  Is these some way change ntsc to pal？

**Comment by whoever42** [comment]
@ma1co sent the dump files finally (RPi couldn't handle dumping nflasha, so I had to pull a normal computer out)

Btw, any hints on how to make permanent changes to the filesystem? Any changes I make to **d**nflasha partitions dissapear within seconds. I managed to install apps on X3000 (https://github.com/ma1co/Sony-PMCA-RE/issues/60) but can't launch them, since the screen doesn't provide such options.

**Comment by ma1co** [comment]
@whoever42 Thanks for the dump! I'm currently making progress on launching apps on the action cam. I'll update you if I have something working reliably.

@sony-l It would be great if you could send me the dump somehow. The CX680 might even support android, but I'm not sure, I'll have to have a look at the firmware dump.

**Comment by whoever42** [comment]
@ma1co nice to hear and I'm also ok with trying/testing if it's not reliable yet

**Comment by sony-l** [comment]
@ma1co  I can not open your dropbox link

**Comment by sony-l** [comment]
@ma1co  https://pan.baidu.com/s/1dGN24yl    password：cd2k

**Comment by ma1co** [comment]
@sony-l Thanks a lot!

**Comment by sony-l** [comment]
@ma1co  I have pj670 ,pj675. It is almost the same. How can I add these model?

**Comment by ma1co** [comment]
@sony-l For the PJ675, please repeat the procedure described in my [comment](#issuecomment-366823727) above (using 0x61010000.zip). For the PJ670, please do the same but using [0x51010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1804032/0x51010000.zip).

**Comment by sony-l** [comment]
@ma1co  
add this model, thanks.
fdat:
  isAccessory: false
  model: 0x41040012
  region: 0
  version: '2.00'

**Comment by ma1co** [comment]
@sony-l Please tell me the model name and the generation.

**Comment by sony-l** [comment]
@ma1co   gen3   HXR-NX3

**Comment by ma1co** [comment]
@sony-l 
Professional video cameras are currently not included. But you can try this file: [NX3.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1891523/NX3.zip). Download and unpack it. You can then run updatershell like this:
`pmca-console updatershell -f NX3.dat`

Btw, did you have any luck with the PJ670 / PJ675?

**Comment by ma1co** [comment]
@whoever42 
Here's how to replace the live streaming app by a custom launcher:
* Update the Sony-PMCA-RE repository or download the newest windows development build [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts)
* Download the [launcher apk](https://github.com/ma1co/OpenMemories-Launcher/releases/latest)
* Run `pmca-console updatershell`
* Install the apk: `install OpenMemories-Launcher-release-1.0.apk`
* Enable usb app installation `tweak`, select the corresponding item and enter `0` to exit
* Exit the updater mode: `exit`
* Configure the Ustream settings as described [here](http://helpguide.sony.net/cam/1640/v1/en/contents/TP0000912428.html) (sorry, you need a Ustream account for now).
* Switch the camera to live streaming mode

**Comment by mungewell** [comment]
BTW didn't we figure out how to pull/push/adjust the Ustream settings in via pcma-console. ;-)
ma1co/Sony-PMCA-RE#53

You might be able to get by with fake credentials (ie not actually need a Ustream account), that would normally be validated by the official PC configure process.

**Comment by whoever42** [comment]
@ma1co got the launcher running (I used latest 2.0 version) as per your instructions on X3000.
I also installed PMCADemo app and OpenMemories-Tweak (this one gives telnet access, right?). 
OpenMemories Tweak app terminates immediately.
PMCADemo launches, but I'm unable to select/see anything, so have to restart camera.
"PlayMemories Camera Apps" menu connects camera to wifi, but there are no network services available, adb or telnet. (and I can get back to previous Launcher view by pressing Menu button on camera).

**Comment by ma1co** [comment]
@whoever42 Currently, the launcher is the only app compatible with action cams. Other apps have to be modified to support the tiny display and limited buttons.

**Comment by sony-l** [comment]
@ma1co   https://pan.baidu.com/s/12dl01o5PgqljVjDBisjyBw 密码：oqi3

**Comment by ma1co** [comment]
@sony-l Thank you for the HDR-PJ675 dump. If you need any help with other cameras, please let me know.

**Comment by sony-l** [comment]
@ma1co  I want to send you a software used by sony factory .But it can not share to all. Maybe,some help for your project. Any other way to contact you ?

**Comment by sony-l** [comment]
@ma1co 
Getting device info
Using firmware for model HDR-CX680

Initializing firmware update
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 82, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 360, in updaterShellCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 373, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 527, in checkGuard
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 501, in _sendWriteCommands
Exception: Firmware update error: Invalid region
[6780] Failed to execute script pmca-console

How do I change region?

**Comment by sony-l** [comment]
@ma1co  
Querying MTP device
Sony Corporation FDR-AX45 is a camera in MTP mode

Initializing firmware update
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in <module>
  File "C:\projects\sony-pmca-re\pmca-console.py", line 82, in main
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 360, in updaterShellCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 373, in firmwareUpdateCommandInternal
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 527, in checkGuard
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 501, in _sendWriteCommands
Exception: Firmware update error: Invalid model
[13452] Failed to execute script pmca-console

**Comment by sony-l** [comment]
@ma1co 0x71010096   0117128

**Comment by ma1co** [comment]
@sony-l I don't understand, please tell me what you're doing.
You have already sent me a dump for the CX680, why doesn't it work anymore?
What do you mean by 0x71010096 0117128?????
Btw, did you have any luck with the PJ670?

**Comment by ma1co** [comment]
@sony-l For the AX45, you can try this file: [71010000_1.zip](https://github.com/ma1co/Sony-PMCA-RE/files/2149552/71010000_1.zip). Please send me the full output.

**Comment by sony-l** [comment]
@ma1co  
@ma1co
Getting device info
Using firmware for model HDR-CX625

Initializing firmware update
Traceback (most recent call last):
File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in 
File "C:\projects\sony-pmca-re\pmca-console.py", line 82, in main
File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 360, in updaterShellCommand
File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 373, in firmwareUpdateCommandInternal
File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 527, in checkGuard
File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 501, in _sendWriteCommands
Exception: Firmware update error: Invalid region
[6780] Failed to execute script pmca-console

How do I change region?  not  cx680, it is cx625

**Comment by sony-l** [comment]
@ma1co   
Trying 100 firmware images
Firmware update error: Invalid version
Success: Found matching file: gen3_0x71010096_1.dat

**Comment by sony-l** [comment]
@ma1co   I rename the cx680 hdr file,and get massages below.
Getting device info
Using firmware for model HDR-CX625

Initializing firmware update
Traceback (most recent call last):
File "C:\projects\sony-pmca-re\pmca-console.py", line 96, in
File "C:\projects\sony-pmca-re\pmca-console.py", line 82, in main
File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 360, in updaterShellCommand
File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 373, in firmwareUpdateCommandInternal
File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 527, in checkGuard
File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 501, in _sendWriteCommands
Exception: Firmware update error: Invalid region
[6780] Failed to execute script pmca-console

How do I change region? not cx680, it is cx625
