### ISSUE TITLE
sony ILCE-9 support

### ISSUE THREAD

**Issue by downloader8** [ma1co/Sony-PMCA-RE#83]
I try to run PMCA on  ILCE-9. There is error above
Switching to app install mode
Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 74, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 238, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 34, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 306, in switchToAppInstaller
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 244, in _sendCommand
  File "C:\projects\sony-pmca-re\pmca\usb\sony.py", line 98, in sendSonyExtCommand
  File "C:\projects\sony-pmca-re\pmca\usb\__init__.py", line 76, in _checkResponse
pmca.usb.InvalidCommandException: MTP error 0x2006
Will 0.17 version add the support of ILCE-9？

**Comment by ma1co** [comment]
The A9 does not support android apps anymore. Additionaly, it has a new firmware format and we don't know the encryption keys. So currently we have no way inside those cameras. I am not aware of any way to dump those keys in the near future. So no, the A9 is not supported.
