### ISSUE TITLE
Error while installing tweak on RX100 V5

### ISSUE THREAD

**Issue by GerryPz** [ma1co/Sony-PMCA-RE#99]
While trying to install Open Memories Tweak...

Traceback (most recent call last):
  File "C:\projects\sony-pmca-re\pmca-gui.py", line 76, in do
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 271, in installCommand
  File "C:\projects\sony-pmca-re\pmca\commands\usb.py", line 159, in importDriver
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\sony-pmca-re\pmca\usb\driver\windows\wpd.py", line 28, in <module>
ImportError: cannot import name '_tagpropertykey'

**Comment by ma1co** [comment]
Please try the [binaries](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
